version: '3.4'

services:
  ipc-webapidatabase:
    container_name: ipc-webapidatabase
    image: "mcr.microsoft.com/mssql/server:latest-ubuntu"
    ports:
      - "1433:1433"
    volumes:
      - mssql-dt-volume:/var/lib/mssqlql/data
    environment:
      SA_PASSWORD: "VerySecretPass1234"
      ACCEPT_EULA: "Y"
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: webapi/Dockerfile
    ports:
      - "6000:6000"
      - "6001:6001"
    volumes:
      #Folders which must be added to the file watcher must be listed below:
      - ./IPC-Project-comparing-api:/IPC-Project-comparing-api\minAPI\webapi1\
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: 1
      ASPNETCORE_URLS: "https://+;http://+"

    depends_on:
      - ipc-webapidatabase

volumes:
  mssql-dt-volume:

