using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataAccess.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    FirstName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LastName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Age = table.Column<int>(type: "int", nullable: false),
                    Email = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Gender = table.Column<int>(type: "int", nullable: false),
                    Framework = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 1, 90, "Beulah.Lesch62@yahoo.com", "Beulah", "DB", 0, "Lesch" },
                    { 2, 55, "Micheal24@gmail.com", "Micheal", "DB", 0, "Daugherty" },
                    { 3, 28, "Debra_Friesen38@yahoo.com", "Debra", "DB", 0, "Friesen" },
                    { 4, 24, "Clayton_Lind@hotmail.com", "Clayton", "DB", 1, "Lind" },
                    { 5, 32, "Mario_Romaguera38@yahoo.com", "Mario", "DB", 0, "Romaguera" },
                    { 6, 32, "Valerie_Schmitt@gmail.com", "Valerie", "DB", 1, "Schmitt" },
                    { 7, 48, "Winifred33@yahoo.com", "Winifred", "DB", 0, "Barton" },
                    { 8, 44, "Winston.OKeefe37@yahoo.com", "Winston", "DB", 0, "O'Keefe" },
                    { 9, 14, "Christopher_Hayes21@hotmail.com", "Christopher", "DB", 1, "Hayes" },
                    { 10, 33, "Ricky61@gmail.com", "Ricky", "DB", 1, "Fisher" },
                    { 11, 56, "Elias35@yahoo.com", "Elias", "DB", 0, "Grant" },
                    { 12, 59, "Charlene.Collins10@hotmail.com", "Charlene", "DB", 1, "Collins" },
                    { 13, 26, "Carl.Glover@gmail.com", "Carl", "DB", 1, "Glover" },
                    { 14, 58, "Molly17@gmail.com", "Molly", "DB", 1, "Grimes" },
                    { 15, 49, "Dora2@hotmail.com", "Dora", "DB", 1, "Marks" },
                    { 16, 66, "Maryann.Olson@hotmail.com", "Maryann", "DB", 0, "Olson" },
                    { 17, 48, "Jacob16@gmail.com", "Jacob", "DB", 1, "Mertz" },
                    { 18, 35, "Lorraine_Harber79@gmail.com", "Lorraine", "DB", 1, "Harber" },
                    { 19, 67, "Steven.Schneider@gmail.com", "Steven", "DB", 1, "Schneider" },
                    { 20, 32, "Carlton21@gmail.com", "Carlton", "DB", 1, "Price" },
                    { 21, 19, "Tommy41@yahoo.com", "Tommy", "DB", 1, "Feil" },
                    { 22, 27, "Rosalie_Waters86@yahoo.com", "Rosalie", "DB", 0, "Waters" },
                    { 23, 67, "Mae.Rowe56@yahoo.com", "Mae", "DB", 1, "Rowe" },
                    { 24, 82, "Bertha.Smitham37@yahoo.com", "Bertha", "DB", 1, "Smitham" },
                    { 25, 8, "June_Nienow70@yahoo.com", "June", "DB", 1, "Nienow" },
                    { 26, 69, "Dean_Strosin@gmail.com", "Dean", "DB", 0, "Strosin" },
                    { 27, 42, "Valerie25@yahoo.com", "Valerie", "DB", 1, "Beahan" },
                    { 28, 41, "Abraham.Weissnat28@hotmail.com", "Abraham", "DB", 1, "Weissnat" },
                    { 29, 56, "Abel.Zboncak@yahoo.com", "Abel", "DB", 0, "Zboncak" },
                    { 30, 69, "Marie.Spinka@yahoo.com", "Marie", "DB", 0, "Spinka" },
                    { 31, 64, "Woodrow.Moore@hotmail.com", "Woodrow", "DB", 1, "Moore" },
                    { 32, 45, "Gertrude_Prohaska71@yahoo.com", "Gertrude", "DB", 1, "Prohaska" },
                    { 33, 73, "Maxine.Ritchie@gmail.com", "Maxine", "DB", 1, "Ritchie" },
                    { 34, 79, "Charlie.Mitchell@yahoo.com", "Charlie", "DB", 0, "Mitchell" },
                    { 35, 40, "Kate.Funk0@yahoo.com", "Kate", "DB", 1, "Funk" },
                    { 36, 17, "Cassandra.Pacocha@yahoo.com", "Cassandra", "DB", 0, "Pacocha" },
                    { 37, 46, "Beatrice_Sipes42@gmail.com", "Beatrice", "DB", 1, "Sipes" },
                    { 38, 33, "Catherine_Rice@gmail.com", "Catherine", "DB", 1, "Rice" },
                    { 39, 37, "Hope.Hodkiewicz@gmail.com", "Hope", "DB", 1, "Hodkiewicz" },
                    { 40, 69, "Jody.Wilderman63@yahoo.com", "Jody", "DB", 1, "Wilderman" },
                    { 41, 70, "Edward_Schaefer57@gmail.com", "Edward", "DB", 1, "Schaefer" },
                    { 42, 30, "Lena_Goldner@gmail.com", "Lena", "DB", 0, "Goldner" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 43, 18, "Troy.Nader34@yahoo.com", "Troy", "DB", 1, "Nader" },
                    { 44, 31, "Eloise_Rice61@yahoo.com", "Eloise", "DB", 1, "Rice" },
                    { 45, 28, "Javier39@gmail.com", "Javier", "DB", 1, "Kilback" },
                    { 46, 90, "Simon.Runolfsson@hotmail.com", "Simon", "DB", 0, "Runolfsson" },
                    { 47, 56, "Laurie_Cruickshank55@yahoo.com", "Laurie", "DB", 1, "Cruickshank" },
                    { 48, 73, "Brandi_Lebsack@gmail.com", "Brandi", "DB", 0, "Lebsack" },
                    { 49, 38, "Teresa_Wilkinson@yahoo.com", "Teresa", "DB", 1, "Wilkinson" },
                    { 50, 35, "Cassandra75@gmail.com", "Cassandra", "DB", 1, "Wilkinson" },
                    { 51, 15, "Victor38@hotmail.com", "Victor", "DB", 1, "Kreiger" },
                    { 52, 15, "Terrance.Monahan97@gmail.com", "Terrance", "DB", 0, "Monahan" },
                    { 53, 83, "Allen_Hudson5@hotmail.com", "Allen", "DB", 0, "Hudson" },
                    { 54, 47, "Salvador_Bernhard65@yahoo.com", "Salvador", "DB", 0, "Bernhard" },
                    { 55, 72, "Katherine8@yahoo.com", "Katherine", "DB", 0, "Crist" },
                    { 56, 33, "Francis_Boyer@gmail.com", "Francis", "DB", 1, "Boyer" },
                    { 57, 60, "Ken.Trantow@yahoo.com", "Ken", "DB", 0, "Trantow" },
                    { 58, 86, "Jeffery.Predovic11@gmail.com", "Jeffery", "DB", 1, "Predovic" },
                    { 59, 15, "Lee_Okuneva@hotmail.com", "Lee", "DB", 0, "Okuneva" },
                    { 60, 72, "Jay.Terry53@hotmail.com", "Jay", "DB", 0, "Terry" },
                    { 61, 50, "Andrea.McCullough@yahoo.com", "Andrea", "DB", 1, "McCullough" },
                    { 62, 54, "Nettie_Renner43@yahoo.com", "Nettie", "DB", 0, "Renner" },
                    { 63, 72, "Mable.Hoeger@gmail.com", "Mable", "DB", 1, "Hoeger" },
                    { 64, 18, "Kenneth.Bauch@gmail.com", "Kenneth", "DB", 0, "Bauch" },
                    { 65, 36, "Bridget_Purdy@gmail.com", "Bridget", "DB", 0, "Purdy" },
                    { 66, 9, "Leo96@gmail.com", "Leo", "DB", 1, "Stehr" },
                    { 67, 13, "Antonia.Hodkiewicz@yahoo.com", "Antonia", "DB", 1, "Hodkiewicz" },
                    { 68, 25, "Paulette.Barrows@yahoo.com", "Paulette", "DB", 0, "Barrows" },
                    { 69, 21, "Cornelius_Casper@hotmail.com", "Cornelius", "DB", 1, "Casper" },
                    { 70, 41, "Marjorie74@hotmail.com", "Marjorie", "DB", 0, "Stokes" },
                    { 71, 72, "Jonathon_Kautzer@yahoo.com", "Jonathon", "DB", 1, "Kautzer" },
                    { 72, 27, "Joseph.Stamm68@hotmail.com", "Joseph", "DB", 0, "Stamm" },
                    { 73, 36, "Ronnie.Bartoletti78@gmail.com", "Ronnie", "DB", 1, "Bartoletti" },
                    { 74, 80, "Katie_Collier56@yahoo.com", "Katie", "DB", 1, "Collier" },
                    { 75, 35, "Tracey_Hand@gmail.com", "Tracey", "DB", 1, "Hand" },
                    { 76, 9, "Lynda83@hotmail.com", "Lynda", "DB", 1, "Marvin" },
                    { 77, 42, "Herbert72@yahoo.com", "Herbert", "DB", 1, "Green" },
                    { 78, 53, "Crystal_Botsford@hotmail.com", "Crystal", "DB", 1, "Botsford" },
                    { 79, 42, "Bethany_Conn81@gmail.com", "Bethany", "DB", 1, "Conn" },
                    { 80, 31, "Pauline_Armstrong34@yahoo.com", "Pauline", "DB", 0, "Armstrong" },
                    { 81, 12, "Marion.Howell93@yahoo.com", "Marion", "DB", 0, "Howell" },
                    { 82, 84, "Philip.Schmidt@hotmail.com", "Philip", "DB", 1, "Schmidt" },
                    { 83, 43, "Todd.Leannon@hotmail.com", "Todd", "DB", 1, "Leannon" },
                    { 84, 20, "Marilyn57@yahoo.com", "Marilyn", "DB", 0, "Armstrong" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 85, 83, "Beverly.Moen@yahoo.com", "Beverly", "DB", 0, "Moen" },
                    { 86, 13, "Arthur.Hauck@yahoo.com", "Arthur", "DB", 0, "Hauck" },
                    { 87, 86, "Oliver_Jast27@hotmail.com", "Oliver", "DB", 1, "Jast" },
                    { 88, 15, "Bessie53@hotmail.com", "Bessie", "DB", 0, "Leuschke" },
                    { 89, 28, "Wilbur.Mann@gmail.com", "Wilbur", "DB", 0, "Mann" },
                    { 90, 9, "Olga_OKon95@yahoo.com", "Olga", "DB", 0, "O'Kon" },
                    { 91, 63, "Nellie_OConnell84@hotmail.com", "Nellie", "DB", 1, "O'Connell" },
                    { 92, 36, "Clayton36@yahoo.com", "Clayton", "DB", 1, "Rogahn" },
                    { 93, 28, "Betsy.Zieme@hotmail.com", "Betsy", "DB", 0, "Zieme" },
                    { 94, 60, "Allan_Jerde@yahoo.com", "Allan", "DB", 1, "Jerde" },
                    { 95, 54, "Raymond39@gmail.com", "Raymond", "DB", 0, "Nikolaus" },
                    { 96, 64, "Ray.Anderson60@hotmail.com", "Ray", "DB", 1, "Anderson" },
                    { 97, 73, "Edmund_Schumm12@gmail.com", "Edmund", "DB", 0, "Schumm" },
                    { 98, 37, "Carole60@yahoo.com", "Carole", "DB", 0, "Oberbrunner" },
                    { 99, 12, "Justin.Lehner@yahoo.com", "Justin", "DB", 1, "Lehner" },
                    { 100, 76, "Darlene67@yahoo.com", "Darlene", "DB", 0, "Runte" },
                    { 101, 57, "Dallas.Spencer18@gmail.com", "Dallas", "DB", 1, "Spencer" },
                    { 102, 15, "Chris_Wiegand@gmail.com", "Chris", "DB", 1, "Wiegand" },
                    { 103, 32, "Victor32@yahoo.com", "Victor", "DB", 1, "Breitenberg" },
                    { 104, 82, "Cary51@hotmail.com", "Cary", "DB", 1, "Nicolas" },
                    { 105, 45, "Marie.Reichel40@yahoo.com", "Marie", "DB", 0, "Reichel" },
                    { 106, 10, "Sara.Rath@yahoo.com", "Sara", "DB", 1, "Rath" },
                    { 107, 54, "Dean32@hotmail.com", "Dean", "DB", 1, "Aufderhar" },
                    { 108, 90, "Lester.Simonis@gmail.com", "Lester", "DB", 0, "Simonis" },
                    { 109, 21, "Judith.Rice79@yahoo.com", "Judith", "DB", 1, "Rice" },
                    { 110, 56, "Nellie7@gmail.com", "Nellie", "DB", 1, "Cummerata" },
                    { 111, 17, "Marc85@yahoo.com", "Marc", "DB", 0, "Osinski" },
                    { 112, 24, "June_Hintz@gmail.com", "June", "DB", 0, "Hintz" },
                    { 113, 11, "Geoffrey.Bartoletti@yahoo.com", "Geoffrey", "DB", 0, "Bartoletti" },
                    { 114, 76, "Alfonso_Funk@gmail.com", "Alfonso", "DB", 0, "Funk" },
                    { 115, 81, "Ebony_Champlin72@yahoo.com", "Ebony", "DB", 0, "Champlin" },
                    { 116, 28, "Russell90@gmail.com", "Russell", "DB", 1, "Heaney" },
                    { 117, 83, "David.Daniel21@hotmail.com", "David", "DB", 1, "Daniel" },
                    { 118, 52, "Traci_VonRueden@hotmail.com", "Traci", "DB", 1, "VonRueden" },
                    { 119, 59, "Terrance86@gmail.com", "Terrance", "DB", 1, "Durgan" },
                    { 120, 27, "Laura96@gmail.com", "Laura", "DB", 0, "Bernier" },
                    { 121, 21, "Floyd_Steuber@gmail.com", "Floyd", "DB", 0, "Steuber" },
                    { 122, 86, "Jessie.Predovic44@yahoo.com", "Jessie", "DB", 1, "Predovic" },
                    { 123, 53, "Margarita.Murazik@yahoo.com", "Margarita", "DB", 0, "Murazik" },
                    { 124, 55, "Pedro_Nitzsche2@yahoo.com", "Pedro", "DB", 1, "Nitzsche" },
                    { 125, 27, "Nichole.Baumbach@hotmail.com", "Nichole", "DB", 0, "Baumbach" },
                    { 126, 86, "Lamar7@yahoo.com", "Lamar", "DB", 1, "Kertzmann" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 127, 42, "Melissa64@hotmail.com", "Melissa", "DB", 0, "Stanton" },
                    { 128, 64, "Tracy.Abshire92@gmail.com", "Tracy", "DB", 1, "Abshire" },
                    { 129, 87, "Enrique_Dietrich@gmail.com", "Enrique", "DB", 1, "Dietrich" },
                    { 130, 71, "Mack.Spencer43@hotmail.com", "Mack", "DB", 0, "Spencer" },
                    { 131, 32, "Colin_Streich80@hotmail.com", "Colin", "DB", 0, "Streich" },
                    { 132, 90, "Harold.Mohr21@yahoo.com", "Harold", "DB", 1, "Mohr" },
                    { 133, 36, "Miguel.Runolfsdottir80@hotmail.com", "Miguel", "DB", 1, "Runolfsdottir" },
                    { 134, 28, "Amber_Lowe67@yahoo.com", "Amber", "DB", 0, "Lowe" },
                    { 135, 67, "Jim_Miller37@yahoo.com", "Jim", "DB", 0, "Miller" },
                    { 136, 16, "Douglas34@gmail.com", "Douglas", "DB", 0, "Cole" },
                    { 137, 12, "Rosemary.Braun38@hotmail.com", "Rosemary", "DB", 0, "Braun" },
                    { 138, 43, "Amanda.Weimann62@yahoo.com", "Amanda", "DB", 0, "Weimann" },
                    { 139, 90, "Bernard82@yahoo.com", "Bernard", "DB", 1, "D'Amore" },
                    { 140, 90, "Leslie_Heathcote46@yahoo.com", "Leslie", "DB", 0, "Heathcote" },
                    { 141, 52, "Janie.Sauer@yahoo.com", "Janie", "DB", 0, "Sauer" },
                    { 142, 29, "Caleb.Langosh53@gmail.com", "Caleb", "DB", 0, "Langosh" },
                    { 143, 80, "Erica5@hotmail.com", "Erica", "DB", 0, "Hamill" },
                    { 144, 50, "Mable66@gmail.com", "Mable", "DB", 1, "Hamill" },
                    { 145, 52, "Bert19@yahoo.com", "Bert", "DB", 1, "Mante" },
                    { 146, 57, "Moses65@gmail.com", "Moses", "DB", 0, "Luettgen" },
                    { 147, 69, "Archie.Heaney20@gmail.com", "Archie", "DB", 0, "Heaney" },
                    { 148, 77, "Archie.Krajcik@gmail.com", "Archie", "DB", 0, "Krajcik" },
                    { 149, 44, "Stacey_Kuvalis77@gmail.com", "Stacey", "DB", 1, "Kuvalis" },
                    { 150, 17, "Hugo36@hotmail.com", "Hugo", "DB", 0, "Bergnaum" },
                    { 151, 36, "Amelia.Zemlak@gmail.com", "Amelia", "DB", 1, "Zemlak" },
                    { 152, 54, "Judith.Kunde61@gmail.com", "Judith", "DB", 1, "Kunde" },
                    { 153, 69, "Derrick_OConnell@gmail.com", "Derrick", "DB", 0, "O'Connell" },
                    { 154, 66, "April94@gmail.com", "April", "DB", 1, "Bartoletti" },
                    { 155, 64, "Roderick_Feest@hotmail.com", "Roderick", "DB", 0, "Feest" },
                    { 156, 45, "Geoffrey0@yahoo.com", "Geoffrey", "DB", 0, "Reinger" },
                    { 157, 26, "Karla.Walter99@gmail.com", "Karla", "DB", 0, "Walter" },
                    { 158, 18, "Melissa_Reilly@gmail.com", "Melissa", "DB", 1, "Reilly" },
                    { 159, 40, "Courtney23@hotmail.com", "Courtney", "DB", 1, "Abernathy" },
                    { 160, 25, "Rudolph5@yahoo.com", "Rudolph", "DB", 1, "O'Reilly" },
                    { 161, 53, "Eva.Borer88@yahoo.com", "Eva", "DB", 0, "Borer" },
                    { 162, 27, "Randal66@gmail.com", "Randal", "DB", 1, "Johns" },
                    { 163, 44, "Francis_Kilback97@hotmail.com", "Francis", "DB", 1, "Kilback" },
                    { 164, 62, "Rene.Quigley69@gmail.com", "Rene", "DB", 0, "Quigley" },
                    { 165, 69, "Amy_Stracke@hotmail.com", "Amy", "DB", 1, "Stracke" },
                    { 166, 23, "Rogelio.Krajcik@yahoo.com", "Rogelio", "DB", 0, "Krajcik" },
                    { 167, 68, "Joyce.Schmitt37@gmail.com", "Joyce", "DB", 0, "Schmitt" },
                    { 168, 18, "Meredith_Bergstrom@yahoo.com", "Meredith", "DB", 1, "Bergstrom" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 169, 55, "Lance28@yahoo.com", "Lance", "DB", 1, "Gutkowski" },
                    { 170, 59, "Julius76@gmail.com", "Julius", "DB", 1, "Conn" },
                    { 171, 81, "Juan6@hotmail.com", "Juan", "DB", 1, "Reynolds" },
                    { 172, 79, "Kristina9@gmail.com", "Kristina", "DB", 1, "Hahn" },
                    { 173, 15, "Tomas_Kutch@hotmail.com", "Tomas", "DB", 0, "Kutch" },
                    { 174, 14, "Guadalupe.Renner@yahoo.com", "Guadalupe", "DB", 0, "Renner" },
                    { 175, 64, "Lindsay12@gmail.com", "Lindsay", "DB", 1, "Schinner" },
                    { 176, 31, "Lonnie91@yahoo.com", "Lonnie", "DB", 1, "Nienow" },
                    { 177, 14, "Preston.Smitham94@yahoo.com", "Preston", "DB", 1, "Smitham" },
                    { 178, 12, "Scott70@gmail.com", "Scott", "DB", 0, "Pagac" },
                    { 179, 68, "Beth.Carroll16@gmail.com", "Beth", "DB", 0, "Carroll" },
                    { 180, 33, "Eula_Stark99@hotmail.com", "Eula", "DB", 1, "Stark" },
                    { 181, 49, "Ted_Nitzsche52@hotmail.com", "Ted", "DB", 1, "Nitzsche" },
                    { 182, 41, "Tim.Ritchie@yahoo.com", "Tim", "DB", 1, "Ritchie" },
                    { 183, 50, "Otis.McClure87@gmail.com", "Otis", "DB", 0, "McClure" },
                    { 184, 68, "Neal_Kertzmann84@hotmail.com", "Neal", "DB", 0, "Kertzmann" },
                    { 185, 76, "Brent.Pacocha61@yahoo.com", "Brent", "DB", 1, "Pacocha" },
                    { 186, 63, "Wesley.Hyatt88@hotmail.com", "Wesley", "DB", 1, "Hyatt" },
                    { 187, 33, "Matthew.Legros@hotmail.com", "Matthew", "DB", 0, "Legros" },
                    { 188, 17, "Melba_Gulgowski88@gmail.com", "Melba", "DB", 1, "Gulgowski" },
                    { 189, 24, "Derek93@yahoo.com", "Derek", "DB", 0, "Labadie" },
                    { 190, 13, "Clyde.MacGyver59@hotmail.com", "Clyde", "DB", 0, "MacGyver" },
                    { 191, 74, "Amanda8@yahoo.com", "Amanda", "DB", 0, "Wintheiser" },
                    { 192, 35, "Jeannette1@yahoo.com", "Jeannette", "DB", 0, "Mohr" },
                    { 193, 44, "Kathleen34@hotmail.com", "Kathleen", "DB", 0, "Hagenes" },
                    { 194, 63, "Donnie5@yahoo.com", "Donnie", "DB", 0, "Wyman" },
                    { 195, 78, "Angelo_Bergnaum@gmail.com", "Angelo", "DB", 0, "Bergnaum" },
                    { 196, 36, "Percy.Cormier@yahoo.com", "Percy", "DB", 0, "Cormier" },
                    { 197, 55, "Randy.McLaughlin@hotmail.com", "Randy", "DB", 0, "McLaughlin" },
                    { 198, 44, "Carl_Shields@gmail.com", "Carl", "DB", 0, "Shields" },
                    { 199, 69, "Muriel.Klocko35@yahoo.com", "Muriel", "DB", 1, "Klocko" },
                    { 200, 69, "Yolanda_Gutmann@gmail.com", "Yolanda", "DB", 0, "Gutmann" },
                    { 201, 85, "Domingo.Crona@gmail.com", "Domingo", "DB", 1, "Crona" },
                    { 202, 71, "Beulah_Ratke@hotmail.com", "Beulah", "DB", 1, "Ratke" },
                    { 203, 56, "Irma.Terry64@gmail.com", "Irma", "DB", 0, "Terry" },
                    { 204, 47, "Alfred_Kautzer68@yahoo.com", "Alfred", "DB", 1, "Kautzer" },
                    { 205, 83, "Claire.Douglas85@yahoo.com", "Claire", "DB", 0, "Douglas" },
                    { 206, 90, "Jordan88@gmail.com", "Jordan", "DB", 1, "Wiza" },
                    { 207, 47, "Stanley_Cummings41@gmail.com", "Stanley", "DB", 0, "Cummings" },
                    { 208, 40, "Nelson_Koss@yahoo.com", "Nelson", "DB", 0, "Koss" },
                    { 209, 9, "Randolph_Klocko@hotmail.com", "Randolph", "DB", 0, "Klocko" },
                    { 210, 64, "Kim_Heathcote@hotmail.com", "Kim", "DB", 0, "Heathcote" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 211, 54, "Kristina25@hotmail.com", "Kristina", "DB", 1, "Trantow" },
                    { 212, 40, "Nathaniel.Auer@yahoo.com", "Nathaniel", "DB", 0, "Auer" },
                    { 213, 77, "Enrique_Feil44@hotmail.com", "Enrique", "DB", 0, "Feil" },
                    { 214, 16, "Seth_Rolfson22@yahoo.com", "Seth", "DB", 1, "Rolfson" },
                    { 215, 13, "Natasha.Wuckert@yahoo.com", "Natasha", "DB", 1, "Wuckert" },
                    { 216, 86, "Lydia_Deckow@yahoo.com", "Lydia", "DB", 1, "Deckow" },
                    { 217, 29, "Lorena_Treutel@yahoo.com", "Lorena", "DB", 1, "Treutel" },
                    { 218, 25, "Luke31@gmail.com", "Luke", "DB", 0, "Littel" },
                    { 219, 66, "Jacqueline91@hotmail.com", "Jacqueline", "DB", 1, "Rempel" },
                    { 220, 68, "Theresa25@hotmail.com", "Theresa", "DB", 1, "Cruickshank" },
                    { 221, 72, "Pat_Stracke@yahoo.com", "Pat", "DB", 1, "Stracke" },
                    { 222, 31, "Lynn56@gmail.com", "Lynn", "DB", 1, "Pollich" },
                    { 223, 89, "Evelyn_Ratke@yahoo.com", "Evelyn", "DB", 1, "Ratke" },
                    { 224, 50, "Sammy47@yahoo.com", "Sammy", "DB", 1, "Cole" },
                    { 225, 71, "Irma64@yahoo.com", "Irma", "DB", 1, "Herman" },
                    { 226, 12, "Sally_Hermann19@yahoo.com", "Sally", "DB", 0, "Hermann" },
                    { 227, 37, "Brooke.Tromp73@yahoo.com", "Brooke", "DB", 1, "Tromp" },
                    { 228, 30, "Pat51@hotmail.com", "Pat", "DB", 1, "Keeling" },
                    { 229, 20, "Glenda_Becker23@yahoo.com", "Glenda", "DB", 1, "Becker" },
                    { 230, 8, "Leroy_Paucek@hotmail.com", "Leroy", "DB", 1, "Paucek" },
                    { 231, 80, "Shawna98@yahoo.com", "Shawna", "DB", 1, "Kshlerin" },
                    { 232, 69, "Brian_Bashirian79@hotmail.com", "Brian", "DB", 1, "Bashirian" },
                    { 233, 21, "Alexis.Keeling28@hotmail.com", "Alexis", "DB", 1, "Keeling" },
                    { 234, 50, "Stanley_Zemlak50@yahoo.com", "Stanley", "DB", 0, "Zemlak" },
                    { 235, 78, "Michael_Green83@hotmail.com", "Michael", "DB", 0, "Green" },
                    { 236, 74, "Tamara.Leuschke62@yahoo.com", "Tamara", "DB", 1, "Leuschke" },
                    { 237, 32, "Julio_Brown@gmail.com", "Julio", "DB", 0, "Brown" },
                    { 238, 47, "Elijah_Douglas@hotmail.com", "Elijah", "DB", 0, "Douglas" },
                    { 239, 60, "Kay96@yahoo.com", "Kay", "DB", 1, "Champlin" },
                    { 240, 37, "Earnest_Fritsch75@gmail.com", "Earnest", "DB", 0, "Fritsch" },
                    { 241, 50, "Jody.Haag90@hotmail.com", "Jody", "DB", 0, "Haag" },
                    { 242, 38, "Bridget32@hotmail.com", "Bridget", "DB", 0, "Olson" },
                    { 243, 16, "Desiree.Gutkowski@hotmail.com", "Desiree", "DB", 0, "Gutkowski" },
                    { 244, 32, "Ruby_Treutel42@gmail.com", "Ruby", "DB", 0, "Treutel" },
                    { 245, 29, "Melvin.Reinger34@hotmail.com", "Melvin", "DB", 0, "Reinger" },
                    { 246, 11, "Antoinette_Considine43@gmail.com", "Antoinette", "DB", 1, "Considine" },
                    { 247, 65, "Philip1@gmail.com", "Philip", "DB", 1, "Rogahn" },
                    { 248, 51, "Hazel64@hotmail.com", "Hazel", "DB", 0, "Hermiston" },
                    { 249, 24, "Lula.Kautzer@gmail.com", "Lula", "DB", 1, "Kautzer" },
                    { 250, 62, "Jeffrey63@yahoo.com", "Jeffrey", "DB", 0, "Schoen" },
                    { 251, 77, "Sally_Bednar41@gmail.com", "Sally", "DB", 0, "Bednar" },
                    { 252, 49, "Harold28@gmail.com", "Harold", "DB", 0, "Hermann" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 253, 33, "Archie60@hotmail.com", "Archie", "DB", 1, "Schoen" },
                    { 254, 84, "Latoya_Schroeder@gmail.com", "Latoya", "DB", 1, "Schroeder" },
                    { 255, 73, "Belinda_Torp8@hotmail.com", "Belinda", "DB", 1, "Torp" },
                    { 256, 26, "Karl.Wiegand82@hotmail.com", "Karl", "DB", 1, "Wiegand" },
                    { 257, 76, "Ida_DAmore@gmail.com", "Ida", "DB", 1, "D'Amore" },
                    { 258, 82, "Mae.Ziemann@hotmail.com", "Mae", "DB", 0, "Ziemann" },
                    { 259, 20, "Herbert.Lebsack21@gmail.com", "Herbert", "DB", 0, "Lebsack" },
                    { 260, 73, "Wanda.Smitham8@yahoo.com", "Wanda", "DB", 0, "Smitham" },
                    { 261, 38, "Donald39@yahoo.com", "Donald", "DB", 0, "Sanford" },
                    { 262, 82, "Carolyn.Kuvalis19@yahoo.com", "Carolyn", "DB", 1, "Kuvalis" },
                    { 263, 57, "Shawn.Wisoky76@hotmail.com", "Shawn", "DB", 1, "Wisoky" },
                    { 264, 38, "Kerry.Fay25@gmail.com", "Kerry", "DB", 1, "Fay" },
                    { 265, 55, "Ellis32@yahoo.com", "Ellis", "DB", 0, "Schmitt" },
                    { 266, 88, "John.Block@hotmail.com", "John", "DB", 1, "Block" },
                    { 267, 12, "Bertha21@gmail.com", "Bertha", "DB", 1, "Welch" },
                    { 268, 35, "Joseph_Littel1@gmail.com", "Joseph", "DB", 0, "Littel" },
                    { 269, 56, "Belinda43@yahoo.com", "Belinda", "DB", 1, "Stokes" },
                    { 270, 16, "Gene9@hotmail.com", "Gene", "DB", 1, "Abbott" },
                    { 271, 9, "Francis_Schuppe83@gmail.com", "Francis", "DB", 1, "Schuppe" },
                    { 272, 54, "Al.Harber25@yahoo.com", "Al", "DB", 0, "Harber" },
                    { 273, 14, "Violet46@hotmail.com", "Violet", "DB", 1, "Cummerata" },
                    { 274, 68, "Guillermo.Breitenberg8@hotmail.com", "Guillermo", "DB", 0, "Breitenberg" },
                    { 275, 59, "Nancy_Kuhn@hotmail.com", "Nancy", "DB", 0, "Kuhn" },
                    { 276, 66, "Delores.Durgan@gmail.com", "Delores", "DB", 1, "Durgan" },
                    { 277, 51, "Mildred12@yahoo.com", "Mildred", "DB", 1, "Boyer" },
                    { 278, 38, "Stanley.Huel75@hotmail.com", "Stanley", "DB", 0, "Huel" },
                    { 279, 46, "Floyd.Collier64@hotmail.com", "Floyd", "DB", 0, "Collier" },
                    { 280, 10, "Arthur_Jerde4@yahoo.com", "Arthur", "DB", 1, "Jerde" },
                    { 281, 22, "Lillian97@hotmail.com", "Lillian", "DB", 0, "Fadel" },
                    { 282, 83, "Duane89@hotmail.com", "Duane", "DB", 1, "Nader" },
                    { 283, 86, "Nicholas.Mertz25@yahoo.com", "Nicholas", "DB", 0, "Mertz" },
                    { 284, 38, "Marco.Schaden@yahoo.com", "Marco", "DB", 1, "Schaden" },
                    { 285, 85, "Ashley.Brown@yahoo.com", "Ashley", "DB", 1, "Brown" },
                    { 286, 77, "Marlon.Friesen@yahoo.com", "Marlon", "DB", 0, "Friesen" },
                    { 287, 39, "Darrell32@gmail.com", "Darrell", "DB", 0, "Weimann" },
                    { 288, 69, "Tami31@hotmail.com", "Tami", "DB", 0, "Zemlak" },
                    { 289, 55, "Stewart_Leannon@gmail.com", "Stewart", "DB", 1, "Leannon" },
                    { 290, 13, "Kelvin_Russel@gmail.com", "Kelvin", "DB", 1, "Russel" },
                    { 291, 17, "Delores87@gmail.com", "Delores", "DB", 1, "Brekke" },
                    { 292, 49, "Lillian67@gmail.com", "Lillian", "DB", 0, "Prosacco" },
                    { 293, 60, "Juana10@hotmail.com", "Juana", "DB", 0, "Pacocha" },
                    { 294, 48, "Ruby.Murray@yahoo.com", "Ruby", "DB", 0, "Murray" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 295, 34, "Winston_Walsh84@hotmail.com", "Winston", "DB", 1, "Walsh" },
                    { 296, 71, "Sheryl25@hotmail.com", "Sheryl", "DB", 0, "Grant" },
                    { 297, 81, "Felicia_Schmeler@gmail.com", "Felicia", "DB", 1, "Schmeler" },
                    { 298, 86, "Hope.Oberbrunner@hotmail.com", "Hope", "DB", 0, "Oberbrunner" },
                    { 299, 65, "Timmy8@gmail.com", "Timmy", "DB", 1, "Russel" },
                    { 300, 47, "Julio.Beahan50@gmail.com", "Julio", "DB", 1, "Beahan" },
                    { 301, 78, "Shirley_Leannon@gmail.com", "Shirley", "DB", 0, "Leannon" },
                    { 302, 30, "Conrad_Dickens29@yahoo.com", "Conrad", "DB", 0, "Dickens" },
                    { 303, 12, "Kent98@yahoo.com", "Kent", "DB", 0, "Marks" },
                    { 304, 89, "Jackie29@gmail.com", "Jackie", "DB", 1, "Bergstrom" },
                    { 305, 56, "Craig_Klocko19@hotmail.com", "Craig", "DB", 0, "Klocko" },
                    { 306, 82, "Patricia.Heller@gmail.com", "Patricia", "DB", 0, "Heller" },
                    { 307, 78, "Phillip_DuBuque99@yahoo.com", "Phillip", "DB", 0, "DuBuque" },
                    { 308, 36, "Winifred.Hahn@gmail.com", "Winifred", "DB", 0, "Hahn" },
                    { 309, 17, "Antonia.Kemmer96@gmail.com", "Antonia", "DB", 1, "Kemmer" },
                    { 310, 14, "Jordan.Mann@gmail.com", "Jordan", "DB", 1, "Mann" },
                    { 311, 83, "Martin.Bogan98@gmail.com", "Martin", "DB", 1, "Bogan" },
                    { 312, 48, "Sue.Mitchell71@hotmail.com", "Sue", "DB", 1, "Mitchell" },
                    { 313, 82, "Dorothy.Tillman74@hotmail.com", "Dorothy", "DB", 0, "Tillman" },
                    { 314, 16, "Clyde.Vandervort@yahoo.com", "Clyde", "DB", 0, "Vandervort" },
                    { 315, 47, "Natalie.Anderson55@hotmail.com", "Natalie", "DB", 1, "Anderson" },
                    { 316, 45, "Cecil_Hoppe41@yahoo.com", "Cecil", "DB", 1, "Hoppe" },
                    { 317, 21, "Chelsea.Bechtelar5@hotmail.com", "Chelsea", "DB", 0, "Bechtelar" },
                    { 318, 28, "Timothy79@yahoo.com", "Timothy", "DB", 0, "Dibbert" },
                    { 319, 51, "Sally_Emmerich47@hotmail.com", "Sally", "DB", 1, "Emmerich" },
                    { 320, 59, "Randall.Legros55@yahoo.com", "Randall", "DB", 0, "Legros" },
                    { 321, 22, "Benjamin.Hyatt0@hotmail.com", "Benjamin", "DB", 0, "Hyatt" },
                    { 322, 13, "Clint_Langworth@gmail.com", "Clint", "DB", 1, "Langworth" },
                    { 323, 36, "Calvin_Reichel@hotmail.com", "Calvin", "DB", 0, "Reichel" },
                    { 324, 80, "Tracy_West62@gmail.com", "Tracy", "DB", 0, "West" },
                    { 325, 88, "Carol.Auer@gmail.com", "Carol", "DB", 0, "Auer" },
                    { 326, 59, "Gayle91@hotmail.com", "Gayle", "DB", 1, "Dietrich" },
                    { 327, 17, "Marcia_Daugherty49@hotmail.com", "Marcia", "DB", 1, "Daugherty" },
                    { 328, 42, "Jonathan_VonRueden41@gmail.com", "Jonathan", "DB", 1, "VonRueden" },
                    { 329, 78, "Adrian.Terry0@gmail.com", "Adrian", "DB", 1, "Terry" },
                    { 330, 19, "Lucille.Altenwerth97@yahoo.com", "Lucille", "DB", 1, "Altenwerth" },
                    { 331, 72, "Gertrude.Greenfelder64@yahoo.com", "Gertrude", "DB", 0, "Greenfelder" },
                    { 332, 78, "Mary30@gmail.com", "Mary", "DB", 1, "Haley" },
                    { 333, 65, "Bob.Botsford@gmail.com", "Bob", "DB", 0, "Botsford" },
                    { 334, 46, "Darrel.Windler50@hotmail.com", "Darrel", "DB", 1, "Windler" },
                    { 335, 9, "Jordan9@gmail.com", "Jordan", "DB", 1, "Powlowski" },
                    { 336, 70, "Jan.Tillman@yahoo.com", "Jan", "DB", 0, "Tillman" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 337, 73, "Frank11@gmail.com", "Frank", "DB", 1, "Welch" },
                    { 338, 40, "Alice.Auer99@gmail.com", "Alice", "DB", 0, "Auer" },
                    { 339, 74, "Virginia99@hotmail.com", "Virginia", "DB", 0, "Kessler" },
                    { 340, 25, "Valerie_Purdy11@hotmail.com", "Valerie", "DB", 1, "Purdy" },
                    { 341, 45, "Melanie95@gmail.com", "Melanie", "DB", 0, "Gleason" },
                    { 342, 44, "Kent_Pouros@hotmail.com", "Kent", "DB", 0, "Pouros" },
                    { 343, 14, "Clark.Hintz@gmail.com", "Clark", "DB", 1, "Hintz" },
                    { 344, 80, "Kerry.Christiansen68@gmail.com", "Kerry", "DB", 1, "Christiansen" },
                    { 345, 46, "Kelley.Howe31@hotmail.com", "Kelley", "DB", 0, "Howe" },
                    { 346, 23, "Karen94@hotmail.com", "Karen", "DB", 0, "Hagenes" },
                    { 347, 64, "Elvira_Bahringer31@hotmail.com", "Elvira", "DB", 1, "Bahringer" },
                    { 348, 33, "Gregg.Daniel@yahoo.com", "Gregg", "DB", 0, "Daniel" },
                    { 349, 36, "Julio60@hotmail.com", "Julio", "DB", 1, "Johns" },
                    { 350, 19, "Arlene_Auer70@yahoo.com", "Arlene", "DB", 1, "Auer" },
                    { 351, 68, "Garrett_Kuhn@gmail.com", "Garrett", "DB", 0, "Kuhn" },
                    { 352, 23, "Renee_Nicolas@gmail.com", "Renee", "DB", 1, "Nicolas" },
                    { 353, 65, "Terry.Olson@hotmail.com", "Terry", "DB", 1, "Olson" },
                    { 354, 40, "Emily.Maggio19@gmail.com", "Emily", "DB", 1, "Maggio" },
                    { 355, 39, "Horace10@gmail.com", "Horace", "DB", 1, "Bode" },
                    { 356, 69, "Julio50@gmail.com", "Julio", "DB", 1, "Mitchell" },
                    { 357, 12, "Leona.Kuhn39@gmail.com", "Leona", "DB", 0, "Kuhn" },
                    { 358, 41, "Jackie_Weber@yahoo.com", "Jackie", "DB", 0, "Weber" },
                    { 359, 78, "Arturo31@hotmail.com", "Arturo", "DB", 1, "Senger" },
                    { 360, 45, "Lena_Crist@hotmail.com", "Lena", "DB", 1, "Crist" },
                    { 361, 71, "Bertha51@yahoo.com", "Bertha", "DB", 0, "Kunde" },
                    { 362, 78, "Ernest_White@gmail.com", "Ernest", "DB", 1, "White" },
                    { 363, 58, "Terrence.Grant@hotmail.com", "Terrence", "DB", 1, "Grant" },
                    { 364, 40, "Roderick_Cronin47@hotmail.com", "Roderick", "DB", 0, "Cronin" },
                    { 365, 71, "Patrick.Jakubowski@gmail.com", "Patrick", "DB", 1, "Jakubowski" },
                    { 366, 75, "Beth.Deckow66@hotmail.com", "Beth", "DB", 1, "Deckow" },
                    { 367, 34, "Yvonne.Schimmel82@gmail.com", "Yvonne", "DB", 0, "Schimmel" },
                    { 368, 64, "Gordon65@yahoo.com", "Gordon", "DB", 1, "Zieme" },
                    { 369, 23, "Alfred75@hotmail.com", "Alfred", "DB", 0, "Rogahn" },
                    { 370, 26, "Santiago.Mraz66@hotmail.com", "Santiago", "DB", 1, "Mraz" },
                    { 371, 31, "Irvin_McGlynn@gmail.com", "Irvin", "DB", 1, "McGlynn" },
                    { 372, 42, "Enrique2@hotmail.com", "Enrique", "DB", 1, "Lemke" },
                    { 373, 87, "Marco10@gmail.com", "Marco", "DB", 0, "Lebsack" },
                    { 374, 45, "Agnes.McDermott@yahoo.com", "Agnes", "DB", 0, "McDermott" },
                    { 375, 70, "Mathew_Rice@gmail.com", "Mathew", "DB", 0, "Rice" },
                    { 376, 64, "Cary.Shanahan22@yahoo.com", "Cary", "DB", 0, "Shanahan" },
                    { 377, 62, "Sergio90@yahoo.com", "Sergio", "DB", 1, "Nitzsche" },
                    { 378, 70, "Santos.Koelpin51@gmail.com", "Santos", "DB", 0, "Koelpin" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 379, 21, "Luke_Walter97@yahoo.com", "Luke", "DB", 0, "Walter" },
                    { 380, 63, "Keith_Hintz56@yahoo.com", "Keith", "DB", 0, "Hintz" },
                    { 381, 64, "Manuel_Schmeler@yahoo.com", "Manuel", "DB", 1, "Schmeler" },
                    { 382, 65, "Chris.Quigley@hotmail.com", "Chris", "DB", 0, "Quigley" },
                    { 383, 20, "Gina41@hotmail.com", "Gina", "DB", 1, "Kovacek" },
                    { 384, 81, "Pauline_Crist@hotmail.com", "Pauline", "DB", 0, "Crist" },
                    { 385, 11, "David64@hotmail.com", "David", "DB", 1, "Parisian" },
                    { 386, 25, "Warren_Gottlieb81@yahoo.com", "Warren", "DB", 0, "Gottlieb" },
                    { 387, 38, "Deanna0@hotmail.com", "Deanna", "DB", 0, "Ebert" },
                    { 388, 76, "Rex78@yahoo.com", "Rex", "DB", 1, "Bradtke" },
                    { 389, 77, "Miriam39@gmail.com", "Miriam", "DB", 0, "Strosin" },
                    { 390, 81, "Elaine_Jenkins81@hotmail.com", "Elaine", "DB", 1, "Jenkins" },
                    { 391, 66, "Brad_Harris92@hotmail.com", "Brad", "DB", 1, "Harris" },
                    { 392, 70, "Judy_Gerlach@gmail.com", "Judy", "DB", 0, "Gerlach" },
                    { 393, 33, "Elijah_Heidenreich@hotmail.com", "Elijah", "DB", 0, "Heidenreich" },
                    { 394, 63, "Katie.Sipes32@yahoo.com", "Katie", "DB", 0, "Sipes" },
                    { 395, 65, "Tracey_Connelly@hotmail.com", "Tracey", "DB", 1, "Connelly" },
                    { 396, 86, "Angela_DuBuque@gmail.com", "Angela", "DB", 0, "DuBuque" },
                    { 397, 88, "Antoinette8@hotmail.com", "Antoinette", "DB", 1, "Satterfield" },
                    { 398, 28, "Israel.Maggio60@gmail.com", "Israel", "DB", 1, "Maggio" },
                    { 399, 33, "Rex37@hotmail.com", "Rex", "DB", 1, "Rice" },
                    { 400, 31, "Tricia.Walker@gmail.com", "Tricia", "DB", 0, "Walker" },
                    { 401, 76, "Evan72@yahoo.com", "Evan", "DB", 1, "Ondricka" },
                    { 402, 56, "Melinda.OReilly35@yahoo.com", "Melinda", "DB", 0, "O'Reilly" },
                    { 403, 24, "Debbie_Barrows77@hotmail.com", "Debbie", "DB", 1, "Barrows" },
                    { 404, 86, "Wayne.Gislason@hotmail.com", "Wayne", "DB", 0, "Gislason" },
                    { 405, 64, "Elena43@gmail.com", "Elena", "DB", 0, "Little" },
                    { 406, 86, "Brandi21@hotmail.com", "Brandi", "DB", 1, "Rempel" },
                    { 407, 42, "Orlando.Grady@gmail.com", "Orlando", "DB", 0, "Grady" },
                    { 408, 90, "Phillip.Wehner50@yahoo.com", "Phillip", "DB", 0, "Wehner" },
                    { 409, 84, "Virgil.Deckow@hotmail.com", "Virgil", "DB", 1, "Deckow" },
                    { 410, 88, "Harvey_McGlynn@hotmail.com", "Harvey", "DB", 0, "McGlynn" },
                    { 411, 87, "Antonia.Jaskolski@gmail.com", "Antonia", "DB", 0, "Jaskolski" },
                    { 412, 64, "Bernadette40@gmail.com", "Bernadette", "DB", 0, "Lynch" },
                    { 413, 22, "Darlene_Mitchell@yahoo.com", "Darlene", "DB", 0, "Mitchell" },
                    { 414, 46, "Ana_Rohan67@hotmail.com", "Ana", "DB", 1, "Rohan" },
                    { 415, 66, "Ross_Schmeler@hotmail.com", "Ross", "DB", 0, "Schmeler" },
                    { 416, 86, "Blanca59@yahoo.com", "Blanca", "DB", 0, "Hettinger" },
                    { 417, 84, "Israel28@yahoo.com", "Israel", "DB", 1, "Schiller" },
                    { 418, 13, "Jessica_Gulgowski96@yahoo.com", "Jessica", "DB", 0, "Gulgowski" },
                    { 419, 41, "Cesar77@gmail.com", "Cesar", "DB", 1, "Bergstrom" },
                    { 420, 37, "Chris_Kreiger@gmail.com", "Chris", "DB", 1, "Kreiger" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 421, 52, "Al_McGlynn@hotmail.com", "Al", "DB", 0, "McGlynn" },
                    { 422, 12, "Ignacio90@gmail.com", "Ignacio", "DB", 0, "Orn" },
                    { 423, 78, "Henrietta.Mohr@hotmail.com", "Henrietta", "DB", 0, "Mohr" },
                    { 424, 9, "Darryl_Greenfelder@gmail.com", "Darryl", "DB", 0, "Greenfelder" },
                    { 425, 28, "Madeline20@yahoo.com", "Madeline", "DB", 1, "Ziemann" },
                    { 426, 56, "Delores13@hotmail.com", "Delores", "DB", 1, "Legros" },
                    { 427, 15, "Dana_Walker@yahoo.com", "Dana", "DB", 1, "Walker" },
                    { 428, 58, "Irene.Nolan@hotmail.com", "Irene", "DB", 0, "Nolan" },
                    { 429, 27, "Penny_Gislason@yahoo.com", "Penny", "DB", 0, "Gislason" },
                    { 430, 49, "Justin.Kiehn32@yahoo.com", "Justin", "DB", 1, "Kiehn" },
                    { 431, 78, "Scott.Klocko@gmail.com", "Scott", "DB", 0, "Klocko" },
                    { 432, 26, "Lillie_Koch@yahoo.com", "Lillie", "DB", 1, "Koch" },
                    { 433, 59, "Phyllis.Leffler28@hotmail.com", "Phyllis", "DB", 1, "Leffler" },
                    { 434, 64, "Lowell_Crist24@yahoo.com", "Lowell", "DB", 0, "Crist" },
                    { 435, 77, "Terry.Walsh21@hotmail.com", "Terry", "DB", 0, "Walsh" },
                    { 436, 86, "Danny77@hotmail.com", "Danny", "DB", 0, "Blick" },
                    { 437, 64, "Florence_Crona@yahoo.com", "Florence", "DB", 1, "Crona" },
                    { 438, 74, "Preston.Schiller@gmail.com", "Preston", "DB", 0, "Schiller" },
                    { 439, 60, "Clara.West60@hotmail.com", "Clara", "DB", 0, "West" },
                    { 440, 69, "Bernadette64@hotmail.com", "Bernadette", "DB", 0, "Gottlieb" },
                    { 441, 46, "Peggy.Wisoky@hotmail.com", "Peggy", "DB", 1, "Wisoky" },
                    { 442, 86, "Miranda71@gmail.com", "Miranda", "DB", 0, "Weissnat" },
                    { 443, 44, "Jenna.Wintheiser22@yahoo.com", "Jenna", "DB", 0, "Wintheiser" },
                    { 444, 56, "Brent94@yahoo.com", "Brent", "DB", 0, "Wiegand" },
                    { 445, 11, "Lorraine.Howell@yahoo.com", "Lorraine", "DB", 0, "Howell" },
                    { 446, 9, "Wm10@yahoo.com", "Wm", "DB", 1, "Turner" },
                    { 447, 51, "Brittany27@yahoo.com", "Brittany", "DB", 1, "Fritsch" },
                    { 448, 83, "Diana48@gmail.com", "Diana", "DB", 0, "Hoeger" },
                    { 449, 56, "Virginia_Dibbert63@gmail.com", "Virginia", "DB", 1, "Dibbert" },
                    { 450, 46, "Dustin_Boyle@yahoo.com", "Dustin", "DB", 0, "Boyle" },
                    { 451, 70, "Evelyn.Weber@hotmail.com", "Evelyn", "DB", 1, "Weber" },
                    { 452, 37, "Raymond39@yahoo.com", "Raymond", "DB", 0, "Graham" },
                    { 453, 69, "Whitney_Tremblay25@gmail.com", "Whitney", "DB", 1, "Tremblay" },
                    { 454, 78, "Jimmy13@yahoo.com", "Jimmy", "DB", 0, "Pfeffer" },
                    { 455, 51, "Eula1@hotmail.com", "Eula", "DB", 0, "Nikolaus" },
                    { 456, 35, "Dewey.Wintheiser@yahoo.com", "Dewey", "DB", 1, "Wintheiser" },
                    { 457, 68, "Lance_Dickens@yahoo.com", "Lance", "DB", 0, "Dickens" },
                    { 458, 44, "Hugh.Sporer@yahoo.com", "Hugh", "DB", 0, "Sporer" },
                    { 459, 54, "Larry83@hotmail.com", "Larry", "DB", 0, "Reynolds" },
                    { 460, 88, "Ruben79@hotmail.com", "Ruben", "DB", 0, "Buckridge" },
                    { 461, 78, "Clara.Ward@yahoo.com", "Clara", "DB", 1, "Ward" },
                    { 462, 82, "Mindy25@gmail.com", "Mindy", "DB", 1, "Heidenreich" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 463, 77, "Sadie86@gmail.com", "Sadie", "DB", 1, "Dietrich" },
                    { 464, 63, "Heather.Robel78@hotmail.com", "Heather", "DB", 0, "Robel" },
                    { 465, 35, "Tracy.Shields20@yahoo.com", "Tracy", "DB", 0, "Shields" },
                    { 466, 34, "Gertrude.Kihn@hotmail.com", "Gertrude", "DB", 1, "Kihn" },
                    { 467, 85, "Zachary33@gmail.com", "Zachary", "DB", 0, "Hegmann" },
                    { 468, 58, "Irving66@yahoo.com", "Irving", "DB", 1, "Effertz" },
                    { 469, 43, "Johnnie90@yahoo.com", "Johnnie", "DB", 0, "Hartmann" },
                    { 470, 48, "Rachael2@yahoo.com", "Rachael", "DB", 1, "Powlowski" },
                    { 471, 72, "Lee_Ratke@hotmail.com", "Lee", "DB", 0, "Ratke" },
                    { 472, 34, "Meredith.Hilpert@yahoo.com", "Meredith", "DB", 1, "Hilpert" },
                    { 473, 86, "Mary_Mante82@hotmail.com", "Mary", "DB", 0, "Mante" },
                    { 474, 33, "Fred_Haag@yahoo.com", "Fred", "DB", 0, "Haag" },
                    { 475, 21, "Tanya_Lebsack36@yahoo.com", "Tanya", "DB", 0, "Lebsack" },
                    { 476, 12, "Silvia81@yahoo.com", "Silvia", "DB", 0, "Quitzon" },
                    { 477, 57, "Lynn.West@gmail.com", "Lynn", "DB", 0, "West" },
                    { 478, 40, "Terrance.Haag67@gmail.com", "Terrance", "DB", 0, "Haag" },
                    { 479, 28, "Andrea.Beier@yahoo.com", "Andrea", "DB", 0, "Beier" },
                    { 480, 82, "Violet.Cormier71@gmail.com", "Violet", "DB", 1, "Cormier" },
                    { 481, 18, "Jane30@yahoo.com", "Jane", "DB", 0, "Haley" },
                    { 482, 61, "Preston61@gmail.com", "Preston", "DB", 1, "Yost" },
                    { 483, 18, "Jenny89@gmail.com", "Jenny", "DB", 0, "Larson" },
                    { 484, 83, "Diana.Wilderman36@hotmail.com", "Diana", "DB", 0, "Wilderman" },
                    { 485, 42, "Darrell_Schuster51@hotmail.com", "Darrell", "DB", 0, "Schuster" },
                    { 486, 17, "Veronica_Weber@gmail.com", "Veronica", "DB", 1, "Weber" },
                    { 487, 38, "Whitney_Williamson56@gmail.com", "Whitney", "DB", 1, "Williamson" },
                    { 488, 72, "Mable_Feest20@gmail.com", "Mable", "DB", 1, "Feest" },
                    { 489, 89, "Matthew95@gmail.com", "Matthew", "DB", 1, "Cassin" },
                    { 490, 77, "Natalie.Bauch@yahoo.com", "Natalie", "DB", 0, "Bauch" },
                    { 491, 26, "Freddie38@hotmail.com", "Freddie", "DB", 1, "Boyle" },
                    { 492, 76, "Alberto52@yahoo.com", "Alberto", "DB", 0, "Pacocha" },
                    { 493, 38, "Enrique_Welch@gmail.com", "Enrique", "DB", 0, "Welch" },
                    { 494, 71, "Beth32@gmail.com", "Beth", "DB", 0, "MacGyver" },
                    { 495, 34, "Lucas_Donnelly@hotmail.com", "Lucas", "DB", 0, "Donnelly" },
                    { 496, 33, "Fredrick62@gmail.com", "Fredrick", "DB", 1, "Lowe" },
                    { 497, 60, "Jordan.Schulist@yahoo.com", "Jordan", "DB", 1, "Schulist" },
                    { 498, 40, "Wayne_Glover@gmail.com", "Wayne", "DB", 1, "Glover" },
                    { 499, 27, "Alfredo40@yahoo.com", "Alfredo", "DB", 1, "Kassulke" },
                    { 500, 10, "Jan46@gmail.com", "Jan", "DB", 1, "Gutmann" },
                    { 501, 58, "Jennie.Mraz55@gmail.com", "Jennie", "DB", 0, "Mraz" },
                    { 502, 66, "Mark.Ankunding28@hotmail.com", "Mark", "DB", 1, "Ankunding" },
                    { 503, 40, "Lorene65@gmail.com", "Lorene", "DB", 1, "Morar" },
                    { 504, 54, "Ed_Hamill@gmail.com", "Ed", "DB", 1, "Hamill" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 505, 74, "Darryl_Zboncak@hotmail.com", "Darryl", "DB", 1, "Zboncak" },
                    { 506, 88, "Roger.Johnston@gmail.com", "Roger", "DB", 0, "Johnston" },
                    { 507, 65, "Diane_Hudson@yahoo.com", "Diane", "DB", 0, "Hudson" },
                    { 508, 84, "Perry_Farrell@gmail.com", "Perry", "DB", 1, "Farrell" },
                    { 509, 30, "Johanna_King58@gmail.com", "Johanna", "DB", 1, "King" },
                    { 510, 73, "Sharon81@gmail.com", "Sharon", "DB", 1, "Hills" },
                    { 511, 90, "Terri.Oberbrunner11@hotmail.com", "Terri", "DB", 1, "Oberbrunner" },
                    { 512, 60, "Kay.Yundt22@yahoo.com", "Kay", "DB", 0, "Yundt" },
                    { 513, 48, "Angel_Kessler@yahoo.com", "Angel", "DB", 1, "Kessler" },
                    { 514, 29, "Virgil.Bartell41@hotmail.com", "Virgil", "DB", 0, "Bartell" },
                    { 515, 68, "Candace.Kassulke17@hotmail.com", "Candace", "DB", 1, "Kassulke" },
                    { 516, 72, "Sadie.Lueilwitz@hotmail.com", "Sadie", "DB", 1, "Lueilwitz" },
                    { 517, 24, "Marshall8@hotmail.com", "Marshall", "DB", 1, "O'Keefe" },
                    { 518, 39, "Agnes11@yahoo.com", "Agnes", "DB", 1, "Hills" },
                    { 519, 17, "Gloria6@gmail.com", "Gloria", "DB", 1, "Gutmann" },
                    { 520, 13, "Marie64@yahoo.com", "Marie", "DB", 0, "Fay" },
                    { 521, 63, "Marcella_Kshlerin86@hotmail.com", "Marcella", "DB", 1, "Kshlerin" },
                    { 522, 70, "Jody.Bogisich@gmail.com", "Jody", "DB", 0, "Bogisich" },
                    { 523, 30, "Tommie_Hegmann@yahoo.com", "Tommie", "DB", 0, "Hegmann" },
                    { 524, 12, "Kurt48@gmail.com", "Kurt", "DB", 1, "Shields" },
                    { 525, 78, "Brandi.Johns99@yahoo.com", "Brandi", "DB", 0, "Johns" },
                    { 526, 21, "Lorena_Feil@yahoo.com", "Lorena", "DB", 1, "Feil" },
                    { 527, 52, "Darren.Denesik61@hotmail.com", "Darren", "DB", 0, "Denesik" },
                    { 528, 42, "Alberta_Corkery@hotmail.com", "Alberta", "DB", 0, "Corkery" },
                    { 529, 32, "Alyssa.Hirthe@yahoo.com", "Alyssa", "DB", 0, "Hirthe" },
                    { 530, 33, "Daniel3@yahoo.com", "Daniel", "DB", 1, "Zboncak" },
                    { 531, 24, "Jake9@hotmail.com", "Jake", "DB", 0, "Bergstrom" },
                    { 532, 45, "Glenn.West@gmail.com", "Glenn", "DB", 1, "West" },
                    { 533, 68, "Laverne_Bechtelar48@gmail.com", "Laverne", "DB", 0, "Bechtelar" },
                    { 534, 65, "Oliver23@hotmail.com", "Oliver", "DB", 1, "Medhurst" },
                    { 535, 31, "Marguerite29@yahoo.com", "Marguerite", "DB", 1, "Abbott" },
                    { 536, 27, "Latoya45@gmail.com", "Latoya", "DB", 1, "Dickinson" },
                    { 537, 58, "Terri_Grant39@gmail.com", "Terri", "DB", 1, "Grant" },
                    { 538, 36, "Kenneth.Veum90@hotmail.com", "Kenneth", "DB", 0, "Veum" },
                    { 539, 26, "Kerry_Abshire@gmail.com", "Kerry", "DB", 1, "Abshire" },
                    { 540, 58, "Lynn.Kshlerin63@gmail.com", "Lynn", "DB", 0, "Kshlerin" },
                    { 541, 16, "Samuel15@gmail.com", "Samuel", "DB", 1, "Price" },
                    { 542, 56, "Lynne21@hotmail.com", "Lynne", "DB", 0, "Bode" },
                    { 543, 31, "Robyn40@yahoo.com", "Robyn", "DB", 0, "Klocko" },
                    { 544, 22, "Ronald31@gmail.com", "Ronald", "DB", 0, "Kessler" },
                    { 545, 9, "Emmett.Ward81@hotmail.com", "Emmett", "DB", 0, "Ward" },
                    { 546, 81, "Kristi_Connelly@gmail.com", "Kristi", "DB", 1, "Connelly" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 547, 67, "Byron46@yahoo.com", "Byron", "DB", 1, "Rodriguez" },
                    { 548, 22, "Pauline_Ernser@yahoo.com", "Pauline", "DB", 1, "Ernser" },
                    { 549, 20, "Stacy63@hotmail.com", "Stacy", "DB", 0, "Stokes" },
                    { 550, 63, "Latoya_Frami9@gmail.com", "Latoya", "DB", 0, "Frami" },
                    { 551, 8, "Dennis40@hotmail.com", "Dennis", "DB", 1, "Ward" },
                    { 552, 89, "Gregg64@hotmail.com", "Gregg", "DB", 0, "Borer" },
                    { 553, 81, "Connie_Rath@hotmail.com", "Connie", "DB", 0, "Rath" },
                    { 554, 25, "Johnnie96@yahoo.com", "Johnnie", "DB", 1, "Bins" },
                    { 555, 66, "Dolores.Stamm@hotmail.com", "Dolores", "DB", 1, "Stamm" },
                    { 556, 26, "Ed51@hotmail.com", "Ed", "DB", 1, "Stanton" },
                    { 557, 41, "Geraldine_Crooks73@hotmail.com", "Geraldine", "DB", 1, "Crooks" },
                    { 558, 30, "Tanya58@yahoo.com", "Tanya", "DB", 0, "Koch" },
                    { 559, 90, "Beverly55@yahoo.com", "Beverly", "DB", 0, "Smith" },
                    { 560, 69, "Julian.Steuber@gmail.com", "Julian", "DB", 1, "Steuber" },
                    { 561, 42, "Rosemary.Thiel87@gmail.com", "Rosemary", "DB", 1, "Thiel" },
                    { 562, 61, "Edmund.Kemmer@hotmail.com", "Edmund", "DB", 0, "Kemmer" },
                    { 563, 12, "Estelle81@hotmail.com", "Estelle", "DB", 1, "Krajcik" },
                    { 564, 63, "Carla66@gmail.com", "Carla", "DB", 1, "Lueilwitz" },
                    { 565, 18, "Aubrey.Beier@hotmail.com", "Aubrey", "DB", 1, "Beier" },
                    { 566, 22, "Bryan_Tromp@hotmail.com", "Bryan", "DB", 0, "Tromp" },
                    { 567, 74, "Nicole.Medhurst@gmail.com", "Nicole", "DB", 0, "Medhurst" },
                    { 568, 9, "Marjorie89@gmail.com", "Marjorie", "DB", 1, "Murazik" },
                    { 569, 68, "Santiago.Bosco@gmail.com", "Santiago", "DB", 1, "Bosco" },
                    { 570, 50, "Shelia_Wilkinson@gmail.com", "Shelia", "DB", 1, "Wilkinson" },
                    { 571, 13, "Kari_Franecki@hotmail.com", "Kari", "DB", 0, "Franecki" },
                    { 572, 47, "Crystal_Haley96@gmail.com", "Crystal", "DB", 0, "Haley" },
                    { 573, 19, "Celia_Cummings@yahoo.com", "Celia", "DB", 1, "Cummings" },
                    { 574, 33, "Alma_Oberbrunner@yahoo.com", "Alma", "DB", 0, "Oberbrunner" },
                    { 575, 84, "Jo.Daugherty31@hotmail.com", "Jo", "DB", 1, "Daugherty" },
                    { 576, 11, "Ricardo.Schultz59@gmail.com", "Ricardo", "DB", 0, "Schultz" },
                    { 577, 81, "Priscilla57@yahoo.com", "Priscilla", "DB", 1, "Littel" },
                    { 578, 9, "Seth23@gmail.com", "Seth", "DB", 1, "O'Keefe" },
                    { 579, 62, "Vanessa_Herzog39@hotmail.com", "Vanessa", "DB", 0, "Herzog" },
                    { 580, 35, "Verna.Wintheiser@gmail.com", "Verna", "DB", 1, "Wintheiser" },
                    { 581, 49, "Rickey_Howell@hotmail.com", "Rickey", "DB", 1, "Howell" },
                    { 582, 65, "Heather_Price25@gmail.com", "Heather", "DB", 1, "Price" },
                    { 583, 86, "Theodore_Hodkiewicz@yahoo.com", "Theodore", "DB", 1, "Hodkiewicz" },
                    { 584, 45, "Roman.Torp10@gmail.com", "Roman", "DB", 1, "Torp" },
                    { 585, 38, "Raul.Bernhard@gmail.com", "Raul", "DB", 0, "Bernhard" },
                    { 586, 45, "Madeline.Smith78@gmail.com", "Madeline", "DB", 1, "Smith" },
                    { 587, 54, "Lindsey_Witting47@yahoo.com", "Lindsey", "DB", 0, "Witting" },
                    { 588, 84, "Virgil.Ritchie11@hotmail.com", "Virgil", "DB", 1, "Ritchie" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 589, 40, "Caroline_Conn56@hotmail.com", "Caroline", "DB", 0, "Conn" },
                    { 590, 82, "Stuart49@hotmail.com", "Stuart", "DB", 1, "Rolfson" },
                    { 591, 67, "Jeannie.Torp41@gmail.com", "Jeannie", "DB", 1, "Torp" },
                    { 592, 69, "Bernadette58@yahoo.com", "Bernadette", "DB", 0, "Jenkins" },
                    { 593, 80, "Doug_Larson@gmail.com", "Doug", "DB", 1, "Larson" },
                    { 594, 36, "Michelle37@gmail.com", "Michelle", "DB", 1, "Swaniawski" },
                    { 595, 33, "Maurice_Koepp18@gmail.com", "Maurice", "DB", 1, "Koepp" },
                    { 596, 83, "Doris.OConnell@yahoo.com", "Doris", "DB", 0, "O'Connell" },
                    { 597, 58, "Horace_Paucek78@gmail.com", "Horace", "DB", 1, "Paucek" },
                    { 598, 45, "Daryl_Kiehn@gmail.com", "Daryl", "DB", 0, "Kiehn" },
                    { 599, 56, "Kyle.Conroy23@yahoo.com", "Kyle", "DB", 1, "Conroy" },
                    { 600, 56, "Elizabeth_Haag@hotmail.com", "Elizabeth", "DB", 1, "Haag" },
                    { 601, 64, "Randolph.Schuppe@hotmail.com", "Randolph", "DB", 1, "Schuppe" },
                    { 602, 46, "Earl.Morissette10@hotmail.com", "Earl", "DB", 0, "Morissette" },
                    { 603, 12, "Courtney_Treutel@hotmail.com", "Courtney", "DB", 0, "Treutel" },
                    { 604, 13, "Carl95@yahoo.com", "Carl", "DB", 0, "Smitham" },
                    { 605, 34, "Jason1@hotmail.com", "Jason", "DB", 1, "Kohler" },
                    { 606, 48, "Mercedes96@gmail.com", "Mercedes", "DB", 1, "Hamill" },
                    { 607, 56, "Trevor_Buckridge@yahoo.com", "Trevor", "DB", 1, "Buckridge" },
                    { 608, 24, "Blanca.Trantow3@hotmail.com", "Blanca", "DB", 0, "Trantow" },
                    { 609, 76, "Jeremiah_Satterfield88@gmail.com", "Jeremiah", "DB", 1, "Satterfield" },
                    { 610, 84, "Zachary_Fahey@gmail.com", "Zachary", "DB", 1, "Fahey" },
                    { 611, 56, "Armando.Swift89@hotmail.com", "Armando", "DB", 1, "Swift" },
                    { 612, 10, "Merle_Ondricka@hotmail.com", "Merle", "DB", 1, "Ondricka" },
                    { 613, 29, "Alicia_Smitham44@hotmail.com", "Alicia", "DB", 0, "Smitham" },
                    { 614, 60, "Rochelle19@gmail.com", "Rochelle", "DB", 0, "Kirlin" },
                    { 615, 52, "Ramona_Goyette@hotmail.com", "Ramona", "DB", 1, "Goyette" },
                    { 616, 32, "Rick_Roberts96@hotmail.com", "Rick", "DB", 1, "Roberts" },
                    { 617, 26, "Josh6@yahoo.com", "Josh", "DB", 0, "Berge" },
                    { 618, 14, "Theresa95@hotmail.com", "Theresa", "DB", 0, "Pagac" },
                    { 619, 18, "Geneva_Gorczany@yahoo.com", "Geneva", "DB", 0, "Gorczany" },
                    { 620, 81, "Ryan_Hayes@hotmail.com", "Ryan", "DB", 0, "Hayes" },
                    { 621, 51, "Kelly21@gmail.com", "Kelly", "DB", 0, "Nienow" },
                    { 622, 21, "Carolyn70@hotmail.com", "Carolyn", "DB", 1, "West" },
                    { 623, 90, "Jasmine_Hackett78@gmail.com", "Jasmine", "DB", 0, "Hackett" },
                    { 624, 10, "Melanie_McLaughlin56@gmail.com", "Melanie", "DB", 1, "McLaughlin" },
                    { 625, 15, "Sheri46@yahoo.com", "Sheri", "DB", 1, "Farrell" },
                    { 626, 90, "Wendell6@gmail.com", "Wendell", "DB", 1, "Hickle" },
                    { 627, 86, "Heather_Stanton63@hotmail.com", "Heather", "DB", 0, "Stanton" },
                    { 628, 48, "Leigh.Leffler@gmail.com", "Leigh", "DB", 0, "Leffler" },
                    { 629, 67, "Nelson_Adams10@yahoo.com", "Nelson", "DB", 0, "Adams" },
                    { 630, 23, "Clay57@gmail.com", "Clay", "DB", 1, "Beer" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 631, 26, "Cristina.Gerlach3@yahoo.com", "Cristina", "DB", 0, "Gerlach" },
                    { 632, 87, "Rosa68@yahoo.com", "Rosa", "DB", 0, "Gaylord" },
                    { 633, 41, "Robin26@gmail.com", "Robin", "DB", 0, "Haag" },
                    { 634, 34, "Justin_Kirlin50@hotmail.com", "Justin", "DB", 0, "Kirlin" },
                    { 635, 8, "Jeannie_Bartoletti@gmail.com", "Jeannie", "DB", 0, "Bartoletti" },
                    { 636, 25, "Ebony_Ledner26@yahoo.com", "Ebony", "DB", 0, "Ledner" },
                    { 637, 13, "Keith51@hotmail.com", "Keith", "DB", 1, "Hane" },
                    { 638, 66, "Keith_Wehner55@gmail.com", "Keith", "DB", 1, "Wehner" },
                    { 639, 34, "Kari.Parker@gmail.com", "Kari", "DB", 0, "Parker" },
                    { 640, 49, "Antonia_Goyette94@gmail.com", "Antonia", "DB", 1, "Goyette" },
                    { 641, 29, "Roosevelt.McLaughlin34@hotmail.com", "Roosevelt", "DB", 1, "McLaughlin" },
                    { 642, 15, "Rose.Moore68@yahoo.com", "Rose", "DB", 0, "Moore" },
                    { 643, 50, "Van.DAmore9@yahoo.com", "Van", "DB", 1, "D'Amore" },
                    { 644, 90, "Tabitha15@hotmail.com", "Tabitha", "DB", 0, "Reinger" },
                    { 645, 84, "Rosalie.Hayes@hotmail.com", "Rosalie", "DB", 0, "Hayes" },
                    { 646, 51, "Guy.Klein79@gmail.com", "Guy", "DB", 0, "Klein" },
                    { 647, 77, "Abel.Will@yahoo.com", "Abel", "DB", 1, "Will" },
                    { 648, 42, "Camille_Walter8@yahoo.com", "Camille", "DB", 1, "Walter" },
                    { 649, 30, "Cecelia46@gmail.com", "Cecelia", "DB", 1, "Green" },
                    { 650, 83, "Sylvia79@gmail.com", "Sylvia", "DB", 0, "Fisher" },
                    { 651, 34, "Manuel45@hotmail.com", "Manuel", "DB", 0, "Nitzsche" },
                    { 652, 78, "Annette46@gmail.com", "Annette", "DB", 0, "Quigley" },
                    { 653, 65, "Jeannie_Hartmann@hotmail.com", "Jeannie", "DB", 1, "Hartmann" },
                    { 654, 22, "Debra_Stracke16@yahoo.com", "Debra", "DB", 0, "Stracke" },
                    { 655, 18, "Renee_Mante7@yahoo.com", "Renee", "DB", 0, "Mante" },
                    { 656, 27, "John.Herzog@yahoo.com", "John", "DB", 0, "Herzog" },
                    { 657, 18, "Leland5@gmail.com", "Leland", "DB", 1, "Ziemann" },
                    { 658, 55, "Tanya_Hermiston7@yahoo.com", "Tanya", "DB", 1, "Hermiston" },
                    { 659, 76, "Perry6@hotmail.com", "Perry", "DB", 0, "Nikolaus" },
                    { 660, 38, "Violet.Marks12@gmail.com", "Violet", "DB", 1, "Marks" },
                    { 661, 78, "Kayla98@gmail.com", "Kayla", "DB", 1, "Moen" },
                    { 662, 8, "Susan.Reichel@hotmail.com", "Susan", "DB", 0, "Reichel" },
                    { 663, 15, "Faith.Tremblay@yahoo.com", "Faith", "DB", 1, "Tremblay" },
                    { 664, 16, "Alice5@hotmail.com", "Alice", "DB", 1, "Wolf" },
                    { 665, 40, "Abraham_Monahan@gmail.com", "Abraham", "DB", 0, "Monahan" },
                    { 666, 77, "Robin95@yahoo.com", "Robin", "DB", 0, "Moore" },
                    { 667, 17, "Eduardo94@gmail.com", "Eduardo", "DB", 1, "Will" },
                    { 668, 77, "Dominic_Osinski78@hotmail.com", "Dominic", "DB", 1, "Osinski" },
                    { 669, 84, "Shaun67@gmail.com", "Shaun", "DB", 1, "Leffler" },
                    { 670, 39, "Roosevelt.Champlin84@gmail.com", "Roosevelt", "DB", 0, "Champlin" },
                    { 671, 59, "Lucy70@hotmail.com", "Lucy", "DB", 0, "Stiedemann" },
                    { 672, 73, "Sonia92@yahoo.com", "Sonia", "DB", 0, "Hackett" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 673, 16, "Tracy_Jacobson@yahoo.com", "Tracy", "DB", 1, "Jacobson" },
                    { 674, 72, "Silvia_Senger96@hotmail.com", "Silvia", "DB", 0, "Senger" },
                    { 675, 27, "Bernice.Aufderhar33@yahoo.com", "Bernice", "DB", 0, "Aufderhar" },
                    { 676, 12, "Francis92@hotmail.com", "Francis", "DB", 1, "Pouros" },
                    { 677, 56, "Virgil2@gmail.com", "Virgil", "DB", 1, "Murray" },
                    { 678, 85, "Jacqueline.Schuppe47@hotmail.com", "Jacqueline", "DB", 0, "Schuppe" },
                    { 679, 8, "Kari.Durgan3@gmail.com", "Kari", "DB", 0, "Durgan" },
                    { 680, 53, "Geneva_Hermiston7@yahoo.com", "Geneva", "DB", 0, "Hermiston" },
                    { 681, 64, "Hubert.Watsica76@gmail.com", "Hubert", "DB", 1, "Watsica" },
                    { 682, 19, "Alan_Simonis@yahoo.com", "Alan", "DB", 1, "Simonis" },
                    { 683, 87, "Terrence.Mayert@gmail.com", "Terrence", "DB", 1, "Mayert" },
                    { 684, 69, "Colleen_Stamm@yahoo.com", "Colleen", "DB", 1, "Stamm" },
                    { 685, 65, "Craig.Hirthe@hotmail.com", "Craig", "DB", 0, "Hirthe" },
                    { 686, 67, "Lynne.Moore@yahoo.com", "Lynne", "DB", 0, "Moore" },
                    { 687, 40, "Pamela.McKenzie19@yahoo.com", "Pamela", "DB", 1, "McKenzie" },
                    { 688, 81, "Justin.Kuphal@gmail.com", "Justin", "DB", 0, "Kuphal" },
                    { 689, 8, "Stacey_Rohan43@gmail.com", "Stacey", "DB", 1, "Rohan" },
                    { 690, 77, "Vernon.Mills@gmail.com", "Vernon", "DB", 1, "Mills" },
                    { 691, 57, "Victor_Mitchell68@yahoo.com", "Victor", "DB", 0, "Mitchell" },
                    { 692, 61, "Jack.Rosenbaum@gmail.com", "Jack", "DB", 1, "Rosenbaum" },
                    { 693, 38, "George0@hotmail.com", "George", "DB", 1, "Schuppe" },
                    { 694, 54, "Neil.Franecki@yahoo.com", "Neil", "DB", 1, "Franecki" },
                    { 695, 26, "Wendy.Koelpin47@yahoo.com", "Wendy", "DB", 0, "Koelpin" },
                    { 696, 35, "Lora.Abbott84@yahoo.com", "Lora", "DB", 0, "Abbott" },
                    { 697, 46, "Gary_Kessler55@gmail.com", "Gary", "DB", 1, "Kessler" },
                    { 698, 66, "Mercedes_Schaden22@yahoo.com", "Mercedes", "DB", 1, "Schaden" },
                    { 699, 69, "Kathryn.Kunze20@yahoo.com", "Kathryn", "DB", 0, "Kunze" },
                    { 700, 18, "Robert.Hartmann@gmail.com", "Robert", "DB", 1, "Hartmann" },
                    { 701, 52, "Rufus.Shanahan@yahoo.com", "Rufus", "DB", 0, "Shanahan" },
                    { 702, 35, "Vivian_Brakus24@yahoo.com", "Vivian", "DB", 1, "Brakus" },
                    { 703, 83, "Whitney.Romaguera@yahoo.com", "Whitney", "DB", 0, "Romaguera" },
                    { 704, 8, "Christine_Hermann@yahoo.com", "Christine", "DB", 0, "Hermann" },
                    { 705, 72, "Samuel_Marvin@hotmail.com", "Samuel", "DB", 1, "Marvin" },
                    { 706, 88, "Amelia68@hotmail.com", "Amelia", "DB", 0, "Bernhard" },
                    { 707, 15, "Elaine54@hotmail.com", "Elaine", "DB", 0, "Hoppe" },
                    { 708, 77, "Ana_Simonis67@hotmail.com", "Ana", "DB", 0, "Simonis" },
                    { 709, 18, "Lorraine44@gmail.com", "Lorraine", "DB", 0, "Zulauf" },
                    { 710, 90, "Deborah.Kshlerin@hotmail.com", "Deborah", "DB", 0, "Kshlerin" },
                    { 711, 54, "Rickey_White98@gmail.com", "Rickey", "DB", 0, "White" },
                    { 712, 53, "Lynne.Hermann@gmail.com", "Lynne", "DB", 0, "Hermann" },
                    { 713, 80, "Johnnie_Parisian74@hotmail.com", "Johnnie", "DB", 0, "Parisian" },
                    { 714, 21, "Nora91@yahoo.com", "Nora", "DB", 0, "West" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 715, 70, "Theodore2@gmail.com", "Theodore", "DB", 1, "Schimmel" },
                    { 716, 87, "Marion.Hartmann@yahoo.com", "Marion", "DB", 0, "Hartmann" },
                    { 717, 46, "Susan_Kuhic@yahoo.com", "Susan", "DB", 1, "Kuhic" },
                    { 718, 9, "Anita.Treutel@yahoo.com", "Anita", "DB", 1, "Treutel" },
                    { 719, 42, "Dallas_Schoen@hotmail.com", "Dallas", "DB", 1, "Schoen" },
                    { 720, 75, "Forrest.Reilly@hotmail.com", "Forrest", "DB", 0, "Reilly" },
                    { 721, 83, "Dixie55@gmail.com", "Dixie", "DB", 1, "Bode" },
                    { 722, 46, "Hannah_Wyman98@yahoo.com", "Hannah", "DB", 1, "Wyman" },
                    { 723, 45, "Inez.Hyatt1@gmail.com", "Inez", "DB", 1, "Hyatt" },
                    { 724, 85, "Meghan36@yahoo.com", "Meghan", "DB", 0, "Turner" },
                    { 725, 33, "Elmer.Purdy@yahoo.com", "Elmer", "DB", 1, "Purdy" },
                    { 726, 25, "Carla.Turcotte48@gmail.com", "Carla", "DB", 0, "Turcotte" },
                    { 727, 38, "Courtney_Shields@yahoo.com", "Courtney", "DB", 0, "Shields" },
                    { 728, 22, "Alberta.Streich@yahoo.com", "Alberta", "DB", 0, "Streich" },
                    { 729, 69, "Abel_Daugherty@hotmail.com", "Abel", "DB", 1, "Daugherty" },
                    { 730, 25, "Mack80@hotmail.com", "Mack", "DB", 1, "Roob" },
                    { 731, 62, "Raymond48@gmail.com", "Raymond", "DB", 0, "Mosciski" },
                    { 732, 60, "Noah95@gmail.com", "Noah", "DB", 0, "McLaughlin" },
                    { 733, 18, "Bessie.Raynor@hotmail.com", "Bessie", "DB", 1, "Raynor" },
                    { 734, 47, "Darnell.Koss@yahoo.com", "Darnell", "DB", 0, "Koss" },
                    { 735, 70, "Earnest_Bradtke89@hotmail.com", "Earnest", "DB", 1, "Bradtke" },
                    { 736, 71, "Gregory79@gmail.com", "Gregory", "DB", 0, "Lebsack" },
                    { 737, 19, "May.Lesch77@yahoo.com", "May", "DB", 0, "Lesch" },
                    { 738, 44, "Ashley28@hotmail.com", "Ashley", "DB", 1, "Quitzon" },
                    { 739, 61, "Elmer.Stanton17@gmail.com", "Elmer", "DB", 1, "Stanton" },
                    { 740, 64, "Lorenzo17@hotmail.com", "Lorenzo", "DB", 0, "Nikolaus" },
                    { 741, 83, "Alejandro54@gmail.com", "Alejandro", "DB", 1, "West" },
                    { 742, 60, "Monique43@yahoo.com", "Monique", "DB", 1, "Greenfelder" },
                    { 743, 45, "Patrick.Ratke87@gmail.com", "Patrick", "DB", 0, "Ratke" },
                    { 744, 75, "Sheri.Mueller81@yahoo.com", "Sheri", "DB", 1, "Mueller" },
                    { 745, 13, "Jessie_Hauck49@gmail.com", "Jessie", "DB", 0, "Hauck" },
                    { 746, 69, "Oliver.Armstrong@yahoo.com", "Oliver", "DB", 1, "Armstrong" },
                    { 747, 88, "Doug13@hotmail.com", "Doug", "DB", 1, "Schultz" },
                    { 748, 46, "Melanie_Davis39@yahoo.com", "Melanie", "DB", 0, "Davis" },
                    { 749, 84, "Howard65@yahoo.com", "Howard", "DB", 1, "Lang" },
                    { 750, 18, "Luther.Vandervort@hotmail.com", "Luther", "DB", 0, "Vandervort" },
                    { 751, 83, "Mitchell70@gmail.com", "Mitchell", "DB", 1, "Hammes" },
                    { 752, 64, "Shaun.Hyatt95@yahoo.com", "Shaun", "DB", 1, "Hyatt" },
                    { 753, 11, "Jerome.Schroeder@hotmail.com", "Jerome", "DB", 1, "Schroeder" },
                    { 754, 47, "Micheal_Harber89@yahoo.com", "Micheal", "DB", 1, "Harber" },
                    { 755, 39, "Josephine.Franecki78@hotmail.com", "Josephine", "DB", 0, "Franecki" },
                    { 756, 12, "Blanca_Sauer64@hotmail.com", "Blanca", "DB", 1, "Sauer" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 757, 58, "Javier.Barrows32@gmail.com", "Javier", "DB", 1, "Barrows" },
                    { 758, 52, "Phyllis_Grant71@hotmail.com", "Phyllis", "DB", 0, "Grant" },
                    { 759, 57, "Rose20@gmail.com", "Rose", "DB", 0, "Berge" },
                    { 760, 11, "Robin87@gmail.com", "Robin", "DB", 1, "Zulauf" },
                    { 761, 58, "Beulah.Morar@hotmail.com", "Beulah", "DB", 1, "Morar" },
                    { 762, 40, "Esther43@yahoo.com", "Esther", "DB", 0, "Treutel" },
                    { 763, 23, "Winston.Yost@yahoo.com", "Winston", "DB", 1, "Yost" },
                    { 764, 65, "Kristopher.Cremin@yahoo.com", "Kristopher", "DB", 0, "Cremin" },
                    { 765, 56, "Elizabeth_Kling@hotmail.com", "Elizabeth", "DB", 1, "Kling" },
                    { 766, 85, "Emily.Beahan@gmail.com", "Emily", "DB", 0, "Beahan" },
                    { 767, 24, "Wilbert.Yost33@hotmail.com", "Wilbert", "DB", 1, "Yost" },
                    { 768, 57, "Daryl.Lakin@hotmail.com", "Daryl", "DB", 1, "Lakin" },
                    { 769, 78, "Joseph_Pagac@hotmail.com", "Joseph", "DB", 1, "Pagac" },
                    { 770, 10, "Dianne_Runolfsson@gmail.com", "Dianne", "DB", 1, "Runolfsson" },
                    { 771, 50, "Ernest_Denesik@gmail.com", "Ernest", "DB", 0, "Denesik" },
                    { 772, 82, "Toni.Mayert@gmail.com", "Toni", "DB", 1, "Mayert" },
                    { 773, 52, "Gertrude28@yahoo.com", "Gertrude", "DB", 1, "Prosacco" },
                    { 774, 54, "Jacqueline.Cassin@yahoo.com", "Jacqueline", "DB", 1, "Cassin" },
                    { 775, 48, "Dustin94@gmail.com", "Dustin", "DB", 0, "Hahn" },
                    { 776, 51, "Meredith90@gmail.com", "Meredith", "DB", 0, "Jacobi" },
                    { 777, 57, "Carrie_Weimann21@yahoo.com", "Carrie", "DB", 0, "Weimann" },
                    { 778, 48, "Dave4@gmail.com", "Dave", "DB", 1, "Borer" },
                    { 779, 32, "Sally15@gmail.com", "Sally", "DB", 0, "Rau" },
                    { 780, 43, "Dustin95@yahoo.com", "Dustin", "DB", 0, "Price" },
                    { 781, 50, "Karla.McLaughlin69@gmail.com", "Karla", "DB", 1, "McLaughlin" },
                    { 782, 47, "Laurence_Considine@hotmail.com", "Laurence", "DB", 1, "Considine" },
                    { 783, 49, "Joann.Cummerata@hotmail.com", "Joann", "DB", 1, "Cummerata" },
                    { 784, 15, "Pearl_Lubowitz@yahoo.com", "Pearl", "DB", 1, "Lubowitz" },
                    { 785, 59, "Woodrow_Hills15@yahoo.com", "Woodrow", "DB", 0, "Hills" },
                    { 786, 44, "Debbie.Durgan@yahoo.com", "Debbie", "DB", 1, "Durgan" },
                    { 787, 25, "Ralph.Muller59@gmail.com", "Ralph", "DB", 0, "Muller" },
                    { 788, 59, "Cory.Wyman@yahoo.com", "Cory", "DB", 1, "Wyman" },
                    { 789, 59, "Jeanette.Rolfson34@yahoo.com", "Jeanette", "DB", 0, "Rolfson" },
                    { 790, 30, "Susie_Barton@yahoo.com", "Susie", "DB", 0, "Barton" },
                    { 791, 69, "Ebony61@yahoo.com", "Ebony", "DB", 1, "Hermann" },
                    { 792, 22, "April.Stanton@yahoo.com", "April", "DB", 1, "Stanton" },
                    { 793, 24, "Shannon41@yahoo.com", "Shannon", "DB", 1, "Yost" },
                    { 794, 65, "Lorena_Collins@yahoo.com", "Lorena", "DB", 1, "Collins" },
                    { 795, 44, "Teresa1@gmail.com", "Teresa", "DB", 1, "Kihn" },
                    { 796, 45, "Virginia66@hotmail.com", "Virginia", "DB", 0, "Schumm" },
                    { 797, 10, "Manuel.Marks@yahoo.com", "Manuel", "DB", 1, "Marks" },
                    { 798, 57, "Santiago.Hintz35@yahoo.com", "Santiago", "DB", 1, "Hintz" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 799, 59, "Katie_Rath@yahoo.com", "Katie", "DB", 0, "Rath" },
                    { 800, 12, "Katie96@yahoo.com", "Katie", "DB", 1, "Haley" },
                    { 801, 14, "Lorene.Torphy@hotmail.com", "Lorene", "DB", 0, "Torphy" },
                    { 802, 52, "Ronnie84@gmail.com", "Ronnie", "DB", 0, "Walker" },
                    { 803, 62, "Frederick_McLaughlin81@hotmail.com", "Frederick", "DB", 0, "McLaughlin" },
                    { 804, 56, "Jorge.Kihn@gmail.com", "Jorge", "DB", 0, "Kihn" },
                    { 805, 21, "Erica_Hauck@hotmail.com", "Erica", "DB", 0, "Hauck" },
                    { 806, 79, "Sara45@yahoo.com", "Sara", "DB", 1, "Stiedemann" },
                    { 807, 62, "Cody_Hoeger83@gmail.com", "Cody", "DB", 1, "Hoeger" },
                    { 808, 11, "Alice_Powlowski63@yahoo.com", "Alice", "DB", 1, "Powlowski" },
                    { 809, 79, "Sam_Sanford@gmail.com", "Sam", "DB", 1, "Sanford" },
                    { 810, 10, "Sonia.Zieme16@hotmail.com", "Sonia", "DB", 1, "Zieme" },
                    { 811, 58, "Eloise.Lebsack@hotmail.com", "Eloise", "DB", 1, "Lebsack" },
                    { 812, 17, "Orlando2@gmail.com", "Orlando", "DB", 1, "Leannon" },
                    { 813, 57, "Lee61@gmail.com", "Lee", "DB", 0, "Willms" },
                    { 814, 89, "Edna.Cremin45@hotmail.com", "Edna", "DB", 0, "Cremin" },
                    { 815, 75, "Laurence.Beier23@hotmail.com", "Laurence", "DB", 0, "Beier" },
                    { 816, 68, "Bob85@yahoo.com", "Bob", "DB", 0, "Terry" },
                    { 817, 28, "Margarita6@yahoo.com", "Margarita", "DB", 0, "Paucek" },
                    { 818, 31, "Armando72@gmail.com", "Armando", "DB", 0, "Schinner" },
                    { 819, 14, "Sheldon_Sporer94@yahoo.com", "Sheldon", "DB", 0, "Sporer" },
                    { 820, 13, "Paul70@hotmail.com", "Paul", "DB", 1, "Senger" },
                    { 821, 54, "Lindsey.Schamberger@yahoo.com", "Lindsey", "DB", 1, "Schamberger" },
                    { 822, 11, "Phil33@gmail.com", "Phil", "DB", 0, "Wilderman" },
                    { 823, 64, "Lynda_McLaughlin@gmail.com", "Lynda", "DB", 0, "McLaughlin" },
                    { 824, 16, "Laurence_OConner22@hotmail.com", "Laurence", "DB", 0, "O'Conner" },
                    { 825, 85, "Alyssa60@hotmail.com", "Alyssa", "DB", 1, "Stehr" },
                    { 826, 71, "Saul64@yahoo.com", "Saul", "DB", 1, "Halvorson" },
                    { 827, 40, "Marilyn_Blanda11@gmail.com", "Marilyn", "DB", 1, "Blanda" },
                    { 828, 90, "Charles.Hackett11@yahoo.com", "Charles", "DB", 0, "Hackett" },
                    { 829, 67, "Wanda.Brakus@hotmail.com", "Wanda", "DB", 0, "Brakus" },
                    { 830, 71, "Traci_Hoppe@hotmail.com", "Traci", "DB", 1, "Hoppe" },
                    { 831, 16, "Bryant.OKon@gmail.com", "Bryant", "DB", 1, "O'Kon" },
                    { 832, 22, "Lola.Hand@hotmail.com", "Lola", "DB", 0, "Hand" },
                    { 833, 77, "Leah_Carter63@hotmail.com", "Leah", "DB", 0, "Carter" },
                    { 834, 35, "Hugh.Rath@hotmail.com", "Hugh", "DB", 0, "Rath" },
                    { 835, 70, "Abraham52@hotmail.com", "Abraham", "DB", 1, "Parker" },
                    { 836, 89, "Luz.Fadel6@gmail.com", "Luz", "DB", 0, "Fadel" },
                    { 837, 26, "Tina_Langosh45@hotmail.com", "Tina", "DB", 1, "Langosh" },
                    { 838, 26, "Jimmy.Kuhlman34@yahoo.com", "Jimmy", "DB", 0, "Kuhlman" },
                    { 839, 56, "Kellie_Bahringer@gmail.com", "Kellie", "DB", 0, "Bahringer" },
                    { 840, 37, "Guadalupe.Wisozk48@hotmail.com", "Guadalupe", "DB", 1, "Wisozk" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 841, 17, "Roosevelt59@gmail.com", "Roosevelt", "DB", 0, "Feest" },
                    { 842, 77, "Sylvester.Schinner@gmail.com", "Sylvester", "DB", 0, "Schinner" },
                    { 843, 60, "Kerry_Marquardt@yahoo.com", "Kerry", "DB", 0, "Marquardt" },
                    { 844, 71, "Eula_Grady61@hotmail.com", "Eula", "DB", 0, "Grady" },
                    { 845, 58, "Clint_Johns@hotmail.com", "Clint", "DB", 0, "Johns" },
                    { 846, 81, "Cesar8@yahoo.com", "Cesar", "DB", 1, "Little" },
                    { 847, 90, "Daryl21@gmail.com", "Daryl", "DB", 0, "Parisian" },
                    { 848, 48, "Guillermo20@yahoo.com", "Guillermo", "DB", 0, "Lindgren" },
                    { 849, 24, "Sue44@yahoo.com", "Sue", "DB", 0, "Lindgren" },
                    { 850, 48, "Alfred.Balistreri@gmail.com", "Alfred", "DB", 1, "Balistreri" },
                    { 851, 17, "Lloyd70@hotmail.com", "Lloyd", "DB", 1, "Halvorson" },
                    { 852, 27, "Raul88@hotmail.com", "Raul", "DB", 0, "Schaden" },
                    { 853, 45, "Naomi12@gmail.com", "Naomi", "DB", 1, "Cole" },
                    { 854, 38, "Bruce.Witting35@hotmail.com", "Bruce", "DB", 0, "Witting" },
                    { 855, 35, "Aubrey99@gmail.com", "Aubrey", "DB", 0, "Koss" },
                    { 856, 17, "Eileen38@gmail.com", "Eileen", "DB", 0, "Leffler" },
                    { 857, 55, "Randall_Murazik12@gmail.com", "Randall", "DB", 1, "Murazik" },
                    { 858, 50, "Lora.Schneider@gmail.com", "Lora", "DB", 1, "Schneider" },
                    { 859, 42, "Simon.Smitham@yahoo.com", "Simon", "DB", 0, "Smitham" },
                    { 860, 90, "Glenda61@gmail.com", "Glenda", "DB", 1, "Stoltenberg" },
                    { 861, 63, "Carl84@yahoo.com", "Carl", "DB", 1, "Goldner" },
                    { 862, 32, "Desiree53@hotmail.com", "Desiree", "DB", 1, "Monahan" },
                    { 863, 65, "Clarence_Bergnaum@yahoo.com", "Clarence", "DB", 1, "Bergnaum" },
                    { 864, 15, "Kim88@gmail.com", "Kim", "DB", 1, "Medhurst" },
                    { 865, 63, "Stephen.Jacobi68@gmail.com", "Stephen", "DB", 1, "Jacobi" },
                    { 866, 84, "Stella63@hotmail.com", "Stella", "DB", 0, "Padberg" },
                    { 867, 88, "Emmett88@gmail.com", "Emmett", "DB", 1, "Olson" },
                    { 868, 35, "Toni_Emard@hotmail.com", "Toni", "DB", 1, "Emard" },
                    { 869, 21, "Luke.Langosh@yahoo.com", "Luke", "DB", 0, "Langosh" },
                    { 870, 76, "Evan_Legros@yahoo.com", "Evan", "DB", 0, "Legros" },
                    { 871, 87, "Herman.Gibson22@hotmail.com", "Herman", "DB", 1, "Gibson" },
                    { 872, 43, "Brett64@hotmail.com", "Brett", "DB", 0, "Ratke" },
                    { 873, 35, "Opal55@gmail.com", "Opal", "DB", 0, "Prohaska" },
                    { 874, 78, "Nadine_Windler93@gmail.com", "Nadine", "DB", 1, "Windler" },
                    { 875, 78, "Peter19@hotmail.com", "Peter", "DB", 0, "Kuhic" },
                    { 876, 33, "Tracy_Rutherford@gmail.com", "Tracy", "DB", 0, "Rutherford" },
                    { 877, 19, "Jacob.Bednar@yahoo.com", "Jacob", "DB", 0, "Bednar" },
                    { 878, 37, "Guillermo_Brakus@gmail.com", "Guillermo", "DB", 0, "Brakus" },
                    { 879, 66, "Nick.Jast@gmail.com", "Nick", "DB", 1, "Jast" },
                    { 880, 90, "Sandra79@hotmail.com", "Sandra", "DB", 0, "Reichel" },
                    { 881, 52, "Brandy.Powlowski@gmail.com", "Brandy", "DB", 0, "Powlowski" },
                    { 882, 33, "Amos.Baumbach@gmail.com", "Amos", "DB", 1, "Baumbach" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 883, 67, "Terry_Carter@hotmail.com", "Terry", "DB", 1, "Carter" },
                    { 884, 11, "Leland.Aufderhar17@gmail.com", "Leland", "DB", 0, "Aufderhar" },
                    { 885, 32, "Rosa82@yahoo.com", "Rosa", "DB", 0, "Ankunding" },
                    { 886, 73, "Juana66@hotmail.com", "Juana", "DB", 1, "Pagac" },
                    { 887, 72, "Lance.Stark36@yahoo.com", "Lance", "DB", 1, "Stark" },
                    { 888, 36, "Archie_Schumm@yahoo.com", "Archie", "DB", 0, "Schumm" },
                    { 889, 75, "Catherine_Schumm@gmail.com", "Catherine", "DB", 0, "Schumm" },
                    { 890, 66, "Andres87@hotmail.com", "Andres", "DB", 0, "Mohr" },
                    { 891, 23, "Derek38@yahoo.com", "Derek", "DB", 0, "Jaskolski" },
                    { 892, 63, "Danny.Jenkins42@gmail.com", "Danny", "DB", 1, "Jenkins" },
                    { 893, 21, "Bobby.Oberbrunner@yahoo.com", "Bobby", "DB", 1, "Oberbrunner" },
                    { 894, 28, "Delores.Beahan67@yahoo.com", "Delores", "DB", 1, "Beahan" },
                    { 895, 11, "Gail_Durgan50@yahoo.com", "Gail", "DB", 0, "Durgan" },
                    { 896, 37, "Tom_Reynolds10@gmail.com", "Tom", "DB", 1, "Reynolds" },
                    { 897, 63, "Amelia41@hotmail.com", "Amelia", "DB", 0, "Nikolaus" },
                    { 898, 42, "Oliver_Fritsch@hotmail.com", "Oliver", "DB", 1, "Fritsch" },
                    { 899, 42, "Aubrey_Tremblay@yahoo.com", "Aubrey", "DB", 0, "Tremblay" },
                    { 900, 67, "Cedric87@hotmail.com", "Cedric", "DB", 1, "Robel" },
                    { 901, 81, "Everett_Gibson@hotmail.com", "Everett", "DB", 1, "Gibson" },
                    { 902, 50, "Adam.Lebsack@yahoo.com", "Adam", "DB", 0, "Lebsack" },
                    { 903, 19, "Toni_Goldner@hotmail.com", "Toni", "DB", 1, "Goldner" },
                    { 904, 25, "Gabriel.King@yahoo.com", "Gabriel", "DB", 1, "King" },
                    { 905, 44, "Katie_Lakin86@gmail.com", "Katie", "DB", 0, "Lakin" },
                    { 906, 66, "Leo49@gmail.com", "Leo", "DB", 1, "O'Hara" },
                    { 907, 69, "Laurence77@yahoo.com", "Laurence", "DB", 1, "Bechtelar" },
                    { 908, 49, "Erika22@hotmail.com", "Erika", "DB", 1, "Shields" },
                    { 909, 14, "Randy_Littel@gmail.com", "Randy", "DB", 1, "Littel" },
                    { 910, 41, "Clara54@hotmail.com", "Clara", "DB", 0, "Rowe" },
                    { 911, 29, "Edmund_Harris96@yahoo.com", "Edmund", "DB", 1, "Harris" },
                    { 912, 70, "Kay.Gorczany@hotmail.com", "Kay", "DB", 1, "Gorczany" },
                    { 913, 47, "Abraham84@yahoo.com", "Abraham", "DB", 0, "Hartmann" },
                    { 914, 28, "Charlie_Hessel28@yahoo.com", "Charlie", "DB", 1, "Hessel" },
                    { 915, 63, "Lila99@gmail.com", "Lila", "DB", 1, "Bartoletti" },
                    { 916, 61, "Della6@gmail.com", "Della", "DB", 0, "Russel" },
                    { 917, 82, "Jenny_Runolfsson13@yahoo.com", "Jenny", "DB", 0, "Runolfsson" },
                    { 918, 31, "Bernadette18@gmail.com", "Bernadette", "DB", 1, "Watsica" },
                    { 919, 72, "Charlotte37@yahoo.com", "Charlotte", "DB", 1, "O'Kon" },
                    { 920, 75, "Erik92@yahoo.com", "Erik", "DB", 1, "Rath" },
                    { 921, 65, "Ruben.Cassin3@gmail.com", "Ruben", "DB", 1, "Cassin" },
                    { 922, 79, "Merle79@hotmail.com", "Merle", "DB", 1, "Smitham" },
                    { 923, 76, "Lillian_Buckridge@hotmail.com", "Lillian", "DB", 0, "Buckridge" },
                    { 924, 71, "Joshua_Reichel@yahoo.com", "Joshua", "DB", 1, "Reichel" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 925, 37, "Nadine.Hickle80@gmail.com", "Nadine", "DB", 1, "Hickle" },
                    { 926, 77, "Carlos.OHara59@hotmail.com", "Carlos", "DB", 0, "O'Hara" },
                    { 927, 88, "Dallas.Mann@yahoo.com", "Dallas", "DB", 0, "Mann" },
                    { 928, 38, "Victor_Barrows@yahoo.com", "Victor", "DB", 0, "Barrows" },
                    { 929, 61, "Josh_Morissette1@hotmail.com", "Josh", "DB", 0, "Morissette" },
                    { 930, 45, "Jackie.Ebert@yahoo.com", "Jackie", "DB", 0, "Ebert" },
                    { 931, 70, "Vicki.Hand70@yahoo.com", "Vicki", "DB", 0, "Hand" },
                    { 932, 71, "Adrian_Hilll@hotmail.com", "Adrian", "DB", 0, "Hilll" },
                    { 933, 60, "Nicholas47@hotmail.com", "Nicholas", "DB", 1, "Padberg" },
                    { 934, 14, "Alton73@hotmail.com", "Alton", "DB", 0, "Kub" },
                    { 935, 36, "Luther.Turcotte33@gmail.com", "Luther", "DB", 1, "Turcotte" },
                    { 936, 62, "Dewey52@gmail.com", "Dewey", "DB", 1, "Volkman" },
                    { 937, 53, "Lorena_Aufderhar@yahoo.com", "Lorena", "DB", 0, "Aufderhar" },
                    { 938, 87, "Jill.Ernser@gmail.com", "Jill", "DB", 0, "Ernser" },
                    { 939, 16, "Marlene_Windler37@hotmail.com", "Marlene", "DB", 0, "Windler" },
                    { 940, 67, "Gwen86@gmail.com", "Gwen", "DB", 1, "Reinger" },
                    { 941, 43, "Lorraine93@yahoo.com", "Lorraine", "DB", 1, "Ruecker" },
                    { 942, 57, "Tricia_Spinka27@yahoo.com", "Tricia", "DB", 0, "Spinka" },
                    { 943, 84, "Ira_Cummerata@yahoo.com", "Ira", "DB", 0, "Cummerata" },
                    { 944, 73, "Milton_Crooks@hotmail.com", "Milton", "DB", 1, "Crooks" },
                    { 945, 76, "Susie.Emmerich27@gmail.com", "Susie", "DB", 1, "Emmerich" },
                    { 946, 67, "Darren84@gmail.com", "Darren", "DB", 0, "Abbott" },
                    { 947, 38, "Courtney.Ankunding@hotmail.com", "Courtney", "DB", 0, "Ankunding" },
                    { 948, 24, "Rickey52@yahoo.com", "Rickey", "DB", 0, "Koss" },
                    { 949, 25, "Sue69@yahoo.com", "Sue", "DB", 0, "Zieme" },
                    { 950, 40, "Daisy99@yahoo.com", "Daisy", "DB", 0, "Bartell" },
                    { 951, 67, "Felix.Spencer@gmail.com", "Felix", "DB", 1, "Spencer" },
                    { 952, 23, "Dan.Towne28@yahoo.com", "Dan", "DB", 0, "Towne" },
                    { 953, 26, "Arlene49@gmail.com", "Arlene", "DB", 1, "Pacocha" },
                    { 954, 81, "Daryl.Bogisich17@gmail.com", "Daryl", "DB", 0, "Bogisich" },
                    { 955, 20, "May0@gmail.com", "May", "DB", 1, "Champlin" },
                    { 956, 86, "Anita_Nikolaus47@hotmail.com", "Anita", "DB", 0, "Nikolaus" },
                    { 957, 63, "Ryan_OKon12@yahoo.com", "Ryan", "DB", 0, "O'Kon" },
                    { 958, 37, "Ramiro78@gmail.com", "Ramiro", "DB", 0, "Abernathy" },
                    { 959, 12, "Beverly_Renner37@hotmail.com", "Beverly", "DB", 1, "Renner" },
                    { 960, 90, "Claude87@gmail.com", "Claude", "DB", 1, "Brown" },
                    { 961, 75, "Eileen_Tromp@hotmail.com", "Eileen", "DB", 1, "Tromp" },
                    { 962, 32, "Roman.Price7@yahoo.com", "Roman", "DB", 1, "Price" },
                    { 963, 56, "Kristie_Lebsack@yahoo.com", "Kristie", "DB", 1, "Lebsack" },
                    { 964, 42, "Clark_Fay91@yahoo.com", "Clark", "DB", 0, "Fay" },
                    { 965, 86, "Nellie_Jacobi51@gmail.com", "Nellie", "DB", 0, "Jacobi" },
                    { 966, 49, "Ramona64@gmail.com", "Ramona", "DB", 1, "Schumm" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 967, 90, "Erik81@gmail.com", "Erik", "DB", 0, "Marks" },
                    { 968, 54, "Helen.Donnelly81@yahoo.com", "Helen", "DB", 1, "Donnelly" },
                    { 969, 39, "Tricia48@hotmail.com", "Tricia", "DB", 0, "Marquardt" },
                    { 970, 18, "Al15@gmail.com", "Al", "DB", 1, "Brakus" },
                    { 971, 83, "Tyrone3@hotmail.com", "Tyrone", "DB", 1, "Keeling" },
                    { 972, 39, "Kristi32@yahoo.com", "Kristi", "DB", 0, "Roberts" },
                    { 973, 41, "Fannie.Price60@gmail.com", "Fannie", "DB", 0, "Price" },
                    { 974, 49, "Sara_Breitenberg88@gmail.com", "Sara", "DB", 1, "Breitenberg" },
                    { 975, 32, "Lucas.Champlin@yahoo.com", "Lucas", "DB", 0, "Champlin" },
                    { 976, 72, "Manuel.Mohr@gmail.com", "Manuel", "DB", 1, "Mohr" },
                    { 977, 43, "Chad5@gmail.com", "Chad", "DB", 1, "Rogahn" },
                    { 978, 28, "Miranda43@gmail.com", "Miranda", "DB", 1, "McDermott" },
                    { 979, 79, "Bobbie.Smith@gmail.com", "Bobbie", "DB", 0, "Smith" },
                    { 980, 48, "Wilson.Wyman@yahoo.com", "Wilson", "DB", 1, "Wyman" },
                    { 981, 76, "Kelli35@yahoo.com", "Kelli", "DB", 1, "Abshire" },
                    { 982, 83, "Grady.Green@hotmail.com", "Grady", "DB", 0, "Green" },
                    { 983, 18, "Rogelio_Larson94@yahoo.com", "Rogelio", "DB", 1, "Larson" },
                    { 984, 25, "Faith.Rodriguez@gmail.com", "Faith", "DB", 1, "Rodriguez" },
                    { 985, 27, "Elsie.Gerlach17@gmail.com", "Elsie", "DB", 1, "Gerlach" },
                    { 986, 65, "Jerald.Hamill@hotmail.com", "Jerald", "DB", 1, "Hamill" },
                    { 987, 33, "Morris15@gmail.com", "Morris", "DB", 0, "Shields" },
                    { 988, 35, "Jermaine.DuBuque1@hotmail.com", "Jermaine", "DB", 0, "DuBuque" },
                    { 989, 65, "Robyn.Keebler@yahoo.com", "Robyn", "DB", 1, "Keebler" },
                    { 990, 33, "Denise_Bahringer@gmail.com", "Denise", "DB", 1, "Bahringer" },
                    { 991, 69, "Elijah.Ankunding53@yahoo.com", "Elijah", "DB", 0, "Ankunding" },
                    { 992, 63, "Darla_Huels@yahoo.com", "Darla", "DB", 0, "Huels" },
                    { 993, 29, "Winifred46@yahoo.com", "Winifred", "DB", 1, "Towne" },
                    { 994, 86, "Christy_Jones@yahoo.com", "Christy", "DB", 1, "Jones" },
                    { 995, 48, "Joann.Predovic29@yahoo.com", "Joann", "DB", 0, "Predovic" },
                    { 996, 82, "Joel92@hotmail.com", "Joel", "DB", 0, "Koss" },
                    { 997, 51, "Cecelia10@yahoo.com", "Cecelia", "DB", 0, "McKenzie" },
                    { 998, 81, "Wm_Christiansen93@gmail.com", "Wm", "DB", 0, "Christiansen" },
                    { 999, 8, "Theresa_Hermann70@gmail.com", "Theresa", "DB", 0, "Hermann" },
                    { 1000, 46, "Bill33@yahoo.com", "Bill", "DB", 1, "Mraz" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
