using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataAccess.Migrations
{
    public partial class InitialCreate22 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    FirstName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LastName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Age = table.Column<int>(type: "int", nullable: false),
                    Email = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Gender = table.Column<int>(type: "int", nullable: false),
                    Framework = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 1, 79, "Andre_Schaden@gmail.com", "Andre", "DB", 1, "Schaden" },
                    { 2, 54, "Vickie_Lesch@hotmail.com", "Vickie", "DB", 1, "Lesch" },
                    { 3, 89, "Reginald_Moore@gmail.com", "Reginald", "DB", 1, "Moore" },
                    { 4, 15, "Gary3@gmail.com", "Gary", "DB", 1, "Schinner" },
                    { 5, 54, "Leo45@yahoo.com", "Leo", "DB", 1, "Schinner" },
                    { 6, 41, "Kyle_Witting87@hotmail.com", "Kyle", "DB", 1, "Witting" },
                    { 7, 71, "Mary_Reinger@gmail.com", "Mary", "DB", 1, "Reinger" },
                    { 8, 65, "Jamie_Stehr@gmail.com", "Jamie", "DB", 1, "Stehr" },
                    { 9, 60, "Jean42@yahoo.com", "Jean", "DB", 1, "Veum" },
                    { 10, 18, "Becky.Cruickshank38@gmail.com", "Becky", "DB", 1, "Cruickshank" },
                    { 11, 70, "Eva48@yahoo.com", "Eva", "DB", 1, "Schiller" },
                    { 12, 20, "Lynette.Ondricka28@gmail.com", "Lynette", "DB", 0, "Ondricka" },
                    { 13, 14, "Jesse96@yahoo.com", "Jesse", "DB", 1, "Nicolas" },
                    { 14, 40, "Ed.Kulas75@yahoo.com", "Ed", "DB", 0, "Kulas" },
                    { 15, 87, "Billy.Reynolds@gmail.com", "Billy", "DB", 1, "Reynolds" },
                    { 16, 73, "Toby87@yahoo.com", "Toby", "DB", 0, "Vandervort" },
                    { 17, 38, "Frankie.Purdy@hotmail.com", "Frankie", "DB", 0, "Purdy" },
                    { 18, 54, "Ed_Bernier@yahoo.com", "Ed", "DB", 1, "Bernier" },
                    { 19, 9, "Tina_Klein72@hotmail.com", "Tina", "DB", 1, "Klein" },
                    { 20, 34, "Olga_Hane@yahoo.com", "Olga", "DB", 0, "Hane" },
                    { 21, 21, "Ernesto.Kub71@gmail.com", "Ernesto", "DB", 0, "Kub" },
                    { 22, 44, "Jamie.Turner@gmail.com", "Jamie", "DB", 1, "Turner" },
                    { 23, 71, "Terrence_Towne@gmail.com", "Terrence", "DB", 1, "Towne" },
                    { 24, 72, "Rose_Marquardt@gmail.com", "Rose", "DB", 0, "Marquardt" },
                    { 25, 62, "Dwayne.Bednar8@yahoo.com", "Dwayne", "DB", 1, "Bednar" },
                    { 26, 60, "Stephen_Runolfsson@gmail.com", "Stephen", "DB", 1, "Runolfsson" },
                    { 27, 27, "Emilio.Treutel@gmail.com", "Emilio", "DB", 0, "Treutel" },
                    { 28, 47, "Kathleen.Jones@gmail.com", "Kathleen", "DB", 1, "Jones" },
                    { 29, 22, "Jamie_Goodwin42@gmail.com", "Jamie", "DB", 1, "Goodwin" },
                    { 30, 68, "Desiree.Trantow@gmail.com", "Desiree", "DB", 1, "Trantow" },
                    { 31, 56, "Anne.Graham73@hotmail.com", "Anne", "DB", 1, "Graham" },
                    { 32, 19, "Miriam68@gmail.com", "Miriam", "DB", 0, "Bauch" },
                    { 33, 44, "Myron31@hotmail.com", "Myron", "DB", 1, "Hauck" },
                    { 34, 32, "Carl29@hotmail.com", "Carl", "DB", 1, "VonRueden" },
                    { 35, 39, "Sean.Zemlak34@yahoo.com", "Sean", "DB", 1, "Zemlak" },
                    { 36, 87, "Cody.Jerde59@yahoo.com", "Cody", "DB", 1, "Jerde" },
                    { 37, 76, "Guadalupe7@hotmail.com", "Guadalupe", "DB", 0, "Ferry" },
                    { 38, 49, "Maxine.Pacocha@gmail.com", "Maxine", "DB", 0, "Pacocha" },
                    { 39, 35, "Marco41@gmail.com", "Marco", "DB", 1, "Stracke" },
                    { 40, 54, "Rita19@hotmail.com", "Rita", "DB", 0, "Hartmann" },
                    { 41, 61, "Evelyn_Volkman26@gmail.com", "Evelyn", "DB", 0, "Volkman" },
                    { 42, 88, "Justin.Hermiston10@yahoo.com", "Justin", "DB", 0, "Hermiston" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 43, 38, "Angelica_Ruecker72@yahoo.com", "Angelica", "DB", 0, "Ruecker" },
                    { 44, 83, "Flora.Wiegand@yahoo.com", "Flora", "DB", 1, "Wiegand" },
                    { 45, 46, "Jana76@yahoo.com", "Jana", "DB", 0, "Dach" },
                    { 46, 46, "Genevieve81@yahoo.com", "Genevieve", "DB", 0, "Gutkowski" },
                    { 47, 56, "Iris.Rempel@hotmail.com", "Iris", "DB", 0, "Rempel" },
                    { 48, 89, "Dawn.Nader78@hotmail.com", "Dawn", "DB", 0, "Nader" },
                    { 49, 21, "Lela.Kutch25@hotmail.com", "Lela", "DB", 1, "Kutch" },
                    { 50, 71, "Ross.Feil31@gmail.com", "Ross", "DB", 0, "Feil" },
                    { 51, 59, "Lucille28@gmail.com", "Lucille", "DB", 0, "Dietrich" },
                    { 52, 20, "Marcus76@yahoo.com", "Marcus", "DB", 0, "Zboncak" },
                    { 53, 72, "Allen_Schuster61@yahoo.com", "Allen", "DB", 0, "Schuster" },
                    { 54, 71, "Leland.Bode@yahoo.com", "Leland", "DB", 1, "Bode" },
                    { 55, 17, "Alvin_Hand29@gmail.com", "Alvin", "DB", 1, "Hand" },
                    { 56, 38, "Tonya.Spinka@yahoo.com", "Tonya", "DB", 0, "Spinka" },
                    { 57, 14, "Gerard_Stracke@yahoo.com", "Gerard", "DB", 0, "Stracke" },
                    { 58, 33, "Christopher_Farrell70@gmail.com", "Christopher", "DB", 0, "Farrell" },
                    { 59, 66, "Matthew4@yahoo.com", "Matthew", "DB", 1, "Conn" },
                    { 60, 56, "Percy_Bernhard@gmail.com", "Percy", "DB", 0, "Bernhard" },
                    { 61, 56, "Taylor_Crist53@gmail.com", "Taylor", "DB", 0, "Crist" },
                    { 62, 70, "Iris.Steuber93@gmail.com", "Iris", "DB", 0, "Steuber" },
                    { 63, 39, "Rudolph_Koch@hotmail.com", "Rudolph", "DB", 0, "Koch" },
                    { 64, 79, "Bruce91@gmail.com", "Bruce", "DB", 0, "Willms" },
                    { 65, 59, "Claire_Hermann@yahoo.com", "Claire", "DB", 1, "Hermann" },
                    { 66, 37, "Phil.Beahan71@gmail.com", "Phil", "DB", 1, "Beahan" },
                    { 67, 62, "Jose.Runolfsdottir42@yahoo.com", "Jose", "DB", 1, "Runolfsdottir" },
                    { 68, 25, "Michelle71@gmail.com", "Michelle", "DB", 1, "Marks" },
                    { 69, 16, "Rafael.Hilll72@yahoo.com", "Rafael", "DB", 1, "Hilll" },
                    { 70, 35, "Harry_Altenwerth@gmail.com", "Harry", "DB", 1, "Altenwerth" },
                    { 71, 57, "Christina26@gmail.com", "Christina", "DB", 1, "Murray" },
                    { 72, 51, "Jacob_Kertzmann75@hotmail.com", "Jacob", "DB", 1, "Kertzmann" },
                    { 73, 64, "Judy.Koss98@gmail.com", "Judy", "DB", 0, "Koss" },
                    { 74, 48, "Nathan.Beer93@gmail.com", "Nathan", "DB", 0, "Beer" },
                    { 75, 9, "Charlie_OKeefe@gmail.com", "Charlie", "DB", 0, "O'Keefe" },
                    { 76, 52, "Sabrina_Swaniawski@gmail.com", "Sabrina", "DB", 1, "Swaniawski" },
                    { 77, 50, "Jeannie4@gmail.com", "Jeannie", "DB", 0, "Upton" },
                    { 78, 75, "Israel_Orn25@gmail.com", "Israel", "DB", 1, "Orn" },
                    { 79, 87, "Kristy78@hotmail.com", "Kristy", "DB", 1, "Doyle" },
                    { 80, 15, "Isabel16@yahoo.com", "Isabel", "DB", 1, "Kuhn" },
                    { 81, 77, "Ethel.Bogisich@gmail.com", "Ethel", "DB", 1, "Bogisich" },
                    { 82, 37, "Norman_Marks43@gmail.com", "Norman", "DB", 0, "Marks" },
                    { 83, 18, "Boyd.Johnson24@yahoo.com", "Boyd", "DB", 1, "Johnson" },
                    { 84, 17, "Melody32@hotmail.com", "Melody", "DB", 1, "Hills" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 85, 70, "Cody9@gmail.com", "Cody", "DB", 0, "Bergstrom" },
                    { 86, 81, "Orlando42@yahoo.com", "Orlando", "DB", 0, "Bogan" },
                    { 87, 51, "Monique_Wilkinson26@hotmail.com", "Monique", "DB", 0, "Wilkinson" },
                    { 88, 65, "Kristen85@yahoo.com", "Kristen", "DB", 0, "McDermott" },
                    { 89, 83, "Marc_Weissnat78@gmail.com", "Marc", "DB", 0, "Weissnat" },
                    { 90, 79, "Rodney12@gmail.com", "Rodney", "DB", 0, "Kertzmann" },
                    { 91, 50, "Abraham97@yahoo.com", "Abraham", "DB", 1, "Dickinson" },
                    { 92, 49, "Lewis_Mayer@gmail.com", "Lewis", "DB", 0, "Mayer" },
                    { 93, 67, "Arthur_Murazik@yahoo.com", "Arthur", "DB", 0, "Murazik" },
                    { 94, 31, "Debra.Zemlak20@hotmail.com", "Debra", "DB", 1, "Zemlak" },
                    { 95, 70, "Erica21@gmail.com", "Erica", "DB", 1, "Rosenbaum" },
                    { 96, 54, "Curtis.Fadel@gmail.com", "Curtis", "DB", 0, "Fadel" },
                    { 97, 57, "Peggy_Corwin@yahoo.com", "Peggy", "DB", 1, "Corwin" },
                    { 98, 59, "Elisa_Spinka@gmail.com", "Elisa", "DB", 0, "Spinka" },
                    { 99, 38, "Karl86@hotmail.com", "Karl", "DB", 1, "Johnson" },
                    { 100, 10, "Clyde.Smitham@hotmail.com", "Clyde", "DB", 1, "Smitham" },
                    { 101, 29, "Marlon_Marvin47@hotmail.com", "Marlon", "DB", 1, "Marvin" },
                    { 102, 42, "Russell.Wiegand62@hotmail.com", "Russell", "DB", 0, "Wiegand" },
                    { 103, 67, "Jessica.Feest@hotmail.com", "Jessica", "DB", 1, "Feest" },
                    { 104, 56, "David_Kunze46@yahoo.com", "David", "DB", 0, "Kunze" },
                    { 105, 67, "Terrence98@yahoo.com", "Terrence", "DB", 1, "Huels" },
                    { 106, 37, "Ricky.Leannon58@hotmail.com", "Ricky", "DB", 1, "Leannon" },
                    { 107, 11, "Glenn_Torp76@hotmail.com", "Glenn", "DB", 1, "Torp" },
                    { 108, 46, "Horace.Dicki@yahoo.com", "Horace", "DB", 0, "Dicki" },
                    { 109, 73, "Nancy8@gmail.com", "Nancy", "DB", 0, "Bernier" },
                    { 110, 74, "Sammy.Will@yahoo.com", "Sammy", "DB", 0, "Will" },
                    { 111, 58, "Taylor.Wunsch46@gmail.com", "Taylor", "DB", 0, "Wunsch" },
                    { 112, 48, "Randal_Skiles37@yahoo.com", "Randal", "DB", 1, "Skiles" },
                    { 113, 69, "Mindy.Keeling26@hotmail.com", "Mindy", "DB", 1, "Keeling" },
                    { 114, 47, "Candace60@gmail.com", "Candace", "DB", 0, "O'Reilly" },
                    { 115, 73, "Olivia.Connelly43@yahoo.com", "Olivia", "DB", 0, "Connelly" },
                    { 116, 65, "Andy_Koss27@yahoo.com", "Andy", "DB", 0, "Koss" },
                    { 117, 17, "Diane_Gutkowski74@gmail.com", "Diane", "DB", 0, "Gutkowski" },
                    { 118, 51, "Anna55@hotmail.com", "Anna", "DB", 1, "DuBuque" },
                    { 119, 8, "Maryann_Pacocha@hotmail.com", "Maryann", "DB", 0, "Pacocha" },
                    { 120, 55, "Clarence_Walter17@hotmail.com", "Clarence", "DB", 0, "Walter" },
                    { 121, 31, "Dolores50@gmail.com", "Dolores", "DB", 1, "VonRueden" },
                    { 122, 70, "John_Mitchell46@hotmail.com", "John", "DB", 1, "Mitchell" },
                    { 123, 27, "Sylvia.Bogan80@hotmail.com", "Sylvia", "DB", 1, "Bogan" },
                    { 124, 9, "Timmy_Paucek@hotmail.com", "Timmy", "DB", 1, "Paucek" },
                    { 125, 31, "Audrey2@gmail.com", "Audrey", "DB", 1, "Halvorson" },
                    { 126, 76, "Martin.Dickinson@yahoo.com", "Martin", "DB", 1, "Dickinson" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 127, 80, "Deborah.Boyer@gmail.com", "Deborah", "DB", 0, "Boyer" },
                    { 128, 47, "Kenny.Doyle@gmail.com", "Kenny", "DB", 1, "Doyle" },
                    { 129, 69, "Hazel.Ortiz53@hotmail.com", "Hazel", "DB", 0, "Ortiz" },
                    { 130, 85, "Janice.Nicolas@hotmail.com", "Janice", "DB", 0, "Nicolas" },
                    { 131, 67, "Rodolfo.Grady51@hotmail.com", "Rodolfo", "DB", 0, "Grady" },
                    { 132, 28, "Eleanor.Hintz41@hotmail.com", "Eleanor", "DB", 1, "Hintz" },
                    { 133, 88, "Glenda20@hotmail.com", "Glenda", "DB", 1, "Swift" },
                    { 134, 61, "Cody.Bins7@hotmail.com", "Cody", "DB", 1, "Bins" },
                    { 135, 78, "Terence17@yahoo.com", "Terence", "DB", 1, "Walsh" },
                    { 136, 17, "Heidi_Goodwin@hotmail.com", "Heidi", "DB", 1, "Goodwin" },
                    { 137, 53, "Elvira_Kulas@yahoo.com", "Elvira", "DB", 0, "Kulas" },
                    { 138, 35, "Vincent_Ullrich73@gmail.com", "Vincent", "DB", 0, "Ullrich" },
                    { 139, 60, "Terrance_Leuschke61@hotmail.com", "Terrance", "DB", 1, "Leuschke" },
                    { 140, 50, "Richard77@gmail.com", "Richard", "DB", 1, "Heidenreich" },
                    { 141, 19, "Fred_Boyer@gmail.com", "Fred", "DB", 0, "Boyer" },
                    { 142, 84, "Dexter78@gmail.com", "Dexter", "DB", 0, "Schneider" },
                    { 143, 70, "Marta90@gmail.com", "Marta", "DB", 0, "Cummerata" },
                    { 144, 84, "Martha.Schaden79@hotmail.com", "Martha", "DB", 0, "Schaden" },
                    { 145, 75, "Loretta6@yahoo.com", "Loretta", "DB", 1, "Klocko" },
                    { 146, 8, "Guadalupe26@gmail.com", "Guadalupe", "DB", 1, "Emard" },
                    { 147, 88, "Ben_Cronin@gmail.com", "Ben", "DB", 1, "Cronin" },
                    { 148, 77, "Patsy_Yundt7@yahoo.com", "Patsy", "DB", 0, "Yundt" },
                    { 149, 90, "Stanley62@gmail.com", "Stanley", "DB", 1, "Beahan" },
                    { 150, 48, "Roland91@yahoo.com", "Roland", "DB", 1, "Quitzon" },
                    { 151, 71, "Henry51@gmail.com", "Henry", "DB", 1, "Krajcik" },
                    { 152, 41, "Albert30@hotmail.com", "Albert", "DB", 0, "Moen" },
                    { 153, 57, "Harvey_Gottlieb40@yahoo.com", "Harvey", "DB", 1, "Gottlieb" },
                    { 154, 43, "Christine21@hotmail.com", "Christine", "DB", 1, "Jaskolski" },
                    { 155, 39, "Lynn.Hills@yahoo.com", "Lynn", "DB", 0, "Hills" },
                    { 156, 74, "Kristie52@gmail.com", "Kristie", "DB", 1, "Kemmer" },
                    { 157, 8, "Melanie.Stroman30@hotmail.com", "Melanie", "DB", 0, "Stroman" },
                    { 158, 70, "Lola.Douglas@hotmail.com", "Lola", "DB", 1, "Douglas" },
                    { 159, 13, "Miriam59@yahoo.com", "Miriam", "DB", 1, "Price" },
                    { 160, 46, "Jeff.Macejkovic@yahoo.com", "Jeff", "DB", 1, "Macejkovic" },
                    { 161, 50, "Sean46@gmail.com", "Sean", "DB", 0, "Schmitt" },
                    { 162, 82, "Tyler.Hermiston@gmail.com", "Tyler", "DB", 1, "Hermiston" },
                    { 163, 77, "Ismael_Considine@yahoo.com", "Ismael", "DB", 0, "Considine" },
                    { 164, 68, "Chelsea.Breitenberg@yahoo.com", "Chelsea", "DB", 1, "Breitenberg" },
                    { 165, 30, "Pat_Lang59@gmail.com", "Pat", "DB", 0, "Lang" },
                    { 166, 12, "Courtney44@yahoo.com", "Courtney", "DB", 1, "MacGyver" },
                    { 167, 17, "Patty52@hotmail.com", "Patty", "DB", 0, "Crooks" },
                    { 168, 89, "Emily_Watsica@gmail.com", "Emily", "DB", 1, "Watsica" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 169, 16, "Maureen56@yahoo.com", "Maureen", "DB", 1, "Lemke" },
                    { 170, 86, "Alton.Bechtelar66@yahoo.com", "Alton", "DB", 1, "Bechtelar" },
                    { 171, 29, "Esther.Hansen47@yahoo.com", "Esther", "DB", 0, "Hansen" },
                    { 172, 33, "Beth52@yahoo.com", "Beth", "DB", 1, "Ritchie" },
                    { 173, 12, "Josh10@gmail.com", "Josh", "DB", 0, "Mertz" },
                    { 174, 66, "Faith.Parisian94@yahoo.com", "Faith", "DB", 0, "Parisian" },
                    { 175, 46, "Jon.Heaney@yahoo.com", "Jon", "DB", 1, "Heaney" },
                    { 176, 13, "Cristina24@hotmail.com", "Cristina", "DB", 1, "Stehr" },
                    { 177, 19, "Nora.Reichert@yahoo.com", "Nora", "DB", 1, "Reichert" },
                    { 178, 76, "Leona.Gusikowski@hotmail.com", "Leona", "DB", 1, "Gusikowski" },
                    { 179, 31, "Nettie_Altenwerth@gmail.com", "Nettie", "DB", 1, "Altenwerth" },
                    { 180, 29, "Guy33@yahoo.com", "Guy", "DB", 0, "Lakin" },
                    { 181, 68, "Dorothy.Skiles@hotmail.com", "Dorothy", "DB", 1, "Skiles" },
                    { 182, 9, "Pam_Larson@hotmail.com", "Pam", "DB", 0, "Larson" },
                    { 183, 24, "Erik_Ryan34@gmail.com", "Erik", "DB", 1, "Ryan" },
                    { 184, 40, "Molly_Harvey@yahoo.com", "Molly", "DB", 1, "Harvey" },
                    { 185, 25, "Celia33@hotmail.com", "Celia", "DB", 1, "Parisian" },
                    { 186, 19, "Ben53@gmail.com", "Ben", "DB", 0, "Hartmann" },
                    { 187, 87, "Sonja.Purdy12@gmail.com", "Sonja", "DB", 1, "Purdy" },
                    { 188, 77, "Violet14@hotmail.com", "Violet", "DB", 0, "Schoen" },
                    { 189, 39, "Armando_Kemmer@hotmail.com", "Armando", "DB", 1, "Kemmer" },
                    { 190, 18, "Lyle_Heller@yahoo.com", "Lyle", "DB", 1, "Heller" },
                    { 191, 68, "Jackie22@hotmail.com", "Jackie", "DB", 1, "Bechtelar" },
                    { 192, 37, "Jay49@hotmail.com", "Jay", "DB", 0, "Funk" },
                    { 193, 18, "Otis_Haley@gmail.com", "Otis", "DB", 0, "Haley" },
                    { 194, 52, "Maryann_Hyatt@yahoo.com", "Maryann", "DB", 0, "Hyatt" },
                    { 195, 26, "Silvia_Donnelly@yahoo.com", "Silvia", "DB", 0, "Donnelly" },
                    { 196, 9, "Gabriel_Balistreri@gmail.com", "Gabriel", "DB", 1, "Balistreri" },
                    { 197, 39, "Latoya.Klein@gmail.com", "Latoya", "DB", 1, "Klein" },
                    { 198, 72, "Corey.Emard86@gmail.com", "Corey", "DB", 0, "Emard" },
                    { 199, 39, "Fannie34@hotmail.com", "Fannie", "DB", 1, "Predovic" },
                    { 200, 61, "Ed81@yahoo.com", "Ed", "DB", 0, "Kuvalis" },
                    { 201, 33, "Woodrow.Robel@gmail.com", "Woodrow", "DB", 1, "Robel" },
                    { 202, 62, "Darrel_Wisoky41@gmail.com", "Darrel", "DB", 1, "Wisoky" },
                    { 203, 14, "Marcos.Zboncak62@yahoo.com", "Marcos", "DB", 1, "Zboncak" },
                    { 204, 79, "Tracey.Schoen0@hotmail.com", "Tracey", "DB", 0, "Schoen" },
                    { 205, 12, "Darnell_Lockman@gmail.com", "Darnell", "DB", 0, "Lockman" },
                    { 206, 41, "Barry_Gaylord@hotmail.com", "Barry", "DB", 1, "Gaylord" },
                    { 207, 74, "Kimberly_Turner58@yahoo.com", "Kimberly", "DB", 1, "Turner" },
                    { 208, 12, "Mary12@hotmail.com", "Mary", "DB", 1, "Connelly" },
                    { 209, 48, "Earl86@gmail.com", "Earl", "DB", 1, "Fisher" },
                    { 210, 38, "Jamie.Greenfelder@hotmail.com", "Jamie", "DB", 0, "Greenfelder" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 211, 20, "Melanie.Lubowitz62@hotmail.com", "Melanie", "DB", 1, "Lubowitz" },
                    { 212, 66, "Ernest50@gmail.com", "Ernest", "DB", 1, "Reinger" },
                    { 213, 55, "Christy.Kunde@yahoo.com", "Christy", "DB", 1, "Kunde" },
                    { 214, 34, "Jan89@yahoo.com", "Jan", "DB", 0, "Kunze" },
                    { 215, 19, "Frank_Kuvalis@yahoo.com", "Frank", "DB", 0, "Kuvalis" },
                    { 216, 69, "Omar.Bartell@yahoo.com", "Omar", "DB", 0, "Bartell" },
                    { 217, 14, "Ernesto17@yahoo.com", "Ernesto", "DB", 0, "Hodkiewicz" },
                    { 218, 12, "Tommie.Grant@hotmail.com", "Tommie", "DB", 1, "Grant" },
                    { 219, 37, "Cathy.Gutmann36@hotmail.com", "Cathy", "DB", 1, "Gutmann" },
                    { 220, 58, "Shannon52@yahoo.com", "Shannon", "DB", 0, "Becker" },
                    { 221, 31, "Brian_Towne73@hotmail.com", "Brian", "DB", 0, "Towne" },
                    { 222, 44, "Brandi.Toy72@gmail.com", "Brandi", "DB", 0, "Toy" },
                    { 223, 55, "Nellie33@gmail.com", "Nellie", "DB", 0, "Conn" },
                    { 224, 20, "Wanda_Satterfield@hotmail.com", "Wanda", "DB", 1, "Satterfield" },
                    { 225, 38, "Gretchen39@yahoo.com", "Gretchen", "DB", 0, "Sauer" },
                    { 226, 14, "Theresa_Collier53@hotmail.com", "Theresa", "DB", 0, "Collier" },
                    { 227, 35, "Marianne_Moen38@gmail.com", "Marianne", "DB", 1, "Moen" },
                    { 228, 20, "Andrew4@yahoo.com", "Andrew", "DB", 1, "Dickinson" },
                    { 229, 45, "Lindsay55@gmail.com", "Lindsay", "DB", 1, "Muller" },
                    { 230, 27, "Ronnie_Konopelski39@hotmail.com", "Ronnie", "DB", 1, "Konopelski" },
                    { 231, 36, "Robyn28@yahoo.com", "Robyn", "DB", 0, "Rempel" },
                    { 232, 71, "Shelley52@gmail.com", "Shelley", "DB", 1, "Hermiston" },
                    { 233, 54, "Lisa6@gmail.com", "Lisa", "DB", 0, "Morar" },
                    { 234, 41, "Cora_Brown@gmail.com", "Cora", "DB", 0, "Brown" },
                    { 235, 24, "Kathryn89@hotmail.com", "Kathryn", "DB", 0, "Moore" },
                    { 236, 77, "Elias_Langosh44@yahoo.com", "Elias", "DB", 1, "Langosh" },
                    { 237, 39, "Samuel27@yahoo.com", "Samuel", "DB", 1, "Heaney" },
                    { 238, 28, "Dominick.Funk@hotmail.com", "Dominick", "DB", 0, "Funk" },
                    { 239, 42, "Brett9@hotmail.com", "Brett", "DB", 0, "O'Connell" },
                    { 240, 84, "Brooke.Herman@gmail.com", "Brooke", "DB", 0, "Herman" },
                    { 241, 12, "Thelma_Oberbrunner52@gmail.com", "Thelma", "DB", 1, "Oberbrunner" },
                    { 242, 68, "Javier77@yahoo.com", "Javier", "DB", 1, "Koss" },
                    { 243, 55, "Pam38@hotmail.com", "Pam", "DB", 1, "Windler" },
                    { 244, 90, "Everett.Aufderhar90@gmail.com", "Everett", "DB", 0, "Aufderhar" },
                    { 245, 29, "Annie_Ferry@hotmail.com", "Annie", "DB", 0, "Ferry" },
                    { 246, 33, "Michael.Osinski@yahoo.com", "Michael", "DB", 1, "Osinski" },
                    { 247, 25, "Alma28@gmail.com", "Alma", "DB", 0, "Prohaska" },
                    { 248, 67, "Noel50@hotmail.com", "Noel", "DB", 1, "Ernser" },
                    { 249, 35, "Raul_Hermann@yahoo.com", "Raul", "DB", 1, "Hermann" },
                    { 250, 79, "Lee_Rogahn51@gmail.com", "Lee", "DB", 1, "Rogahn" },
                    { 251, 14, "Celia.Cronin@gmail.com", "Celia", "DB", 0, "Cronin" },
                    { 252, 17, "Barbara.Schmeler17@gmail.com", "Barbara", "DB", 0, "Schmeler" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 253, 20, "Rafael_Kemmer4@gmail.com", "Rafael", "DB", 1, "Kemmer" },
                    { 254, 69, "Ernest80@hotmail.com", "Ernest", "DB", 0, "Witting" },
                    { 255, 40, "Kristen_Stoltenberg@yahoo.com", "Kristen", "DB", 0, "Stoltenberg" },
                    { 256, 89, "Conrad.Lockman@hotmail.com", "Conrad", "DB", 0, "Lockman" },
                    { 257, 55, "Rose_Green@hotmail.com", "Rose", "DB", 0, "Green" },
                    { 258, 81, "Beverly_Parisian35@hotmail.com", "Beverly", "DB", 0, "Parisian" },
                    { 259, 22, "Lorenzo_Rogahn@gmail.com", "Lorenzo", "DB", 0, "Rogahn" },
                    { 260, 12, "Alberto_Howell@gmail.com", "Alberto", "DB", 0, "Howell" },
                    { 261, 15, "Hattie74@hotmail.com", "Hattie", "DB", 0, "Tillman" },
                    { 262, 67, "Angelica_Daniel@yahoo.com", "Angelica", "DB", 1, "Daniel" },
                    { 263, 44, "Lula_Rice@yahoo.com", "Lula", "DB", 0, "Rice" },
                    { 264, 54, "Douglas.Rempel45@yahoo.com", "Douglas", "DB", 1, "Rempel" },
                    { 265, 59, "Jennie75@gmail.com", "Jennie", "DB", 0, "Durgan" },
                    { 266, 90, "Sherri80@gmail.com", "Sherri", "DB", 0, "Gislason" },
                    { 267, 57, "Patrick_Baumbach55@gmail.com", "Patrick", "DB", 1, "Baumbach" },
                    { 268, 60, "Ora75@hotmail.com", "Ora", "DB", 1, "Mann" },
                    { 269, 67, "Charles_Schroeder@yahoo.com", "Charles", "DB", 0, "Schroeder" },
                    { 270, 38, "Maryann60@hotmail.com", "Maryann", "DB", 1, "Conn" },
                    { 271, 80, "Evelyn.Padberg69@hotmail.com", "Evelyn", "DB", 0, "Padberg" },
                    { 272, 20, "Jessie_Ziemann32@hotmail.com", "Jessie", "DB", 0, "Ziemann" },
                    { 273, 12, "Arturo.Huels17@gmail.com", "Arturo", "DB", 1, "Huels" },
                    { 274, 26, "Sheryl.Parisian@gmail.com", "Sheryl", "DB", 0, "Parisian" },
                    { 275, 21, "Guadalupe74@hotmail.com", "Guadalupe", "DB", 0, "Bashirian" },
                    { 276, 11, "Beatrice54@gmail.com", "Beatrice", "DB", 0, "Christiansen" },
                    { 277, 52, "Sammy.Monahan@yahoo.com", "Sammy", "DB", 1, "Monahan" },
                    { 278, 52, "Dexter_Schaden0@yahoo.com", "Dexter", "DB", 0, "Schaden" },
                    { 279, 73, "Troy31@hotmail.com", "Troy", "DB", 1, "Schneider" },
                    { 280, 81, "Kurt.Wyman22@gmail.com", "Kurt", "DB", 1, "Wyman" },
                    { 281, 64, "Bob.Schulist13@yahoo.com", "Bob", "DB", 0, "Schulist" },
                    { 282, 51, "Barry50@gmail.com", "Barry", "DB", 0, "Greenfelder" },
                    { 283, 76, "Tyrone.Jacobson98@yahoo.com", "Tyrone", "DB", 0, "Jacobson" },
                    { 284, 76, "Marcus31@gmail.com", "Marcus", "DB", 1, "Nicolas" },
                    { 285, 47, "Cody.Hane77@yahoo.com", "Cody", "DB", 1, "Hane" },
                    { 286, 25, "Megan.Gaylord@gmail.com", "Megan", "DB", 1, "Gaylord" },
                    { 287, 79, "Neal_Goodwin17@gmail.com", "Neal", "DB", 1, "Goodwin" },
                    { 288, 76, "Sheri.Gerlach11@hotmail.com", "Sheri", "DB", 0, "Gerlach" },
                    { 289, 79, "Kenneth_Legros@hotmail.com", "Kenneth", "DB", 1, "Legros" },
                    { 290, 35, "Kathryn.Reilly@gmail.com", "Kathryn", "DB", 1, "Reilly" },
                    { 291, 79, "Priscilla_Hermann6@yahoo.com", "Priscilla", "DB", 0, "Hermann" },
                    { 292, 28, "Emma.Dickens@hotmail.com", "Emma", "DB", 0, "Dickens" },
                    { 293, 18, "Kyle.Weber@hotmail.com", "Kyle", "DB", 1, "Weber" },
                    { 294, 37, "Eric.McGlynn@yahoo.com", "Eric", "DB", 0, "McGlynn" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 295, 19, "Nelson.OHara@hotmail.com", "Nelson", "DB", 1, "O'Hara" },
                    { 296, 68, "Kelly.Hermiston61@yahoo.com", "Kelly", "DB", 1, "Hermiston" },
                    { 297, 49, "Shannon.Kerluke@yahoo.com", "Shannon", "DB", 1, "Kerluke" },
                    { 298, 64, "Derek33@yahoo.com", "Derek", "DB", 1, "Hilll" },
                    { 299, 48, "Deanna.Effertz28@gmail.com", "Deanna", "DB", 1, "Effertz" },
                    { 300, 89, "Marion_Hoeger13@yahoo.com", "Marion", "DB", 1, "Hoeger" },
                    { 301, 41, "Arturo.Stehr32@hotmail.com", "Arturo", "DB", 0, "Stehr" },
                    { 302, 81, "Suzanne.Frami36@hotmail.com", "Suzanne", "DB", 1, "Frami" },
                    { 303, 9, "Marvin_Jenkins24@hotmail.com", "Marvin", "DB", 1, "Jenkins" },
                    { 304, 26, "Zachary79@hotmail.com", "Zachary", "DB", 0, "Jakubowski" },
                    { 305, 58, "Hannah30@yahoo.com", "Hannah", "DB", 0, "Hahn" },
                    { 306, 68, "Vincent.Kemmer69@hotmail.com", "Vincent", "DB", 0, "Kemmer" },
                    { 307, 59, "Jamie.Bergstrom@gmail.com", "Jamie", "DB", 0, "Bergstrom" },
                    { 308, 69, "Terry.Bradtke61@gmail.com", "Terry", "DB", 0, "Bradtke" },
                    { 309, 86, "Hubert.West@yahoo.com", "Hubert", "DB", 0, "West" },
                    { 310, 43, "Archie56@yahoo.com", "Archie", "DB", 0, "Klein" },
                    { 311, 51, "Geoffrey32@hotmail.com", "Geoffrey", "DB", 1, "Gusikowski" },
                    { 312, 43, "Roger_Hills44@yahoo.com", "Roger", "DB", 1, "Hills" },
                    { 313, 49, "Marcos_Rau57@hotmail.com", "Marcos", "DB", 0, "Rau" },
                    { 314, 88, "Noah_Emmerich71@gmail.com", "Noah", "DB", 1, "Emmerich" },
                    { 315, 41, "Glenda5@hotmail.com", "Glenda", "DB", 1, "Kunze" },
                    { 316, 18, "Fredrick79@hotmail.com", "Fredrick", "DB", 0, "Bode" },
                    { 317, 61, "Stacey.Smitham@gmail.com", "Stacey", "DB", 1, "Smitham" },
                    { 318, 45, "Ben_Lueilwitz68@gmail.com", "Ben", "DB", 1, "Lueilwitz" },
                    { 319, 26, "Ismael_Beer@yahoo.com", "Ismael", "DB", 1, "Beer" },
                    { 320, 59, "Kristy.Rice@yahoo.com", "Kristy", "DB", 1, "Rice" },
                    { 321, 39, "Edith67@gmail.com", "Edith", "DB", 0, "Hand" },
                    { 322, 80, "Shirley_Hayes@gmail.com", "Shirley", "DB", 1, "Hayes" },
                    { 323, 51, "Wayne.Gulgowski@gmail.com", "Wayne", "DB", 1, "Gulgowski" },
                    { 324, 62, "Chris.Pouros7@yahoo.com", "Chris", "DB", 1, "Pouros" },
                    { 325, 41, "Glenda.Aufderhar94@gmail.com", "Glenda", "DB", 0, "Aufderhar" },
                    { 326, 46, "Arnold78@yahoo.com", "Arnold", "DB", 0, "Kohler" },
                    { 327, 74, "Earl.Ebert@yahoo.com", "Earl", "DB", 1, "Ebert" },
                    { 328, 11, "Sylvester29@yahoo.com", "Sylvester", "DB", 0, "Pouros" },
                    { 329, 32, "Maggie55@hotmail.com", "Maggie", "DB", 1, "Hartmann" },
                    { 330, 47, "Leroy.Rutherford@gmail.com", "Leroy", "DB", 0, "Rutherford" },
                    { 331, 78, "Gwen_Rice@yahoo.com", "Gwen", "DB", 1, "Rice" },
                    { 332, 67, "Colin76@hotmail.com", "Colin", "DB", 0, "Farrell" },
                    { 333, 59, "Tracy.Gislason@yahoo.com", "Tracy", "DB", 1, "Gislason" },
                    { 334, 35, "Allan_Miller63@yahoo.com", "Allan", "DB", 0, "Miller" },
                    { 335, 8, "Gordon16@gmail.com", "Gordon", "DB", 0, "Hansen" },
                    { 336, 23, "Theodore_Gerlach@yahoo.com", "Theodore", "DB", 0, "Gerlach" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 337, 24, "Lonnie.Lemke99@yahoo.com", "Lonnie", "DB", 1, "Lemke" },
                    { 338, 17, "Kelly_Wisoky@yahoo.com", "Kelly", "DB", 1, "Wisoky" },
                    { 339, 50, "Reginald.Schamberger@gmail.com", "Reginald", "DB", 0, "Schamberger" },
                    { 340, 25, "Andre_Walker25@hotmail.com", "Andre", "DB", 0, "Walker" },
                    { 341, 61, "Gilbert.Yundt@yahoo.com", "Gilbert", "DB", 0, "Yundt" },
                    { 342, 24, "Ollie22@yahoo.com", "Ollie", "DB", 0, "Lindgren" },
                    { 343, 49, "Hannah31@yahoo.com", "Hannah", "DB", 0, "Kertzmann" },
                    { 344, 21, "Darrell.Macejkovic21@gmail.com", "Darrell", "DB", 0, "Macejkovic" },
                    { 345, 56, "Lillie.Rath35@hotmail.com", "Lillie", "DB", 1, "Rath" },
                    { 346, 75, "Percy_Fisher@gmail.com", "Percy", "DB", 1, "Fisher" },
                    { 347, 87, "Carla.Kessler53@hotmail.com", "Carla", "DB", 1, "Kessler" },
                    { 348, 36, "Noah80@hotmail.com", "Noah", "DB", 1, "Daniel" },
                    { 349, 33, "Darrel.Smith@gmail.com", "Darrel", "DB", 0, "Smith" },
                    { 350, 78, "Megan.Terry71@gmail.com", "Megan", "DB", 1, "Terry" },
                    { 351, 35, "Arnold.Conn@hotmail.com", "Arnold", "DB", 0, "Conn" },
                    { 352, 52, "Rex.Fritsch@hotmail.com", "Rex", "DB", 0, "Fritsch" },
                    { 353, 28, "Walter_Ledner@yahoo.com", "Walter", "DB", 0, "Ledner" },
                    { 354, 22, "Roberto.Hills@yahoo.com", "Roberto", "DB", 1, "Hills" },
                    { 355, 28, "Lula.Mosciski78@yahoo.com", "Lula", "DB", 1, "Mosciski" },
                    { 356, 88, "Max.Bergstrom@hotmail.com", "Max", "DB", 1, "Bergstrom" },
                    { 357, 23, "Lance_Marks13@yahoo.com", "Lance", "DB", 0, "Marks" },
                    { 358, 48, "Violet7@yahoo.com", "Violet", "DB", 1, "Johnson" },
                    { 359, 72, "Willie30@yahoo.com", "Willie", "DB", 1, "Lakin" },
                    { 360, 13, "Lindsey.Graham32@yahoo.com", "Lindsey", "DB", 0, "Graham" },
                    { 361, 45, "Pamela_Larkin87@yahoo.com", "Pamela", "DB", 1, "Larkin" },
                    { 362, 35, "Rochelle_Leannon@gmail.com", "Rochelle", "DB", 0, "Leannon" },
                    { 363, 74, "Darla_Mertz16@hotmail.com", "Darla", "DB", 1, "Mertz" },
                    { 364, 53, "Justin20@hotmail.com", "Justin", "DB", 1, "Dare" },
                    { 365, 28, "Nellie.Schmeler14@gmail.com", "Nellie", "DB", 1, "Schmeler" },
                    { 366, 33, "Kristine82@hotmail.com", "Kristine", "DB", 0, "Pagac" },
                    { 367, 75, "Julio73@hotmail.com", "Julio", "DB", 1, "Grimes" },
                    { 368, 49, "Gail_Jones83@hotmail.com", "Gail", "DB", 0, "Jones" },
                    { 369, 54, "Barbara_Greenfelder@yahoo.com", "Barbara", "DB", 0, "Greenfelder" },
                    { 370, 81, "Geraldine63@hotmail.com", "Geraldine", "DB", 0, "West" },
                    { 371, 51, "Ebony.Ullrich57@gmail.com", "Ebony", "DB", 0, "Ullrich" },
                    { 372, 79, "Kent58@hotmail.com", "Kent", "DB", 0, "Wisoky" },
                    { 373, 78, "Hannah_Nolan@hotmail.com", "Hannah", "DB", 0, "Nolan" },
                    { 374, 84, "Earl.Bauch@hotmail.com", "Earl", "DB", 0, "Bauch" },
                    { 375, 81, "Hattie7@hotmail.com", "Hattie", "DB", 0, "Medhurst" },
                    { 376, 43, "Bert.Carroll95@yahoo.com", "Bert", "DB", 0, "Carroll" },
                    { 377, 36, "Minnie_Zieme@yahoo.com", "Minnie", "DB", 0, "Zieme" },
                    { 378, 87, "Leon24@gmail.com", "Leon", "DB", 1, "Schulist" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 379, 16, "Lorena_Friesen0@hotmail.com", "Lorena", "DB", 1, "Friesen" },
                    { 380, 26, "Garry_Herzog@yahoo.com", "Garry", "DB", 1, "Herzog" },
                    { 381, 85, "Lionel_Berge60@gmail.com", "Lionel", "DB", 0, "Berge" },
                    { 382, 40, "Terrance40@yahoo.com", "Terrance", "DB", 0, "Erdman" },
                    { 383, 39, "Herman_Kunze57@hotmail.com", "Herman", "DB", 0, "Kunze" },
                    { 384, 63, "Roosevelt.Hegmann84@yahoo.com", "Roosevelt", "DB", 0, "Hegmann" },
                    { 385, 53, "Miriam79@hotmail.com", "Miriam", "DB", 0, "Nikolaus" },
                    { 386, 77, "Conrad56@gmail.com", "Conrad", "DB", 1, "Lebsack" },
                    { 387, 21, "Ruby.Upton96@gmail.com", "Ruby", "DB", 0, "Upton" },
                    { 388, 49, "Franklin.Blick24@hotmail.com", "Franklin", "DB", 1, "Blick" },
                    { 389, 81, "Leigh_Paucek2@hotmail.com", "Leigh", "DB", 1, "Paucek" },
                    { 390, 76, "Rachel_Oberbrunner@gmail.com", "Rachel", "DB", 0, "Oberbrunner" },
                    { 391, 40, "Gina57@hotmail.com", "Gina", "DB", 0, "Yundt" },
                    { 392, 78, "Melinda.Willms20@yahoo.com", "Melinda", "DB", 1, "Willms" },
                    { 393, 66, "Ron_Williamson@hotmail.com", "Ron", "DB", 0, "Williamson" },
                    { 394, 28, "Franklin80@hotmail.com", "Franklin", "DB", 0, "Streich" },
                    { 395, 76, "Jamie_Pfannerstill@gmail.com", "Jamie", "DB", 1, "Pfannerstill" },
                    { 396, 79, "Marilyn.Harber9@yahoo.com", "Marilyn", "DB", 1, "Harber" },
                    { 397, 10, "Ken_Hand38@gmail.com", "Ken", "DB", 1, "Hand" },
                    { 398, 33, "Jaime18@hotmail.com", "Jaime", "DB", 0, "Nolan" },
                    { 399, 54, "Damon.Terry42@gmail.com", "Damon", "DB", 1, "Terry" },
                    { 400, 90, "Edmond_Champlin@yahoo.com", "Edmond", "DB", 0, "Champlin" },
                    { 401, 52, "Lonnie.Schulist82@hotmail.com", "Lonnie", "DB", 0, "Schulist" },
                    { 402, 79, "Luz_Bruen@yahoo.com", "Luz", "DB", 0, "Bruen" },
                    { 403, 43, "Owen91@hotmail.com", "Owen", "DB", 1, "Stanton" },
                    { 404, 63, "Wm.Kohler@yahoo.com", "Wm", "DB", 1, "Kohler" },
                    { 405, 77, "Shirley.Block59@gmail.com", "Shirley", "DB", 0, "Block" },
                    { 406, 70, "Rosalie.Sanford@gmail.com", "Rosalie", "DB", 0, "Sanford" },
                    { 407, 19, "Sheryl74@gmail.com", "Sheryl", "DB", 0, "Leuschke" },
                    { 408, 14, "Angelina_Muller6@gmail.com", "Angelina", "DB", 1, "Muller" },
                    { 409, 39, "Francisco_Adams73@hotmail.com", "Francisco", "DB", 1, "Adams" },
                    { 410, 19, "Seth7@yahoo.com", "Seth", "DB", 1, "Hamill" },
                    { 411, 20, "Justin_Ortiz65@hotmail.com", "Justin", "DB", 1, "Ortiz" },
                    { 412, 46, "Luz72@hotmail.com", "Luz", "DB", 0, "McLaughlin" },
                    { 413, 77, "Rickey_Pouros20@yahoo.com", "Rickey", "DB", 1, "Pouros" },
                    { 414, 86, "Blake_Durgan89@gmail.com", "Blake", "DB", 0, "Durgan" },
                    { 415, 61, "Lisa_Reynolds@yahoo.com", "Lisa", "DB", 1, "Reynolds" },
                    { 416, 24, "Dale_Bashirian@hotmail.com", "Dale", "DB", 1, "Bashirian" },
                    { 417, 16, "Edith_Labadie0@yahoo.com", "Edith", "DB", 0, "Labadie" },
                    { 418, 39, "Evan85@gmail.com", "Evan", "DB", 1, "D'Amore" },
                    { 419, 59, "Stephen.Williamson@yahoo.com", "Stephen", "DB", 1, "Williamson" },
                    { 420, 88, "Tami.Mertz70@hotmail.com", "Tami", "DB", 1, "Mertz" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 421, 55, "Lauren_Roob@gmail.com", "Lauren", "DB", 0, "Roob" },
                    { 422, 18, "Vickie22@hotmail.com", "Vickie", "DB", 1, "Denesik" },
                    { 423, 27, "Bennie_Cartwright@yahoo.com", "Bennie", "DB", 0, "Cartwright" },
                    { 424, 22, "Johnathan.Metz@hotmail.com", "Johnathan", "DB", 1, "Metz" },
                    { 425, 50, "Wm_Deckow71@gmail.com", "Wm", "DB", 1, "Deckow" },
                    { 426, 12, "Orlando.Legros@hotmail.com", "Orlando", "DB", 1, "Legros" },
                    { 427, 30, "Wendy90@gmail.com", "Wendy", "DB", 0, "Graham" },
                    { 428, 9, "Armando92@yahoo.com", "Armando", "DB", 1, "Herzog" },
                    { 429, 57, "Dominic.Corkery10@hotmail.com", "Dominic", "DB", 1, "Corkery" },
                    { 430, 38, "Sonia.Cronin8@yahoo.com", "Sonia", "DB", 1, "Cronin" },
                    { 431, 50, "Marsha_Satterfield75@yahoo.com", "Marsha", "DB", 0, "Satterfield" },
                    { 432, 70, "Sophie_Donnelly@hotmail.com", "Sophie", "DB", 0, "Donnelly" },
                    { 433, 70, "Mindy.Baumbach6@hotmail.com", "Mindy", "DB", 1, "Baumbach" },
                    { 434, 67, "Hubert88@hotmail.com", "Hubert", "DB", 1, "Quitzon" },
                    { 435, 23, "Desiree.Runte@hotmail.com", "Desiree", "DB", 1, "Runte" },
                    { 436, 72, "Brittany_Lockman@yahoo.com", "Brittany", "DB", 0, "Lockman" },
                    { 437, 41, "Maureen99@gmail.com", "Maureen", "DB", 0, "Bailey" },
                    { 438, 65, "Christie_Kulas59@gmail.com", "Christie", "DB", 1, "Kulas" },
                    { 439, 12, "Dianne_Shanahan48@yahoo.com", "Dianne", "DB", 0, "Shanahan" },
                    { 440, 67, "Priscilla_Grant46@gmail.com", "Priscilla", "DB", 0, "Grant" },
                    { 441, 75, "Cristina.Witting@hotmail.com", "Cristina", "DB", 1, "Witting" },
                    { 442, 21, "Cora.Prohaska81@hotmail.com", "Cora", "DB", 1, "Prohaska" },
                    { 443, 81, "Jimmy.Weimann@gmail.com", "Jimmy", "DB", 1, "Weimann" },
                    { 444, 13, "Harold.Nikolaus47@gmail.com", "Harold", "DB", 0, "Nikolaus" },
                    { 445, 88, "Sandra62@gmail.com", "Sandra", "DB", 1, "Roberts" },
                    { 446, 73, "Earnest.Mitchell72@hotmail.com", "Earnest", "DB", 0, "Mitchell" },
                    { 447, 12, "Daryl_Ritchie62@hotmail.com", "Daryl", "DB", 0, "Ritchie" },
                    { 448, 21, "Alison_Dooley92@yahoo.com", "Alison", "DB", 1, "Dooley" },
                    { 449, 9, "Josefina88@gmail.com", "Josefina", "DB", 0, "Fadel" },
                    { 450, 78, "Frances17@gmail.com", "Frances", "DB", 0, "Schowalter" },
                    { 451, 47, "Sophia19@gmail.com", "Sophia", "DB", 0, "Hansen" },
                    { 452, 85, "Rebecca60@hotmail.com", "Rebecca", "DB", 1, "Gleason" },
                    { 453, 10, "Dallas_Stracke@hotmail.com", "Dallas", "DB", 0, "Stracke" },
                    { 454, 88, "Pat.Rolfson2@yahoo.com", "Pat", "DB", 0, "Rolfson" },
                    { 455, 61, "Mario_Luettgen@yahoo.com", "Mario", "DB", 0, "Luettgen" },
                    { 456, 19, "Winifred_Pouros84@hotmail.com", "Winifred", "DB", 0, "Pouros" },
                    { 457, 11, "Doreen_Yost43@hotmail.com", "Doreen", "DB", 1, "Yost" },
                    { 458, 24, "Melody_Koelpin73@gmail.com", "Melody", "DB", 1, "Koelpin" },
                    { 459, 40, "Melba_Goldner@yahoo.com", "Melba", "DB", 1, "Goldner" },
                    { 460, 27, "Corey.Kuhn38@yahoo.com", "Corey", "DB", 0, "Kuhn" },
                    { 461, 84, "Betty58@yahoo.com", "Betty", "DB", 0, "Ruecker" },
                    { 462, 39, "Toni_OKon35@hotmail.com", "Toni", "DB", 1, "O'Kon" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 463, 32, "Robert70@hotmail.com", "Robert", "DB", 0, "Jacobs" },
                    { 464, 36, "Nelson.DAmore57@gmail.com", "Nelson", "DB", 0, "D'Amore" },
                    { 465, 27, "Craig51@yahoo.com", "Craig", "DB", 1, "Hamill" },
                    { 466, 44, "Kristy.Towne5@hotmail.com", "Kristy", "DB", 1, "Towne" },
                    { 467, 19, "Kristin4@hotmail.com", "Kristin", "DB", 0, "Stamm" },
                    { 468, 49, "Andrea79@gmail.com", "Andrea", "DB", 0, "Murazik" },
                    { 469, 25, "Lula60@gmail.com", "Lula", "DB", 0, "Langosh" },
                    { 470, 44, "Toby.Blanda73@hotmail.com", "Toby", "DB", 0, "Blanda" },
                    { 471, 71, "Marvin76@gmail.com", "Marvin", "DB", 0, "Connelly" },
                    { 472, 66, "Terence_Connelly84@hotmail.com", "Terence", "DB", 0, "Connelly" },
                    { 473, 55, "Moses_West19@yahoo.com", "Moses", "DB", 0, "West" },
                    { 474, 11, "Aubrey62@yahoo.com", "Aubrey", "DB", 1, "Veum" },
                    { 475, 33, "Malcolm.Gulgowski@yahoo.com", "Malcolm", "DB", 0, "Gulgowski" },
                    { 476, 75, "Sonia.Huel@gmail.com", "Sonia", "DB", 0, "Huel" },
                    { 477, 75, "Jenna.Weissnat40@gmail.com", "Jenna", "DB", 1, "Weissnat" },
                    { 478, 45, "Glenda43@gmail.com", "Glenda", "DB", 1, "Labadie" },
                    { 479, 20, "Isaac40@gmail.com", "Isaac", "DB", 1, "Waters" },
                    { 480, 31, "Patty91@hotmail.com", "Patty", "DB", 0, "Hagenes" },
                    { 481, 8, "Charles0@gmail.com", "Charles", "DB", 1, "Runte" },
                    { 482, 13, "Thelma97@yahoo.com", "Thelma", "DB", 1, "Luettgen" },
                    { 483, 67, "Opal90@hotmail.com", "Opal", "DB", 0, "Thompson" },
                    { 484, 54, "Lori87@hotmail.com", "Lori", "DB", 1, "Farrell" },
                    { 485, 31, "Mario61@gmail.com", "Mario", "DB", 1, "Wuckert" },
                    { 486, 55, "Peggy28@yahoo.com", "Peggy", "DB", 1, "Frami" },
                    { 487, 41, "Corey_Pouros61@gmail.com", "Corey", "DB", 0, "Pouros" },
                    { 488, 73, "Kelley.Berge@gmail.com", "Kelley", "DB", 0, "Berge" },
                    { 489, 54, "Casey.Luettgen@hotmail.com", "Casey", "DB", 1, "Luettgen" },
                    { 490, 53, "Leland_Keebler75@hotmail.com", "Leland", "DB", 0, "Keebler" },
                    { 491, 60, "Irving_Walter@yahoo.com", "Irving", "DB", 0, "Walter" },
                    { 492, 31, "Jack_Little14@yahoo.com", "Jack", "DB", 0, "Little" },
                    { 493, 44, "Angie.Conn@yahoo.com", "Angie", "DB", 1, "Conn" },
                    { 494, 49, "Kayla99@gmail.com", "Kayla", "DB", 1, "Schmitt" },
                    { 495, 40, "Tabitha_Becker53@gmail.com", "Tabitha", "DB", 0, "Becker" },
                    { 496, 71, "Sara_Kihn83@hotmail.com", "Sara", "DB", 1, "Kihn" },
                    { 497, 12, "Ora14@hotmail.com", "Ora", "DB", 0, "Fadel" },
                    { 498, 76, "Lee.Kilback43@yahoo.com", "Lee", "DB", 1, "Kilback" },
                    { 499, 68, "Miriam.Stracke@gmail.com", "Miriam", "DB", 0, "Stracke" },
                    { 500, 30, "Alexis_Kilback@yahoo.com", "Alexis", "DB", 0, "Kilback" },
                    { 501, 46, "Mabel44@hotmail.com", "Mabel", "DB", 0, "Maggio" },
                    { 502, 86, "Kenny_Will59@hotmail.com", "Kenny", "DB", 0, "Will" },
                    { 503, 70, "Willis_Rowe@gmail.com", "Willis", "DB", 0, "Rowe" },
                    { 504, 86, "Reginald26@gmail.com", "Reginald", "DB", 0, "Haag" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 505, 66, "Van_Wiegand51@hotmail.com", "Van", "DB", 1, "Wiegand" },
                    { 506, 52, "Veronica.Wiza88@yahoo.com", "Veronica", "DB", 1, "Wiza" },
                    { 507, 26, "Kayla36@yahoo.com", "Kayla", "DB", 1, "Barton" },
                    { 508, 9, "Cathy.Effertz47@hotmail.com", "Cathy", "DB", 0, "Effertz" },
                    { 509, 24, "Phillip.Sipes@gmail.com", "Phillip", "DB", 0, "Sipes" },
                    { 510, 58, "Ernest_Ortiz@yahoo.com", "Ernest", "DB", 0, "Ortiz" },
                    { 511, 22, "Guy.Cremin@hotmail.com", "Guy", "DB", 0, "Cremin" },
                    { 512, 34, "Marian.Leuschke@hotmail.com", "Marian", "DB", 1, "Leuschke" },
                    { 513, 59, "Velma.Russel20@gmail.com", "Velma", "DB", 0, "Russel" },
                    { 514, 45, "Nettie.Hintz69@yahoo.com", "Nettie", "DB", 1, "Hintz" },
                    { 515, 37, "Pete_Rempel62@yahoo.com", "Pete", "DB", 0, "Rempel" },
                    { 516, 71, "Woodrow.Rosenbaum@hotmail.com", "Woodrow", "DB", 0, "Rosenbaum" },
                    { 517, 49, "Santiago87@hotmail.com", "Santiago", "DB", 0, "Lang" },
                    { 518, 47, "Bob90@gmail.com", "Bob", "DB", 0, "Beatty" },
                    { 519, 83, "Blanche_Graham37@yahoo.com", "Blanche", "DB", 1, "Graham" },
                    { 520, 51, "Naomi.Treutel49@hotmail.com", "Naomi", "DB", 0, "Treutel" },
                    { 521, 28, "Wilma_Hayes@hotmail.com", "Wilma", "DB", 1, "Hayes" },
                    { 522, 86, "Sophia47@hotmail.com", "Sophia", "DB", 1, "VonRueden" },
                    { 523, 90, "Jeff.Goldner93@hotmail.com", "Jeff", "DB", 0, "Goldner" },
                    { 524, 88, "Rickey73@yahoo.com", "Rickey", "DB", 1, "Grimes" },
                    { 525, 56, "Ron67@hotmail.com", "Ron", "DB", 1, "Murray" },
                    { 526, 25, "Carolyn81@yahoo.com", "Carolyn", "DB", 1, "Stokes" },
                    { 527, 61, "Melanie_Hessel40@gmail.com", "Melanie", "DB", 1, "Hessel" },
                    { 528, 14, "Donnie.Hermann@yahoo.com", "Donnie", "DB", 1, "Hermann" },
                    { 529, 43, "Brian_Thompson@hotmail.com", "Brian", "DB", 1, "Thompson" },
                    { 530, 57, "Conrad.Dooley26@gmail.com", "Conrad", "DB", 1, "Dooley" },
                    { 531, 75, "Christian16@yahoo.com", "Christian", "DB", 1, "Kunde" },
                    { 532, 22, "Raul59@gmail.com", "Raul", "DB", 0, "Crist" },
                    { 533, 17, "Henrietta4@gmail.com", "Henrietta", "DB", 0, "Dooley" },
                    { 534, 87, "Gayle.Hermann@gmail.com", "Gayle", "DB", 0, "Hermann" },
                    { 535, 27, "Rick_Simonis58@hotmail.com", "Rick", "DB", 1, "Simonis" },
                    { 536, 59, "Jodi_Casper58@gmail.com", "Jodi", "DB", 0, "Casper" },
                    { 537, 8, "Marlon22@hotmail.com", "Marlon", "DB", 0, "Rice" },
                    { 538, 69, "Marjorie_Marvin@yahoo.com", "Marjorie", "DB", 1, "Marvin" },
                    { 539, 42, "Eric27@gmail.com", "Eric", "DB", 1, "Haag" },
                    { 540, 38, "Antonio_Sporer@gmail.com", "Antonio", "DB", 1, "Sporer" },
                    { 541, 74, "Mack_Hayes45@hotmail.com", "Mack", "DB", 0, "Hayes" },
                    { 542, 41, "Florence.Larson95@yahoo.com", "Florence", "DB", 0, "Larson" },
                    { 543, 48, "Lori56@hotmail.com", "Lori", "DB", 0, "Fay" },
                    { 544, 51, "Lena93@gmail.com", "Lena", "DB", 1, "Turner" },
                    { 545, 42, "Claude_Rempel@hotmail.com", "Claude", "DB", 1, "Rempel" },
                    { 546, 18, "Sabrina8@gmail.com", "Sabrina", "DB", 0, "Auer" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 547, 8, "Maxine.Kuhn@gmail.com", "Maxine", "DB", 1, "Kuhn" },
                    { 548, 71, "Juan.Rempel8@gmail.com", "Juan", "DB", 1, "Rempel" },
                    { 549, 19, "Darrel77@yahoo.com", "Darrel", "DB", 0, "Kihn" },
                    { 550, 57, "Sherry10@hotmail.com", "Sherry", "DB", 1, "Franecki" },
                    { 551, 65, "Kelly84@yahoo.com", "Kelly", "DB", 1, "Witting" },
                    { 552, 62, "Scott.Howe71@yahoo.com", "Scott", "DB", 1, "Howe" },
                    { 553, 64, "Emily.Treutel@gmail.com", "Emily", "DB", 1, "Treutel" },
                    { 554, 14, "Freddie9@gmail.com", "Freddie", "DB", 1, "Marvin" },
                    { 555, 21, "Rodolfo8@yahoo.com", "Rodolfo", "DB", 1, "Kiehn" },
                    { 556, 53, "Holly.Johnson82@hotmail.com", "Holly", "DB", 1, "Johnson" },
                    { 557, 17, "Wesley_Bechtelar51@gmail.com", "Wesley", "DB", 0, "Bechtelar" },
                    { 558, 33, "Stephen.Kulas@yahoo.com", "Stephen", "DB", 0, "Kulas" },
                    { 559, 41, "Greg_Barrows@yahoo.com", "Greg", "DB", 0, "Barrows" },
                    { 560, 52, "Diane12@hotmail.com", "Diane", "DB", 1, "Keeling" },
                    { 561, 72, "Lester8@yahoo.com", "Lester", "DB", 0, "Hessel" },
                    { 562, 76, "Jennie5@yahoo.com", "Jennie", "DB", 0, "Carter" },
                    { 563, 50, "Lillian_Ziemann@gmail.com", "Lillian", "DB", 0, "Ziemann" },
                    { 564, 57, "Essie77@gmail.com", "Essie", "DB", 1, "Volkman" },
                    { 565, 21, "Rodolfo_Williamson@gmail.com", "Rodolfo", "DB", 1, "Williamson" },
                    { 566, 12, "Floyd53@yahoo.com", "Floyd", "DB", 0, "Kertzmann" },
                    { 567, 17, "Judy40@hotmail.com", "Judy", "DB", 1, "Heathcote" },
                    { 568, 34, "Helen80@yahoo.com", "Helen", "DB", 0, "Bergstrom" },
                    { 569, 79, "Greg86@yahoo.com", "Greg", "DB", 1, "Wilkinson" },
                    { 570, 73, "Courtney32@hotmail.com", "Courtney", "DB", 0, "Parker" },
                    { 571, 71, "Vicky.Rempel29@gmail.com", "Vicky", "DB", 0, "Rempel" },
                    { 572, 58, "Faith26@gmail.com", "Faith", "DB", 1, "Runolfsson" },
                    { 573, 29, "Susan_McGlynn60@yahoo.com", "Susan", "DB", 1, "McGlynn" },
                    { 574, 80, "Blake85@gmail.com", "Blake", "DB", 0, "Will" },
                    { 575, 74, "Nina98@hotmail.com", "Nina", "DB", 0, "Smitham" },
                    { 576, 63, "Brendan.Padberg21@gmail.com", "Brendan", "DB", 1, "Padberg" },
                    { 577, 50, "Donald62@gmail.com", "Donald", "DB", 0, "Barrows" },
                    { 578, 43, "Billie.Kilback79@hotmail.com", "Billie", "DB", 1, "Kilback" },
                    { 579, 52, "Darin.Schowalter40@gmail.com", "Darin", "DB", 1, "Schowalter" },
                    { 580, 30, "Kerry.Murphy70@gmail.com", "Kerry", "DB", 0, "Murphy" },
                    { 581, 66, "Jerry_Langworth70@yahoo.com", "Jerry", "DB", 1, "Langworth" },
                    { 582, 37, "Jack_Olson@hotmail.com", "Jack", "DB", 1, "Olson" },
                    { 583, 60, "Leroy17@yahoo.com", "Leroy", "DB", 1, "Witting" },
                    { 584, 84, "Victoria6@yahoo.com", "Victoria", "DB", 1, "Kuphal" },
                    { 585, 24, "Lillian.Gusikowski@gmail.com", "Lillian", "DB", 0, "Gusikowski" },
                    { 586, 18, "Leroy10@gmail.com", "Leroy", "DB", 1, "Schuster" },
                    { 587, 8, "Adrian_Rutherford79@yahoo.com", "Adrian", "DB", 0, "Rutherford" },
                    { 588, 66, "Orlando.Beatty@gmail.com", "Orlando", "DB", 1, "Beatty" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 589, 77, "Blanca_Smith@gmail.com", "Blanca", "DB", 1, "Smith" },
                    { 590, 13, "Sharon_Hoppe36@yahoo.com", "Sharon", "DB", 0, "Hoppe" },
                    { 591, 31, "Chelsea.McLaughlin25@hotmail.com", "Chelsea", "DB", 1, "McLaughlin" },
                    { 592, 51, "Erica.Pfannerstill49@hotmail.com", "Erica", "DB", 0, "Pfannerstill" },
                    { 593, 77, "Vicki_Ryan@gmail.com", "Vicki", "DB", 1, "Ryan" },
                    { 594, 14, "Courtney.Spinka76@hotmail.com", "Courtney", "DB", 0, "Spinka" },
                    { 595, 79, "Jeremiah_Mante23@gmail.com", "Jeremiah", "DB", 0, "Mante" },
                    { 596, 49, "Aaron.Bauch35@gmail.com", "Aaron", "DB", 1, "Bauch" },
                    { 597, 31, "Moses_MacGyver6@hotmail.com", "Moses", "DB", 1, "MacGyver" },
                    { 598, 85, "Grace75@yahoo.com", "Grace", "DB", 1, "Nikolaus" },
                    { 599, 10, "Nick.Greenholt60@hotmail.com", "Nick", "DB", 1, "Greenholt" },
                    { 600, 27, "Lucas67@yahoo.com", "Lucas", "DB", 1, "Deckow" },
                    { 601, 21, "Wm.Hoppe43@hotmail.com", "Wm", "DB", 1, "Hoppe" },
                    { 602, 18, "Lora52@hotmail.com", "Lora", "DB", 1, "Gutmann" },
                    { 603, 73, "Frederick.Rogahn@yahoo.com", "Frederick", "DB", 0, "Rogahn" },
                    { 604, 80, "Leslie.Hansen@hotmail.com", "Leslie", "DB", 1, "Hansen" },
                    { 605, 54, "Sarah2@yahoo.com", "Sarah", "DB", 0, "Parisian" },
                    { 606, 66, "Claudia_Emmerich@yahoo.com", "Claudia", "DB", 0, "Emmerich" },
                    { 607, 33, "Raul_Keebler@hotmail.com", "Raul", "DB", 1, "Keebler" },
                    { 608, 39, "Jeannette.Gleichner87@hotmail.com", "Jeannette", "DB", 1, "Gleichner" },
                    { 609, 40, "Lamar17@hotmail.com", "Lamar", "DB", 1, "Gutkowski" },
                    { 610, 31, "Gerard_Lockman@hotmail.com", "Gerard", "DB", 1, "Lockman" },
                    { 611, 68, "Anna36@hotmail.com", "Anna", "DB", 1, "Smitham" },
                    { 612, 29, "Dorothy_Runolfsson@gmail.com", "Dorothy", "DB", 1, "Runolfsson" },
                    { 613, 35, "Howard_Casper90@gmail.com", "Howard", "DB", 0, "Casper" },
                    { 614, 81, "Dwayne_Lueilwitz@hotmail.com", "Dwayne", "DB", 1, "Lueilwitz" },
                    { 615, 70, "Donna_Collins@yahoo.com", "Donna", "DB", 0, "Collins" },
                    { 616, 36, "Devin.Ondricka60@hotmail.com", "Devin", "DB", 0, "Ondricka" },
                    { 617, 76, "Andrea34@yahoo.com", "Andrea", "DB", 1, "Veum" },
                    { 618, 81, "Cecelia_Sporer1@yahoo.com", "Cecelia", "DB", 0, "Sporer" },
                    { 619, 44, "Gerald.Boehm35@yahoo.com", "Gerald", "DB", 1, "Boehm" },
                    { 620, 15, "Calvin90@gmail.com", "Calvin", "DB", 0, "Cummerata" },
                    { 621, 33, "Ross.Hickle@hotmail.com", "Ross", "DB", 1, "Hickle" },
                    { 622, 26, "Roger_Jones@yahoo.com", "Roger", "DB", 1, "Jones" },
                    { 623, 32, "Jody.Kemmer95@yahoo.com", "Jody", "DB", 1, "Kemmer" },
                    { 624, 60, "Earl_Spencer@gmail.com", "Earl", "DB", 1, "Spencer" },
                    { 625, 67, "Diana_Haley8@yahoo.com", "Diana", "DB", 0, "Haley" },
                    { 626, 70, "Dewey.Mann@gmail.com", "Dewey", "DB", 1, "Mann" },
                    { 627, 51, "Randall71@yahoo.com", "Randall", "DB", 1, "Lynch" },
                    { 628, 87, "Laverne52@hotmail.com", "Laverne", "DB", 0, "Von" },
                    { 629, 58, "Kathy.Barrows0@hotmail.com", "Kathy", "DB", 1, "Barrows" },
                    { 630, 57, "Jody51@hotmail.com", "Jody", "DB", 0, "Daugherty" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 631, 63, "Jorge.Hyatt@hotmail.com", "Jorge", "DB", 0, "Hyatt" },
                    { 632, 69, "Pauline2@hotmail.com", "Pauline", "DB", 1, "Fisher" },
                    { 633, 27, "Jesus.Armstrong@yahoo.com", "Jesus", "DB", 1, "Armstrong" },
                    { 634, 21, "Vicki.Windler@yahoo.com", "Vicki", "DB", 0, "Windler" },
                    { 635, 36, "Forrest10@hotmail.com", "Forrest", "DB", 0, "Cummerata" },
                    { 636, 13, "Jeannie14@yahoo.com", "Jeannie", "DB", 0, "Rosenbaum" },
                    { 637, 30, "Jody59@hotmail.com", "Jody", "DB", 1, "Thiel" },
                    { 638, 33, "Lillie.Hegmann30@hotmail.com", "Lillie", "DB", 1, "Hegmann" },
                    { 639, 83, "Israel.Sauer64@hotmail.com", "Israel", "DB", 1, "Sauer" },
                    { 640, 58, "Saul87@gmail.com", "Saul", "DB", 0, "Jones" },
                    { 641, 39, "Jennie.Goldner3@hotmail.com", "Jennie", "DB", 0, "Goldner" },
                    { 642, 15, "Glenda_Hudson47@gmail.com", "Glenda", "DB", 0, "Hudson" },
                    { 643, 21, "Christine_Lowe@gmail.com", "Christine", "DB", 1, "Lowe" },
                    { 644, 53, "Pat_Sawayn@hotmail.com", "Pat", "DB", 0, "Sawayn" },
                    { 645, 61, "Betsy_Rolfson@hotmail.com", "Betsy", "DB", 0, "Rolfson" },
                    { 646, 61, "Lila.Huel32@gmail.com", "Lila", "DB", 1, "Huel" },
                    { 647, 61, "Joseph.Cronin14@hotmail.com", "Joseph", "DB", 1, "Cronin" },
                    { 648, 55, "Joy_Morar@hotmail.com", "Joy", "DB", 1, "Morar" },
                    { 649, 24, "Martin58@yahoo.com", "Martin", "DB", 1, "Ortiz" },
                    { 650, 41, "Carrie.Prohaska@hotmail.com", "Carrie", "DB", 1, "Prohaska" },
                    { 651, 84, "Gretchen36@gmail.com", "Gretchen", "DB", 0, "Zulauf" },
                    { 652, 17, "Carlos.Lind@yahoo.com", "Carlos", "DB", 0, "Lind" },
                    { 653, 18, "Rodolfo49@yahoo.com", "Rodolfo", "DB", 0, "Aufderhar" },
                    { 654, 90, "Jesse19@hotmail.com", "Jesse", "DB", 0, "Torphy" },
                    { 655, 42, "Rufus7@gmail.com", "Rufus", "DB", 1, "Casper" },
                    { 656, 32, "Irma_Ankunding75@hotmail.com", "Irma", "DB", 0, "Ankunding" },
                    { 657, 31, "Wilbert.Boehm@hotmail.com", "Wilbert", "DB", 0, "Boehm" },
                    { 658, 24, "Billy21@yahoo.com", "Billy", "DB", 0, "Halvorson" },
                    { 659, 79, "Dustin.Beer@yahoo.com", "Dustin", "DB", 0, "Beer" },
                    { 660, 50, "Jack.Kuhic@yahoo.com", "Jack", "DB", 0, "Kuhic" },
                    { 661, 61, "Linda_Bosco82@gmail.com", "Linda", "DB", 0, "Bosco" },
                    { 662, 27, "Rebecca4@yahoo.com", "Rebecca", "DB", 0, "Huels" },
                    { 663, 35, "Lloyd_Hodkiewicz@gmail.com", "Lloyd", "DB", 0, "Hodkiewicz" },
                    { 664, 80, "Wallace43@hotmail.com", "Wallace", "DB", 0, "Glover" },
                    { 665, 56, "Daisy.Walsh@yahoo.com", "Daisy", "DB", 0, "Walsh" },
                    { 666, 59, "Heidi.Kassulke@hotmail.com", "Heidi", "DB", 0, "Kassulke" },
                    { 667, 68, "Mandy_Conroy96@yahoo.com", "Mandy", "DB", 1, "Conroy" },
                    { 668, 8, "Virginia24@gmail.com", "Virginia", "DB", 1, "Medhurst" },
                    { 669, 48, "Claire.Sauer@gmail.com", "Claire", "DB", 0, "Sauer" },
                    { 670, 43, "Johnnie.Kerluke@hotmail.com", "Johnnie", "DB", 0, "Kerluke" },
                    { 671, 65, "Fred.Wolff@gmail.com", "Fred", "DB", 0, "Wolff" },
                    { 672, 40, "Tabitha.Stroman12@yahoo.com", "Tabitha", "DB", 0, "Stroman" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 673, 20, "Ruben.Murray83@gmail.com", "Ruben", "DB", 0, "Murray" },
                    { 674, 31, "Clark.Simonis@hotmail.com", "Clark", "DB", 1, "Simonis" },
                    { 675, 45, "Penny13@yahoo.com", "Penny", "DB", 0, "Harvey" },
                    { 676, 73, "Russell_Thompson@hotmail.com", "Russell", "DB", 1, "Thompson" },
                    { 677, 44, "Cindy11@yahoo.com", "Cindy", "DB", 1, "Nolan" },
                    { 678, 14, "Kelley47@yahoo.com", "Kelley", "DB", 0, "Schamberger" },
                    { 679, 42, "Kent46@gmail.com", "Kent", "DB", 1, "Mraz" },
                    { 680, 56, "Andres.Grady67@gmail.com", "Andres", "DB", 1, "Grady" },
                    { 681, 18, "Roxanne.Corkery64@hotmail.com", "Roxanne", "DB", 0, "Corkery" },
                    { 682, 77, "Gabriel_Leffler@gmail.com", "Gabriel", "DB", 0, "Leffler" },
                    { 683, 21, "Gregory.Glover@yahoo.com", "Gregory", "DB", 0, "Glover" },
                    { 684, 75, "Bert66@gmail.com", "Bert", "DB", 0, "Becker" },
                    { 685, 89, "Ben_Batz41@gmail.com", "Ben", "DB", 0, "Batz" },
                    { 686, 25, "Rudolph_McCullough77@hotmail.com", "Rudolph", "DB", 0, "McCullough" },
                    { 687, 59, "Hope9@hotmail.com", "Hope", "DB", 1, "Maggio" },
                    { 688, 70, "Elizabeth.Upton@gmail.com", "Elizabeth", "DB", 1, "Upton" },
                    { 689, 41, "Monica_Wehner63@hotmail.com", "Monica", "DB", 1, "Wehner" },
                    { 690, 43, "Ann_Watsica@hotmail.com", "Ann", "DB", 0, "Watsica" },
                    { 691, 29, "Bridget58@yahoo.com", "Bridget", "DB", 1, "Fay" },
                    { 692, 55, "Marta_Bruen@gmail.com", "Marta", "DB", 0, "Bruen" },
                    { 693, 18, "Doug.OConnell11@hotmail.com", "Doug", "DB", 0, "O'Connell" },
                    { 694, 80, "Jenna.Bauch@gmail.com", "Jenna", "DB", 1, "Bauch" },
                    { 695, 66, "Roxanne_McKenzie78@yahoo.com", "Roxanne", "DB", 1, "McKenzie" },
                    { 696, 9, "Earnest4@yahoo.com", "Earnest", "DB", 1, "Satterfield" },
                    { 697, 81, "Lela.McGlynn18@hotmail.com", "Lela", "DB", 1, "McGlynn" },
                    { 698, 14, "Douglas_Boyle@yahoo.com", "Douglas", "DB", 0, "Boyle" },
                    { 699, 57, "Myra_Rempel@yahoo.com", "Myra", "DB", 1, "Rempel" },
                    { 700, 55, "Timmy66@hotmail.com", "Timmy", "DB", 0, "Reichert" },
                    { 701, 14, "Kristopher_Kuhn@hotmail.com", "Kristopher", "DB", 1, "Kuhn" },
                    { 702, 44, "Bobby18@yahoo.com", "Bobby", "DB", 1, "Goyette" },
                    { 703, 74, "Billy_Bartell@hotmail.com", "Billy", "DB", 1, "Bartell" },
                    { 704, 43, "Lester.Ward53@hotmail.com", "Lester", "DB", 0, "Ward" },
                    { 705, 64, "Randal_Schmidt@gmail.com", "Randal", "DB", 1, "Schmidt" },
                    { 706, 31, "Holly49@hotmail.com", "Holly", "DB", 1, "Nikolaus" },
                    { 707, 16, "Willie.Kovacek57@gmail.com", "Willie", "DB", 0, "Kovacek" },
                    { 708, 44, "Ira.Stark32@gmail.com", "Ira", "DB", 0, "Stark" },
                    { 709, 21, "Eloise.Lesch@yahoo.com", "Eloise", "DB", 0, "Lesch" },
                    { 710, 87, "Stephanie_Hane47@gmail.com", "Stephanie", "DB", 1, "Hane" },
                    { 711, 13, "Cedric97@yahoo.com", "Cedric", "DB", 0, "Vandervort" },
                    { 712, 74, "Evan.Bernier@hotmail.com", "Evan", "DB", 1, "Bernier" },
                    { 713, 47, "Christopher65@gmail.com", "Christopher", "DB", 0, "Harber" },
                    { 714, 40, "Sherman_Walsh44@yahoo.com", "Sherman", "DB", 0, "Walsh" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 715, 54, "Lee.Hickle79@yahoo.com", "Lee", "DB", 0, "Hickle" },
                    { 716, 19, "Alonzo_Moore@hotmail.com", "Alonzo", "DB", 0, "Moore" },
                    { 717, 50, "Renee_Treutel@gmail.com", "Renee", "DB", 1, "Treutel" },
                    { 718, 20, "Elena_Gutkowski@yahoo.com", "Elena", "DB", 1, "Gutkowski" },
                    { 719, 20, "Forrest91@yahoo.com", "Forrest", "DB", 1, "Schultz" },
                    { 720, 9, "Erick.Mitchell@yahoo.com", "Erick", "DB", 1, "Mitchell" },
                    { 721, 72, "Helen_Hilll11@hotmail.com", "Helen", "DB", 0, "Hilll" },
                    { 722, 74, "Opal_Boyer11@yahoo.com", "Opal", "DB", 1, "Boyer" },
                    { 723, 66, "Marilyn.Kilback19@gmail.com", "Marilyn", "DB", 0, "Kilback" },
                    { 724, 61, "Jackie.Rice@gmail.com", "Jackie", "DB", 1, "Rice" },
                    { 725, 67, "Jared_Champlin15@hotmail.com", "Jared", "DB", 0, "Champlin" },
                    { 726, 23, "Micheal.Daniel73@hotmail.com", "Micheal", "DB", 0, "Daniel" },
                    { 727, 42, "Hattie_Green54@gmail.com", "Hattie", "DB", 1, "Green" },
                    { 728, 39, "Neil22@gmail.com", "Neil", "DB", 1, "Zemlak" },
                    { 729, 64, "Milton_Mayert88@yahoo.com", "Milton", "DB", 0, "Mayert" },
                    { 730, 38, "Roberto_Hahn81@gmail.com", "Roberto", "DB", 1, "Hahn" },
                    { 731, 75, "Raul1@yahoo.com", "Raul", "DB", 0, "Schiller" },
                    { 732, 62, "Nettie_Green61@hotmail.com", "Nettie", "DB", 0, "Green" },
                    { 733, 20, "Maxine.Kulas@hotmail.com", "Maxine", "DB", 1, "Kulas" },
                    { 734, 88, "Neil.Koch@yahoo.com", "Neil", "DB", 0, "Koch" },
                    { 735, 83, "Bennie41@gmail.com", "Bennie", "DB", 1, "Leffler" },
                    { 736, 55, "Geoffrey.McLaughlin39@yahoo.com", "Geoffrey", "DB", 1, "McLaughlin" },
                    { 737, 14, "Leah10@hotmail.com", "Leah", "DB", 0, "Nader" },
                    { 738, 26, "Frederick_Lind@gmail.com", "Frederick", "DB", 1, "Lind" },
                    { 739, 20, "Freda_Anderson@hotmail.com", "Freda", "DB", 0, "Anderson" },
                    { 740, 10, "Ervin.Nicolas68@hotmail.com", "Ervin", "DB", 1, "Nicolas" },
                    { 741, 81, "Eddie.Gleichner66@hotmail.com", "Eddie", "DB", 0, "Gleichner" },
                    { 742, 65, "Edmond.Bruen@hotmail.com", "Edmond", "DB", 0, "Bruen" },
                    { 743, 54, "Susan7@hotmail.com", "Susan", "DB", 1, "O'Connell" },
                    { 744, 57, "Clark.Metz28@yahoo.com", "Clark", "DB", 1, "Metz" },
                    { 745, 42, "Wilbur.Koch26@gmail.com", "Wilbur", "DB", 0, "Koch" },
                    { 746, 85, "Kerry.Reynolds@gmail.com", "Kerry", "DB", 1, "Reynolds" },
                    { 747, 29, "Herman_Cartwright@gmail.com", "Herman", "DB", 1, "Cartwright" },
                    { 748, 35, "Duane_Dietrich@gmail.com", "Duane", "DB", 1, "Dietrich" },
                    { 749, 24, "Ray_Walter68@yahoo.com", "Ray", "DB", 1, "Walter" },
                    { 750, 46, "Catherine_Macejkovic@hotmail.com", "Catherine", "DB", 1, "Macejkovic" },
                    { 751, 55, "Jasmine.Strosin26@gmail.com", "Jasmine", "DB", 1, "Strosin" },
                    { 752, 62, "Santiago.DAmore39@hotmail.com", "Santiago", "DB", 0, "D'Amore" },
                    { 753, 47, "Nathan_Huels@hotmail.com", "Nathan", "DB", 1, "Huels" },
                    { 754, 45, "Meredith_Will@hotmail.com", "Meredith", "DB", 0, "Will" },
                    { 755, 48, "Kevin_Larkin47@yahoo.com", "Kevin", "DB", 1, "Larkin" },
                    { 756, 46, "Elena_Carter@yahoo.com", "Elena", "DB", 0, "Carter" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 757, 21, "Mabel.Braun@yahoo.com", "Mabel", "DB", 1, "Braun" },
                    { 758, 8, "Pam2@hotmail.com", "Pam", "DB", 1, "Borer" },
                    { 759, 49, "Eddie.Balistreri91@yahoo.com", "Eddie", "DB", 1, "Balistreri" },
                    { 760, 46, "Joan5@hotmail.com", "Joan", "DB", 0, "Kuvalis" },
                    { 761, 57, "Lonnie_Jaskolski@hotmail.com", "Lonnie", "DB", 1, "Jaskolski" },
                    { 762, 89, "Krista22@hotmail.com", "Krista", "DB", 1, "Frami" },
                    { 763, 65, "Grace65@yahoo.com", "Grace", "DB", 0, "Yundt" },
                    { 764, 88, "Geoffrey_Berge19@yahoo.com", "Geoffrey", "DB", 0, "Berge" },
                    { 765, 38, "Gerard.Hane@hotmail.com", "Gerard", "DB", 0, "Hane" },
                    { 766, 60, "Zachary_Schuster@gmail.com", "Zachary", "DB", 0, "Schuster" },
                    { 767, 41, "Arturo_Becker@gmail.com", "Arturo", "DB", 0, "Becker" },
                    { 768, 35, "Rene48@hotmail.com", "Rene", "DB", 1, "Kessler" },
                    { 769, 50, "Rufus_Gusikowski22@hotmail.com", "Rufus", "DB", 1, "Gusikowski" },
                    { 770, 31, "Sylvia57@hotmail.com", "Sylvia", "DB", 0, "Barton" },
                    { 771, 41, "Marguerite_Kertzmann@gmail.com", "Marguerite", "DB", 1, "Kertzmann" },
                    { 772, 17, "Delbert_Blick@yahoo.com", "Delbert", "DB", 0, "Blick" },
                    { 773, 24, "Kristie.Smith34@hotmail.com", "Kristie", "DB", 1, "Smith" },
                    { 774, 86, "Catherine.Oberbrunner36@hotmail.com", "Catherine", "DB", 0, "Oberbrunner" },
                    { 775, 88, "Sally.Baumbach50@hotmail.com", "Sally", "DB", 0, "Baumbach" },
                    { 776, 37, "Horace37@yahoo.com", "Horace", "DB", 1, "Bernier" },
                    { 777, 24, "Dennis.Hoeger@gmail.com", "Dennis", "DB", 0, "Hoeger" },
                    { 778, 40, "Alice53@gmail.com", "Alice", "DB", 1, "Wehner" },
                    { 779, 12, "Sarah_Hermann49@gmail.com", "Sarah", "DB", 1, "Hermann" },
                    { 780, 45, "Dan_Armstrong@hotmail.com", "Dan", "DB", 0, "Armstrong" },
                    { 781, 14, "Alan.Cummings75@gmail.com", "Alan", "DB", 0, "Cummings" },
                    { 782, 83, "Darrel61@hotmail.com", "Darrel", "DB", 1, "Waelchi" },
                    { 783, 14, "Danny_Wunsch64@hotmail.com", "Danny", "DB", 1, "Wunsch" },
                    { 784, 59, "Lana_Trantow@yahoo.com", "Lana", "DB", 1, "Trantow" },
                    { 785, 75, "Grady.Cruickshank63@gmail.com", "Grady", "DB", 0, "Cruickshank" },
                    { 786, 88, "Vera_Wolf@hotmail.com", "Vera", "DB", 0, "Wolf" },
                    { 787, 73, "Frankie_Pacocha49@gmail.com", "Frankie", "DB", 0, "Pacocha" },
                    { 788, 26, "May.Shields@gmail.com", "May", "DB", 0, "Shields" },
                    { 789, 25, "Rosemary.Walsh@gmail.com", "Rosemary", "DB", 1, "Walsh" },
                    { 790, 81, "Hugh.Prosacco@hotmail.com", "Hugh", "DB", 0, "Prosacco" },
                    { 791, 31, "Mabel37@hotmail.com", "Mabel", "DB", 0, "Bednar" },
                    { 792, 21, "Ira48@gmail.com", "Ira", "DB", 1, "Hettinger" },
                    { 793, 41, "Janice.Sipes@hotmail.com", "Janice", "DB", 0, "Sipes" },
                    { 794, 87, "Irving39@gmail.com", "Irving", "DB", 1, "Tremblay" },
                    { 795, 9, "Sherman_Skiles24@gmail.com", "Sherman", "DB", 1, "Skiles" },
                    { 796, 81, "Christie38@gmail.com", "Christie", "DB", 0, "Mayer" },
                    { 797, 31, "Terry61@gmail.com", "Terry", "DB", 0, "Quigley" },
                    { 798, 62, "Micheal.Osinski94@gmail.com", "Micheal", "DB", 0, "Osinski" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 799, 68, "Bradley_Tillman28@hotmail.com", "Bradley", "DB", 0, "Tillman" },
                    { 800, 24, "Antonia.Abshire@hotmail.com", "Antonia", "DB", 0, "Abshire" },
                    { 801, 24, "Myrtle.Sauer41@yahoo.com", "Myrtle", "DB", 0, "Sauer" },
                    { 802, 46, "Tracey.Medhurst@hotmail.com", "Tracey", "DB", 1, "Medhurst" },
                    { 803, 14, "Merle.Runolfsson56@yahoo.com", "Merle", "DB", 0, "Runolfsson" },
                    { 804, 31, "Charlene_Fritsch11@yahoo.com", "Charlene", "DB", 0, "Fritsch" },
                    { 805, 65, "Ruby_Kozey@gmail.com", "Ruby", "DB", 1, "Kozey" },
                    { 806, 44, "Teresa.Robel67@yahoo.com", "Teresa", "DB", 1, "Robel" },
                    { 807, 31, "Alexander20@hotmail.com", "Alexander", "DB", 0, "Bradtke" },
                    { 808, 15, "Jaime28@gmail.com", "Jaime", "DB", 1, "Monahan" },
                    { 809, 57, "Vernon21@hotmail.com", "Vernon", "DB", 0, "O'Conner" },
                    { 810, 49, "Emmett.Abshire96@gmail.com", "Emmett", "DB", 0, "Abshire" },
                    { 811, 27, "Faith.Bosco85@yahoo.com", "Faith", "DB", 1, "Bosco" },
                    { 812, 90, "Alyssa30@gmail.com", "Alyssa", "DB", 0, "Larkin" },
                    { 813, 63, "Arnold_Conn@hotmail.com", "Arnold", "DB", 1, "Conn" },
                    { 814, 54, "Molly31@hotmail.com", "Molly", "DB", 0, "Krajcik" },
                    { 815, 76, "Sylvia73@hotmail.com", "Sylvia", "DB", 0, "Schmidt" },
                    { 816, 41, "Homer81@hotmail.com", "Homer", "DB", 0, "Walsh" },
                    { 817, 8, "Tim_Turcotte81@gmail.com", "Tim", "DB", 1, "Turcotte" },
                    { 818, 71, "Christie97@hotmail.com", "Christie", "DB", 0, "Lind" },
                    { 819, 43, "Terrell_Schaefer@gmail.com", "Terrell", "DB", 0, "Schaefer" },
                    { 820, 16, "Taylor_OHara@gmail.com", "Taylor", "DB", 0, "O'Hara" },
                    { 821, 52, "Andy94@gmail.com", "Andy", "DB", 0, "Funk" },
                    { 822, 59, "Douglas.Hickle53@gmail.com", "Douglas", "DB", 1, "Hickle" },
                    { 823, 69, "Marlon_Wunsch83@yahoo.com", "Marlon", "DB", 0, "Wunsch" },
                    { 824, 39, "Rachael_Bosco42@gmail.com", "Rachael", "DB", 0, "Bosco" },
                    { 825, 72, "Dianna_Franecki@gmail.com", "Dianna", "DB", 0, "Franecki" },
                    { 826, 75, "Kim79@gmail.com", "Kim", "DB", 1, "Dicki" },
                    { 827, 37, "Santos_Emmerich@gmail.com", "Santos", "DB", 1, "Emmerich" },
                    { 828, 16, "Salvador.Armstrong@gmail.com", "Salvador", "DB", 0, "Armstrong" },
                    { 829, 52, "Tanya.Hansen@gmail.com", "Tanya", "DB", 0, "Hansen" },
                    { 830, 36, "Willie.Hills@yahoo.com", "Willie", "DB", 1, "Hills" },
                    { 831, 56, "Gilbert_Metz@gmail.com", "Gilbert", "DB", 0, "Metz" },
                    { 832, 70, "Marcia.Bergstrom@hotmail.com", "Marcia", "DB", 0, "Bergstrom" },
                    { 833, 35, "Johanna.Mante20@yahoo.com", "Johanna", "DB", 0, "Mante" },
                    { 834, 68, "Vincent_Rohan@hotmail.com", "Vincent", "DB", 1, "Rohan" },
                    { 835, 58, "Salvador.Morar48@hotmail.com", "Salvador", "DB", 1, "Morar" },
                    { 836, 84, "Randall.Boehm63@hotmail.com", "Randall", "DB", 0, "Boehm" },
                    { 837, 45, "Jody60@gmail.com", "Jody", "DB", 0, "Grady" },
                    { 838, 37, "Israel73@gmail.com", "Israel", "DB", 1, "Gerlach" },
                    { 839, 72, "Guillermo_Zieme36@yahoo.com", "Guillermo", "DB", 1, "Zieme" },
                    { 840, 68, "Jenna_Connelly@gmail.com", "Jenna", "DB", 1, "Connelly" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 841, 85, "Roxanne.Sauer27@yahoo.com", "Roxanne", "DB", 0, "Sauer" },
                    { 842, 49, "Angel.Moore90@gmail.com", "Angel", "DB", 1, "Moore" },
                    { 843, 82, "Sergio_Wolf96@yahoo.com", "Sergio", "DB", 0, "Wolf" },
                    { 844, 75, "Edna21@hotmail.com", "Edna", "DB", 0, "Tillman" },
                    { 845, 89, "Gregory.Halvorson51@yahoo.com", "Gregory", "DB", 0, "Halvorson" },
                    { 846, 67, "Todd.Koch@hotmail.com", "Todd", "DB", 0, "Koch" },
                    { 847, 86, "Edith_Ankunding53@yahoo.com", "Edith", "DB", 1, "Ankunding" },
                    { 848, 73, "Jose12@hotmail.com", "Jose", "DB", 1, "Abbott" },
                    { 849, 35, "Lionel79@gmail.com", "Lionel", "DB", 1, "Dickinson" },
                    { 850, 38, "Jeffrey_Rohan@hotmail.com", "Jeffrey", "DB", 1, "Rohan" },
                    { 851, 50, "Donald_Little22@yahoo.com", "Donald", "DB", 0, "Little" },
                    { 852, 45, "Robert.Zulauf62@yahoo.com", "Robert", "DB", 1, "Zulauf" },
                    { 853, 37, "Monique.Heaney29@gmail.com", "Monique", "DB", 1, "Heaney" },
                    { 854, 86, "Kari26@hotmail.com", "Kari", "DB", 0, "Emard" },
                    { 855, 27, "Conrad_Larson@hotmail.com", "Conrad", "DB", 1, "Larson" },
                    { 856, 66, "Sara_Walter@yahoo.com", "Sara", "DB", 1, "Walter" },
                    { 857, 80, "Nellie98@gmail.com", "Nellie", "DB", 1, "Rath" },
                    { 858, 71, "Eunice.Beier@gmail.com", "Eunice", "DB", 1, "Beier" },
                    { 859, 83, "Joel.Lind44@yahoo.com", "Joel", "DB", 1, "Lind" },
                    { 860, 81, "Jack.Goyette19@gmail.com", "Jack", "DB", 0, "Goyette" },
                    { 861, 19, "Hope_Terry61@gmail.com", "Hope", "DB", 1, "Terry" },
                    { 862, 10, "Everett_Heathcote@yahoo.com", "Everett", "DB", 1, "Heathcote" },
                    { 863, 31, "Billie_Hermiston@hotmail.com", "Billie", "DB", 0, "Hermiston" },
                    { 864, 77, "Lucille_Kihn42@gmail.com", "Lucille", "DB", 1, "Kihn" },
                    { 865, 22, "Raquel.Bashirian@yahoo.com", "Raquel", "DB", 0, "Bashirian" },
                    { 866, 60, "Lorene_Shanahan12@hotmail.com", "Lorene", "DB", 1, "Shanahan" },
                    { 867, 88, "Darrin66@yahoo.com", "Darrin", "DB", 0, "Fritsch" },
                    { 868, 63, "Timmy.Connelly24@gmail.com", "Timmy", "DB", 0, "Connelly" },
                    { 869, 22, "Ramiro38@yahoo.com", "Ramiro", "DB", 0, "Rodriguez" },
                    { 870, 25, "Pat70@hotmail.com", "Pat", "DB", 0, "Botsford" },
                    { 871, 76, "Judith_Ullrich@gmail.com", "Judith", "DB", 1, "Ullrich" },
                    { 872, 49, "Tomas_Gleason@hotmail.com", "Tomas", "DB", 0, "Gleason" },
                    { 873, 42, "Dexter_Schoen@hotmail.com", "Dexter", "DB", 0, "Schoen" },
                    { 874, 36, "Edgar66@gmail.com", "Edgar", "DB", 0, "Quitzon" },
                    { 875, 62, "Clay_Wisoky@yahoo.com", "Clay", "DB", 0, "Wisoky" },
                    { 876, 55, "Elsie.Reilly31@yahoo.com", "Elsie", "DB", 0, "Reilly" },
                    { 877, 65, "Cynthia2@gmail.com", "Cynthia", "DB", 1, "Wintheiser" },
                    { 878, 88, "Rufus.Boehm@yahoo.com", "Rufus", "DB", 1, "Boehm" },
                    { 879, 77, "Oliver2@yahoo.com", "Oliver", "DB", 0, "Schiller" },
                    { 880, 32, "Leslie.Lynch@gmail.com", "Leslie", "DB", 0, "Lynch" },
                    { 881, 24, "Geneva_Corkery@yahoo.com", "Geneva", "DB", 1, "Corkery" },
                    { 882, 67, "Alison4@yahoo.com", "Alison", "DB", 1, "Macejkovic" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 883, 51, "Troy85@yahoo.com", "Troy", "DB", 0, "Wehner" },
                    { 884, 34, "Kathleen.Wuckert54@yahoo.com", "Kathleen", "DB", 0, "Wuckert" },
                    { 885, 38, "Ernest94@hotmail.com", "Ernest", "DB", 0, "Veum" },
                    { 886, 52, "Laurie16@gmail.com", "Laurie", "DB", 0, "Blick" },
                    { 887, 29, "Dale.Abbott@yahoo.com", "Dale", "DB", 0, "Abbott" },
                    { 888, 44, "Nicolas45@hotmail.com", "Nicolas", "DB", 1, "Bechtelar" },
                    { 889, 90, "Darryl84@hotmail.com", "Darryl", "DB", 0, "Kuhlman" },
                    { 890, 70, "Robin10@hotmail.com", "Robin", "DB", 0, "Bashirian" },
                    { 891, 12, "Ana14@gmail.com", "Ana", "DB", 0, "Hoeger" },
                    { 892, 49, "Todd7@hotmail.com", "Todd", "DB", 1, "Schneider" },
                    { 893, 76, "Nettie.Senger@yahoo.com", "Nettie", "DB", 1, "Senger" },
                    { 894, 36, "Dixie.Brakus@gmail.com", "Dixie", "DB", 0, "Brakus" },
                    { 895, 72, "Charlene_Denesik75@hotmail.com", "Charlene", "DB", 1, "Denesik" },
                    { 896, 68, "Tabitha_Murray36@gmail.com", "Tabitha", "DB", 0, "Murray" },
                    { 897, 79, "Pearl66@yahoo.com", "Pearl", "DB", 0, "White" },
                    { 898, 88, "Estelle.Schroeder@gmail.com", "Estelle", "DB", 1, "Schroeder" },
                    { 899, 41, "Maxine.Rippin@yahoo.com", "Maxine", "DB", 1, "Rippin" },
                    { 900, 70, "Caroline_McGlynn@yahoo.com", "Caroline", "DB", 1, "McGlynn" },
                    { 901, 33, "Ollie.Rempel@gmail.com", "Ollie", "DB", 1, "Rempel" },
                    { 902, 68, "Steve78@gmail.com", "Steve", "DB", 1, "Littel" },
                    { 903, 42, "Alexandra_Johnston81@yahoo.com", "Alexandra", "DB", 1, "Johnston" },
                    { 904, 60, "Sandra_Dare15@yahoo.com", "Sandra", "DB", 0, "Dare" },
                    { 905, 32, "Rosa_Graham@yahoo.com", "Rosa", "DB", 1, "Graham" },
                    { 906, 31, "Sam_Schuppe@hotmail.com", "Sam", "DB", 1, "Schuppe" },
                    { 907, 52, "Naomi.Pfeffer50@hotmail.com", "Naomi", "DB", 1, "Pfeffer" },
                    { 908, 19, "Antonio88@yahoo.com", "Antonio", "DB", 1, "Baumbach" },
                    { 909, 25, "Rebecca48@yahoo.com", "Rebecca", "DB", 0, "Baumbach" },
                    { 910, 81, "Justin.Sipes9@hotmail.com", "Justin", "DB", 1, "Sipes" },
                    { 911, 88, "Pablo94@yahoo.com", "Pablo", "DB", 0, "Friesen" },
                    { 912, 18, "Jessica28@yahoo.com", "Jessica", "DB", 1, "Vandervort" },
                    { 913, 66, "Ron30@hotmail.com", "Ron", "DB", 1, "Tromp" },
                    { 914, 15, "Hazel97@hotmail.com", "Hazel", "DB", 0, "Rogahn" },
                    { 915, 19, "Hannah36@hotmail.com", "Hannah", "DB", 1, "McCullough" },
                    { 916, 39, "Deborah_Glover40@yahoo.com", "Deborah", "DB", 1, "Glover" },
                    { 917, 67, "Delores.Keebler82@gmail.com", "Delores", "DB", 1, "Keebler" },
                    { 918, 40, "Louis_Heaney12@hotmail.com", "Louis", "DB", 0, "Heaney" },
                    { 919, 63, "Evelyn57@hotmail.com", "Evelyn", "DB", 1, "Skiles" },
                    { 920, 36, "Ira.Breitenberg@gmail.com", "Ira", "DB", 1, "Breitenberg" },
                    { 921, 73, "Homer.Hyatt43@gmail.com", "Homer", "DB", 1, "Hyatt" },
                    { 922, 16, "Orville.Wolff@hotmail.com", "Orville", "DB", 1, "Wolff" },
                    { 923, 43, "Paul_Braun@hotmail.com", "Paul", "DB", 1, "Braun" },
                    { 924, 67, "Kristen.Roob17@yahoo.com", "Kristen", "DB", 0, "Roob" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 925, 14, "Drew.Williamson@gmail.com", "Drew", "DB", 1, "Williamson" },
                    { 926, 25, "Mitchell.Nader34@yahoo.com", "Mitchell", "DB", 0, "Nader" },
                    { 927, 14, "Duane41@hotmail.com", "Duane", "DB", 1, "Harvey" },
                    { 928, 16, "Ismael36@hotmail.com", "Ismael", "DB", 0, "Kris" },
                    { 929, 56, "Vernon.Bruen30@hotmail.com", "Vernon", "DB", 0, "Bruen" },
                    { 930, 49, "Carolyn75@gmail.com", "Carolyn", "DB", 1, "Batz" },
                    { 931, 90, "Darrel.Schamberger4@hotmail.com", "Darrel", "DB", 1, "Schamberger" },
                    { 932, 81, "Larry_Torp63@gmail.com", "Larry", "DB", 1, "Torp" },
                    { 933, 57, "Hilda_Brekke10@gmail.com", "Hilda", "DB", 1, "Brekke" },
                    { 934, 33, "Opal_Berge3@yahoo.com", "Opal", "DB", 0, "Berge" },
                    { 935, 31, "Gregory37@hotmail.com", "Gregory", "DB", 0, "Harber" },
                    { 936, 12, "Frances71@yahoo.com", "Frances", "DB", 1, "Rice" },
                    { 937, 69, "Cameron81@yahoo.com", "Cameron", "DB", 0, "Cruickshank" },
                    { 938, 71, "Saul85@yahoo.com", "Saul", "DB", 1, "Klein" },
                    { 939, 83, "Robyn1@gmail.com", "Robyn", "DB", 1, "Carroll" },
                    { 940, 81, "Elisa.Stracke49@hotmail.com", "Elisa", "DB", 1, "Stracke" },
                    { 941, 31, "Tom26@gmail.com", "Tom", "DB", 1, "Berge" },
                    { 942, 8, "Floyd_Brakus@yahoo.com", "Floyd", "DB", 0, "Brakus" },
                    { 943, 87, "Israel.Robel@hotmail.com", "Israel", "DB", 1, "Robel" },
                    { 944, 75, "Rick.Collier@hotmail.com", "Rick", "DB", 0, "Collier" },
                    { 945, 19, "Cedric_Walsh@hotmail.com", "Cedric", "DB", 1, "Walsh" },
                    { 946, 24, "Lee51@gmail.com", "Lee", "DB", 1, "Steuber" },
                    { 947, 8, "Alberta31@hotmail.com", "Alberta", "DB", 1, "Batz" },
                    { 948, 43, "Delbert.Bartoletti89@hotmail.com", "Delbert", "DB", 0, "Bartoletti" },
                    { 949, 90, "Chester86@gmail.com", "Chester", "DB", 1, "Grady" },
                    { 950, 79, "Emily.Kling16@hotmail.com", "Emily", "DB", 1, "Kling" },
                    { 951, 34, "Tomas.Kessler51@gmail.com", "Tomas", "DB", 0, "Kessler" },
                    { 952, 23, "Preston.Tillman@yahoo.com", "Preston", "DB", 0, "Tillman" },
                    { 953, 36, "Kerry_Hoppe71@hotmail.com", "Kerry", "DB", 1, "Hoppe" },
                    { 954, 65, "Kathleen_Auer51@gmail.com", "Kathleen", "DB", 0, "Auer" },
                    { 955, 12, "Darrell71@yahoo.com", "Darrell", "DB", 1, "Pfeffer" },
                    { 956, 56, "Christy.Wuckert@hotmail.com", "Christy", "DB", 1, "Wuckert" },
                    { 957, 84, "Ricky4@gmail.com", "Ricky", "DB", 1, "Herman" },
                    { 958, 9, "Max_Glover51@hotmail.com", "Max", "DB", 1, "Glover" },
                    { 959, 76, "Mathew43@yahoo.com", "Mathew", "DB", 1, "Simonis" },
                    { 960, 52, "Maxine71@yahoo.com", "Maxine", "DB", 1, "Murphy" },
                    { 961, 50, "Forrest28@gmail.com", "Forrest", "DB", 0, "Feil" },
                    { 962, 19, "Jessica80@gmail.com", "Jessica", "DB", 1, "Homenick" },
                    { 963, 50, "Ellen_Cole97@gmail.com", "Ellen", "DB", 0, "Cole" },
                    { 964, 20, "Terrance.Wisozk20@yahoo.com", "Terrance", "DB", 1, "Wisozk" },
                    { 965, 26, "Traci.Parisian@hotmail.com", "Traci", "DB", 0, "Parisian" },
                    { 966, 34, "Cindy_Hyatt@gmail.com", "Cindy", "DB", 0, "Hyatt" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 967, 74, "Thelma_Monahan2@gmail.com", "Thelma", "DB", 1, "Monahan" },
                    { 968, 11, "Erik.Legros@gmail.com", "Erik", "DB", 1, "Legros" },
                    { 969, 23, "Glen35@gmail.com", "Glen", "DB", 1, "Daniel" },
                    { 970, 16, "Iris36@gmail.com", "Iris", "DB", 1, "Mayer" },
                    { 971, 53, "Greg.Bergstrom@hotmail.com", "Greg", "DB", 1, "Bergstrom" },
                    { 972, 64, "Miriam26@yahoo.com", "Miriam", "DB", 0, "Crooks" },
                    { 973, 15, "Janis17@gmail.com", "Janis", "DB", 1, "Roberts" },
                    { 974, 28, "Todd78@hotmail.com", "Todd", "DB", 1, "Pfeffer" },
                    { 975, 62, "Christopher7@gmail.com", "Christopher", "DB", 1, "Schultz" },
                    { 976, 21, "Willard_Stoltenberg@yahoo.com", "Willard", "DB", 1, "Stoltenberg" },
                    { 977, 54, "Tina32@yahoo.com", "Tina", "DB", 1, "Waelchi" },
                    { 978, 44, "Julian71@yahoo.com", "Julian", "DB", 0, "Grant" },
                    { 979, 31, "Jaime.Herzog46@hotmail.com", "Jaime", "DB", 1, "Herzog" },
                    { 980, 27, "Vivian10@yahoo.com", "Vivian", "DB", 1, "Dietrich" },
                    { 981, 88, "Natalie.Cremin@yahoo.com", "Natalie", "DB", 0, "Cremin" },
                    { 982, 72, "Dana33@hotmail.com", "Dana", "DB", 0, "Kunze" },
                    { 983, 66, "Florence95@hotmail.com", "Florence", "DB", 1, "Hand" },
                    { 984, 87, "Jack_Mueller@gmail.com", "Jack", "DB", 0, "Mueller" },
                    { 985, 38, "Sonja_Herzog@hotmail.com", "Sonja", "DB", 0, "Herzog" },
                    { 986, 39, "Miriam_Beier@hotmail.com", "Miriam", "DB", 0, "Beier" },
                    { 987, 45, "Clay44@gmail.com", "Clay", "DB", 1, "Connelly" },
                    { 988, 50, "Carroll.Pacocha@hotmail.com", "Carroll", "DB", 1, "Pacocha" },
                    { 989, 37, "Candace40@hotmail.com", "Candace", "DB", 1, "Larkin" },
                    { 990, 69, "Lucas.Deckow11@yahoo.com", "Lucas", "DB", 0, "Deckow" },
                    { 991, 63, "Floyd73@gmail.com", "Floyd", "DB", 1, "Klocko" },
                    { 992, 76, "Woodrow_Reilly37@hotmail.com", "Woodrow", "DB", 0, "Reilly" },
                    { 993, 53, "Ruben.Gibson@gmail.com", "Ruben", "DB", 0, "Gibson" },
                    { 994, 59, "Nellie.Jacobson@yahoo.com", "Nellie", "DB", 0, "Jacobson" },
                    { 995, 79, "Ernesto_Aufderhar43@gmail.com", "Ernesto", "DB", 1, "Aufderhar" },
                    { 996, 52, "Tamara.Stroman61@hotmail.com", "Tamara", "DB", 1, "Stroman" },
                    { 997, 62, "Randall_Dicki@gmail.com", "Randall", "DB", 0, "Dicki" },
                    { 998, 71, "Johnathan_Gutkowski95@hotmail.com", "Johnathan", "DB", 1, "Gutkowski" },
                    { 999, 34, "Kelly_Conroy19@gmail.com", "Kelly", "DB", 1, "Conroy" },
                    { 1000, 44, "Randolph_Wyman0@gmail.com", "Randolph", "DB", 0, "Wyman" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
