using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataAccess.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    FirstName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LastName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Age = table.Column<int>(type: "int", nullable: false),
                    Email = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Gender = table.Column<int>(type: "int", nullable: false),
                    Framework = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 1, 48, "Roland.Toy19@hotmail.com", "Roland", "DB", 0, "Toy" },
                    { 2, 49, "Gregg23@yahoo.com", "Gregg", "DB", 1, "Labadie" },
                    { 3, 63, "Shari.Thompson92@yahoo.com", "Shari", "DB", 1, "Thompson" },
                    { 4, 61, "Simon36@gmail.com", "Simon", "DB", 1, "Zboncak" },
                    { 5, 85, "Timmy.DuBuque2@yahoo.com", "Timmy", "DB", 1, "DuBuque" },
                    { 6, 24, "Spencer.Stehr16@hotmail.com", "Spencer", "DB", 0, "Stehr" },
                    { 7, 78, "Fernando.Jones63@yahoo.com", "Fernando", "DB", 0, "Jones" },
                    { 8, 20, "Lauren_Kozey@hotmail.com", "Lauren", "DB", 1, "Kozey" },
                    { 9, 19, "Lynda54@yahoo.com", "Lynda", "DB", 0, "Wintheiser" },
                    { 10, 59, "Simon.Steuber@gmail.com", "Simon", "DB", 1, "Steuber" },
                    { 11, 47, "Jody59@yahoo.com", "Jody", "DB", 1, "Gutmann" },
                    { 12, 19, "Melinda.Predovic10@hotmail.com", "Melinda", "DB", 1, "Predovic" },
                    { 13, 38, "Gilbert34@gmail.com", "Gilbert", "DB", 1, "Abshire" },
                    { 14, 32, "Ella_Jerde@hotmail.com", "Ella", "DB", 1, "Jerde" },
                    { 15, 20, "Don87@gmail.com", "Don", "DB", 0, "Frami" },
                    { 16, 24, "Carol_Gulgowski@gmail.com", "Carol", "DB", 0, "Gulgowski" },
                    { 17, 17, "Theresa90@gmail.com", "Theresa", "DB", 0, "Veum" },
                    { 18, 54, "Mark_Daugherty95@hotmail.com", "Mark", "DB", 1, "Daugherty" },
                    { 19, 41, "Estelle56@yahoo.com", "Estelle", "DB", 0, "Lakin" },
                    { 20, 78, "Saul.Cassin54@gmail.com", "Saul", "DB", 1, "Cassin" },
                    { 21, 16, "Donna.Zieme@yahoo.com", "Donna", "DB", 0, "Zieme" },
                    { 22, 51, "Everett34@yahoo.com", "Everett", "DB", 1, "Kshlerin" },
                    { 23, 81, "Homer86@hotmail.com", "Homer", "DB", 0, "Hudson" },
                    { 24, 35, "Rhonda_Reilly94@yahoo.com", "Rhonda", "DB", 0, "Reilly" },
                    { 25, 8, "Jacqueline60@gmail.com", "Jacqueline", "DB", 0, "Streich" },
                    { 26, 48, "Kim67@gmail.com", "Kim", "DB", 1, "Reilly" },
                    { 27, 61, "Ralph.Gorczany@gmail.com", "Ralph", "DB", 0, "Gorczany" },
                    { 28, 72, "Hope_Pollich81@hotmail.com", "Hope", "DB", 1, "Pollich" },
                    { 29, 64, "Jermaine.Dooley@hotmail.com", "Jermaine", "DB", 1, "Dooley" },
                    { 30, 11, "Dolores54@gmail.com", "Dolores", "DB", 0, "Champlin" },
                    { 31, 72, "Gina_Prosacco@gmail.com", "Gina", "DB", 0, "Prosacco" },
                    { 32, 46, "Frances_Hessel55@gmail.com", "Frances", "DB", 1, "Hessel" },
                    { 33, 55, "Orville91@gmail.com", "Orville", "DB", 0, "O'Hara" },
                    { 34, 32, "Dwight.Schuster@yahoo.com", "Dwight", "DB", 0, "Schuster" },
                    { 35, 46, "Carl.Von@yahoo.com", "Carl", "DB", 1, "Von" },
                    { 36, 11, "Ebony_Wuckert@gmail.com", "Ebony", "DB", 1, "Wuckert" },
                    { 37, 89, "Inez.Spencer69@gmail.com", "Inez", "DB", 1, "Spencer" },
                    { 38, 70, "Angelo.Ferry79@gmail.com", "Angelo", "DB", 0, "Ferry" },
                    { 39, 59, "Ivan_Raynor62@yahoo.com", "Ivan", "DB", 1, "Raynor" },
                    { 40, 27, "Irene0@yahoo.com", "Irene", "DB", 0, "Krajcik" },
                    { 41, 78, "Darrin53@gmail.com", "Darrin", "DB", 0, "Cormier" },
                    { 42, 77, "Milton.Barrows@yahoo.com", "Milton", "DB", 1, "Barrows" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 43, 61, "Josefina_Ruecker1@hotmail.com", "Josefina", "DB", 1, "Ruecker" },
                    { 44, 14, "Milton.Moen80@yahoo.com", "Milton", "DB", 0, "Moen" },
                    { 45, 58, "Ismael_Kirlin@gmail.com", "Ismael", "DB", 1, "Kirlin" },
                    { 46, 13, "Tom_Stehr@gmail.com", "Tom", "DB", 1, "Stehr" },
                    { 47, 27, "Jacob45@hotmail.com", "Jacob", "DB", 1, "Von" },
                    { 48, 74, "Phil_Johnston@yahoo.com", "Phil", "DB", 1, "Johnston" },
                    { 49, 69, "Hubert89@hotmail.com", "Hubert", "DB", 0, "Muller" },
                    { 50, 19, "Angie_Kuphal59@gmail.com", "Angie", "DB", 0, "Kuphal" },
                    { 51, 8, "Sonya.Wilkinson85@gmail.com", "Sonya", "DB", 1, "Wilkinson" },
                    { 52, 65, "Victoria_Metz@gmail.com", "Victoria", "DB", 0, "Metz" },
                    { 53, 60, "Jodi46@gmail.com", "Jodi", "DB", 1, "Franecki" },
                    { 54, 51, "Matthew5@hotmail.com", "Matthew", "DB", 1, "Jast" },
                    { 55, 68, "Ross14@hotmail.com", "Ross", "DB", 1, "Carroll" },
                    { 56, 42, "Arnold.Lakin@yahoo.com", "Arnold", "DB", 0, "Lakin" },
                    { 57, 72, "Wayne_Gleichner@yahoo.com", "Wayne", "DB", 1, "Gleichner" },
                    { 58, 84, "Philip78@yahoo.com", "Philip", "DB", 1, "Leannon" },
                    { 59, 84, "Terrell.Koss@hotmail.com", "Terrell", "DB", 0, "Koss" },
                    { 60, 75, "Gail_McClure@hotmail.com", "Gail", "DB", 1, "McClure" },
                    { 61, 67, "Nancy_Rohan@yahoo.com", "Nancy", "DB", 0, "Rohan" },
                    { 62, 27, "Kim_Gislason@gmail.com", "Kim", "DB", 0, "Gislason" },
                    { 63, 65, "Marcia2@hotmail.com", "Marcia", "DB", 0, "Hackett" },
                    { 64, 25, "Monique_Conn50@gmail.com", "Monique", "DB", 0, "Conn" },
                    { 65, 14, "Andrea36@yahoo.com", "Andrea", "DB", 1, "McCullough" },
                    { 66, 37, "Brenda_Stiedemann@hotmail.com", "Brenda", "DB", 0, "Stiedemann" },
                    { 67, 13, "Caleb_Koepp44@hotmail.com", "Caleb", "DB", 0, "Koepp" },
                    { 68, 21, "Kent_Cummings62@gmail.com", "Kent", "DB", 1, "Cummings" },
                    { 69, 69, "Grace.Conn94@yahoo.com", "Grace", "DB", 1, "Conn" },
                    { 70, 62, "Doreen6@hotmail.com", "Doreen", "DB", 0, "Vandervort" },
                    { 71, 60, "Jon13@yahoo.com", "Jon", "DB", 1, "Bins" },
                    { 72, 83, "Christine51@gmail.com", "Christine", "DB", 1, "Balistreri" },
                    { 73, 37, "Derrick_Ledner@yahoo.com", "Derrick", "DB", 1, "Ledner" },
                    { 74, 21, "Ted.Koepp@gmail.com", "Ted", "DB", 0, "Koepp" },
                    { 75, 79, "Calvin16@yahoo.com", "Calvin", "DB", 0, "Schneider" },
                    { 76, 66, "Jeannie_Schowalter@hotmail.com", "Jeannie", "DB", 0, "Schowalter" },
                    { 77, 53, "Kirk62@yahoo.com", "Kirk", "DB", 0, "Orn" },
                    { 78, 30, "Lisa.Goyette59@yahoo.com", "Lisa", "DB", 0, "Goyette" },
                    { 79, 68, "Mary.Feest@gmail.com", "Mary", "DB", 1, "Feest" },
                    { 80, 64, "Derek.Corwin@yahoo.com", "Derek", "DB", 0, "Corwin" },
                    { 81, 54, "Kenneth69@gmail.com", "Kenneth", "DB", 1, "Fadel" },
                    { 82, 83, "Brandi_Hoppe35@gmail.com", "Brandi", "DB", 1, "Hoppe" },
                    { 83, 89, "Zachary_Beer@hotmail.com", "Zachary", "DB", 1, "Beer" },
                    { 84, 61, "Theresa_Will@gmail.com", "Theresa", "DB", 0, "Will" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 85, 38, "Sonja.Kerluke@hotmail.com", "Sonja", "DB", 0, "Kerluke" },
                    { 86, 90, "Meghan_Friesen58@gmail.com", "Meghan", "DB", 0, "Friesen" },
                    { 87, 25, "Mark_Nikolaus@hotmail.com", "Mark", "DB", 0, "Nikolaus" },
                    { 88, 55, "Melanie.Lehner@hotmail.com", "Melanie", "DB", 0, "Lehner" },
                    { 89, 43, "Nettie.Muller11@yahoo.com", "Nettie", "DB", 0, "Muller" },
                    { 90, 21, "Paulette.Hoppe39@yahoo.com", "Paulette", "DB", 0, "Hoppe" },
                    { 91, 61, "Marcos39@yahoo.com", "Marcos", "DB", 0, "Johnston" },
                    { 92, 23, "Martha88@yahoo.com", "Martha", "DB", 0, "Larkin" },
                    { 93, 8, "Ismael_Pollich@gmail.com", "Ismael", "DB", 1, "Pollich" },
                    { 94, 47, "Sam.Romaguera38@hotmail.com", "Sam", "DB", 0, "Romaguera" },
                    { 95, 62, "Ken_Parisian82@yahoo.com", "Ken", "DB", 1, "Parisian" },
                    { 96, 84, "Fernando.Macejkovic65@gmail.com", "Fernando", "DB", 1, "Macejkovic" },
                    { 97, 8, "Cassandra_Schaefer67@hotmail.com", "Cassandra", "DB", 0, "Schaefer" },
                    { 98, 65, "Hector.Ernser@hotmail.com", "Hector", "DB", 1, "Ernser" },
                    { 99, 47, "Lewis_Christiansen26@yahoo.com", "Lewis", "DB", 1, "Christiansen" },
                    { 100, 34, "Casey32@hotmail.com", "Casey", "DB", 1, "Cummings" },
                    { 101, 12, "Lyle_Dickinson82@yahoo.com", "Lyle", "DB", 1, "Dickinson" },
                    { 102, 64, "Domingo83@yahoo.com", "Domingo", "DB", 0, "Labadie" },
                    { 103, 13, "Dana.Bahringer@gmail.com", "Dana", "DB", 0, "Bahringer" },
                    { 104, 12, "Clark_Jaskolski55@hotmail.com", "Clark", "DB", 0, "Jaskolski" },
                    { 105, 88, "Israel8@yahoo.com", "Israel", "DB", 0, "Ondricka" },
                    { 106, 80, "Clint_Rogahn61@yahoo.com", "Clint", "DB", 0, "Rogahn" },
                    { 107, 23, "Rochelle_Wisozk87@yahoo.com", "Rochelle", "DB", 0, "Wisozk" },
                    { 108, 57, "Mandy_Kunde26@gmail.com", "Mandy", "DB", 1, "Kunde" },
                    { 109, 73, "Roosevelt16@yahoo.com", "Roosevelt", "DB", 0, "Harvey" },
                    { 110, 13, "Daisy.Cruickshank51@yahoo.com", "Daisy", "DB", 1, "Cruickshank" },
                    { 111, 16, "Yolanda28@hotmail.com", "Yolanda", "DB", 1, "Robel" },
                    { 112, 14, "Johnathan61@hotmail.com", "Johnathan", "DB", 0, "Hansen" },
                    { 113, 44, "Ella_Becker@gmail.com", "Ella", "DB", 0, "Becker" },
                    { 114, 33, "Jacqueline_Grimes95@yahoo.com", "Jacqueline", "DB", 1, "Grimes" },
                    { 115, 79, "Lora41@gmail.com", "Lora", "DB", 0, "Bogan" },
                    { 116, 56, "Leigh.Stracke@yahoo.com", "Leigh", "DB", 0, "Stracke" },
                    { 117, 62, "Arnold.Rosenbaum@gmail.com", "Arnold", "DB", 1, "Rosenbaum" },
                    { 118, 79, "Laurie.Barton@gmail.com", "Laurie", "DB", 1, "Barton" },
                    { 119, 30, "Albert58@hotmail.com", "Albert", "DB", 1, "Keeling" },
                    { 120, 31, "Wesley_Auer65@yahoo.com", "Wesley", "DB", 0, "Auer" },
                    { 121, 44, "Edna78@yahoo.com", "Edna", "DB", 0, "Schimmel" },
                    { 122, 15, "Daryl68@hotmail.com", "Daryl", "DB", 0, "Schneider" },
                    { 123, 90, "Jose26@gmail.com", "Jose", "DB", 0, "Kling" },
                    { 124, 74, "Ramiro72@hotmail.com", "Ramiro", "DB", 1, "Kreiger" },
                    { 125, 24, "Greg.Weimann@hotmail.com", "Greg", "DB", 0, "Weimann" },
                    { 126, 33, "James.Brakus94@yahoo.com", "James", "DB", 1, "Brakus" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 127, 32, "Myron.Kuhic83@gmail.com", "Myron", "DB", 1, "Kuhic" },
                    { 128, 79, "Edward.Krajcik4@yahoo.com", "Edward", "DB", 0, "Krajcik" },
                    { 129, 30, "Ebony_Schmidt26@hotmail.com", "Ebony", "DB", 1, "Schmidt" },
                    { 130, 13, "Nathaniel27@yahoo.com", "Nathaniel", "DB", 0, "Walter" },
                    { 131, 21, "Cynthia_Roob62@yahoo.com", "Cynthia", "DB", 0, "Roob" },
                    { 132, 65, "Cheryl_Buckridge@hotmail.com", "Cheryl", "DB", 0, "Buckridge" },
                    { 133, 33, "Tracy29@yahoo.com", "Tracy", "DB", 1, "Wiza" },
                    { 134, 45, "Francisco14@hotmail.com", "Francisco", "DB", 0, "Doyle" },
                    { 135, 34, "Jermaine.Swaniawski55@hotmail.com", "Jermaine", "DB", 0, "Swaniawski" },
                    { 136, 57, "Max.Shields80@yahoo.com", "Max", "DB", 0, "Shields" },
                    { 137, 74, "Eileen39@gmail.com", "Eileen", "DB", 1, "Macejkovic" },
                    { 138, 54, "Nadine.Russel10@yahoo.com", "Nadine", "DB", 1, "Russel" },
                    { 139, 19, "Neal_Adams23@gmail.com", "Neal", "DB", 0, "Adams" },
                    { 140, 27, "Kristine_Wiegand13@gmail.com", "Kristine", "DB", 1, "Wiegand" },
                    { 141, 53, "Pedro27@yahoo.com", "Pedro", "DB", 0, "Gusikowski" },
                    { 142, 69, "April33@hotmail.com", "April", "DB", 0, "Huel" },
                    { 143, 19, "Clarence52@hotmail.com", "Clarence", "DB", 1, "Stamm" },
                    { 144, 43, "Freda.Schultz91@yahoo.com", "Freda", "DB", 1, "Schultz" },
                    { 145, 49, "Rodney92@hotmail.com", "Rodney", "DB", 0, "Gibson" },
                    { 146, 59, "Jenny18@hotmail.com", "Jenny", "DB", 1, "Koss" },
                    { 147, 49, "Chester_Kreiger8@yahoo.com", "Chester", "DB", 0, "Kreiger" },
                    { 148, 26, "Dana_Tremblay@gmail.com", "Dana", "DB", 1, "Tremblay" },
                    { 149, 60, "Lowell.Jacobson83@hotmail.com", "Lowell", "DB", 1, "Jacobson" },
                    { 150, 43, "Gwen_Padberg61@yahoo.com", "Gwen", "DB", 1, "Padberg" },
                    { 151, 18, "Carrie.Von39@yahoo.com", "Carrie", "DB", 0, "Von" },
                    { 152, 22, "Marguerite.Kshlerin@yahoo.com", "Marguerite", "DB", 0, "Kshlerin" },
                    { 153, 63, "Jerome71@gmail.com", "Jerome", "DB", 1, "Ward" },
                    { 154, 62, "Megan13@gmail.com", "Megan", "DB", 1, "Bernhard" },
                    { 155, 23, "Jamie12@gmail.com", "Jamie", "DB", 0, "Orn" },
                    { 156, 69, "Angela_Wunsch@hotmail.com", "Angela", "DB", 1, "Wunsch" },
                    { 157, 41, "Ken50@hotmail.com", "Ken", "DB", 1, "Yundt" },
                    { 158, 38, "Dominick69@gmail.com", "Dominick", "DB", 1, "Bayer" },
                    { 159, 48, "Lyle97@yahoo.com", "Lyle", "DB", 1, "Watsica" },
                    { 160, 11, "Joel_Sauer@gmail.com", "Joel", "DB", 0, "Sauer" },
                    { 161, 69, "Tamara_Greenholt93@gmail.com", "Tamara", "DB", 1, "Greenholt" },
                    { 162, 87, "Harriet_Gutmann45@hotmail.com", "Harriet", "DB", 1, "Gutmann" },
                    { 163, 71, "Wanda_Frami18@hotmail.com", "Wanda", "DB", 1, "Frami" },
                    { 164, 71, "Amanda61@hotmail.com", "Amanda", "DB", 0, "Yost" },
                    { 165, 45, "Juana_Farrell@hotmail.com", "Juana", "DB", 1, "Farrell" },
                    { 166, 11, "Jon.DAmore@gmail.com", "Jon", "DB", 1, "D'Amore" },
                    { 167, 43, "Courtney.Schamberger@hotmail.com", "Courtney", "DB", 1, "Schamberger" },
                    { 168, 29, "Josephine.Cronin44@gmail.com", "Josephine", "DB", 0, "Cronin" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 169, 86, "Phil.Smitham2@hotmail.com", "Phil", "DB", 0, "Smitham" },
                    { 170, 87, "Darlene.Conn80@hotmail.com", "Darlene", "DB", 0, "Conn" },
                    { 171, 88, "Essie.Weimann@gmail.com", "Essie", "DB", 0, "Weimann" },
                    { 172, 14, "Amelia_Orn23@gmail.com", "Amelia", "DB", 0, "Orn" },
                    { 173, 41, "Jaime67@hotmail.com", "Jaime", "DB", 1, "Bayer" },
                    { 174, 89, "Kendra29@hotmail.com", "Kendra", "DB", 1, "Koepp" },
                    { 175, 14, "Rodolfo_Cronin57@gmail.com", "Rodolfo", "DB", 1, "Cronin" },
                    { 176, 66, "Levi6@yahoo.com", "Levi", "DB", 1, "Stehr" },
                    { 177, 63, "Lauren_Reynolds94@gmail.com", "Lauren", "DB", 0, "Reynolds" },
                    { 178, 84, "Carmen_Ferry45@hotmail.com", "Carmen", "DB", 0, "Ferry" },
                    { 179, 36, "Grace.Halvorson9@yahoo.com", "Grace", "DB", 0, "Halvorson" },
                    { 180, 52, "Rodolfo_Friesen15@yahoo.com", "Rodolfo", "DB", 1, "Friesen" },
                    { 181, 67, "Kristi_Osinski13@gmail.com", "Kristi", "DB", 1, "Osinski" },
                    { 182, 60, "Andres53@hotmail.com", "Andres", "DB", 1, "Abernathy" },
                    { 183, 23, "Michael81@gmail.com", "Michael", "DB", 0, "Breitenberg" },
                    { 184, 13, "Gladys_Aufderhar@gmail.com", "Gladys", "DB", 1, "Aufderhar" },
                    { 185, 34, "Ginger_Carter24@yahoo.com", "Ginger", "DB", 0, "Carter" },
                    { 186, 8, "Gerard5@hotmail.com", "Gerard", "DB", 0, "Luettgen" },
                    { 187, 57, "Spencer79@yahoo.com", "Spencer", "DB", 0, "Shanahan" },
                    { 188, 67, "Amanda_Stiedemann@gmail.com", "Amanda", "DB", 1, "Stiedemann" },
                    { 189, 21, "Wesley34@hotmail.com", "Wesley", "DB", 1, "O'Kon" },
                    { 190, 11, "Dixie80@gmail.com", "Dixie", "DB", 1, "Murphy" },
                    { 191, 85, "Lester.Braun@yahoo.com", "Lester", "DB", 1, "Braun" },
                    { 192, 55, "Marcia.Armstrong@yahoo.com", "Marcia", "DB", 1, "Armstrong" },
                    { 193, 41, "Mark_Cassin@yahoo.com", "Mark", "DB", 1, "Cassin" },
                    { 194, 16, "Lillie_Waelchi42@gmail.com", "Lillie", "DB", 0, "Waelchi" },
                    { 195, 88, "David41@hotmail.com", "David", "DB", 1, "Ledner" },
                    { 196, 72, "Amos_Keebler@gmail.com", "Amos", "DB", 1, "Keebler" },
                    { 197, 64, "Derrick.Veum57@yahoo.com", "Derrick", "DB", 0, "Veum" },
                    { 198, 34, "Darryl72@hotmail.com", "Darryl", "DB", 0, "Quitzon" },
                    { 199, 29, "Jamie.Huel@gmail.com", "Jamie", "DB", 1, "Huel" },
                    { 200, 17, "Lillie_OKon@hotmail.com", "Lillie", "DB", 0, "O'Kon" },
                    { 201, 86, "Dave.Buckridge61@gmail.com", "Dave", "DB", 0, "Buckridge" },
                    { 202, 37, "Roy_Morar24@yahoo.com", "Roy", "DB", 1, "Morar" },
                    { 203, 67, "Lawrence20@gmail.com", "Lawrence", "DB", 0, "Zemlak" },
                    { 204, 80, "Sean_Dooley20@gmail.com", "Sean", "DB", 1, "Dooley" },
                    { 205, 29, "Julian52@yahoo.com", "Julian", "DB", 0, "Zieme" },
                    { 206, 15, "Dewey50@gmail.com", "Dewey", "DB", 0, "Blanda" },
                    { 207, 46, "Julie.Barton@yahoo.com", "Julie", "DB", 0, "Barton" },
                    { 208, 47, "Ginger_Rempel@yahoo.com", "Ginger", "DB", 1, "Rempel" },
                    { 209, 35, "Cory38@gmail.com", "Cory", "DB", 0, "Beahan" },
                    { 210, 82, "Roman74@yahoo.com", "Roman", "DB", 1, "Fay" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 211, 20, "Kyle.Trantow@gmail.com", "Kyle", "DB", 0, "Trantow" },
                    { 212, 8, "Hannah41@hotmail.com", "Hannah", "DB", 0, "Cartwright" },
                    { 213, 10, "Mona38@gmail.com", "Mona", "DB", 0, "Beatty" },
                    { 214, 48, "Caroline_Anderson3@yahoo.com", "Caroline", "DB", 0, "Anderson" },
                    { 215, 62, "Randolph41@yahoo.com", "Randolph", "DB", 1, "Kuhic" },
                    { 216, 49, "Pat19@gmail.com", "Pat", "DB", 1, "Heller" },
                    { 217, 56, "Regina_Hodkiewicz@gmail.com", "Regina", "DB", 0, "Hodkiewicz" },
                    { 218, 19, "Danielle_Rutherford88@gmail.com", "Danielle", "DB", 0, "Rutherford" },
                    { 219, 26, "Oliver29@gmail.com", "Oliver", "DB", 1, "Morar" },
                    { 220, 25, "Lewis69@yahoo.com", "Lewis", "DB", 1, "Kassulke" },
                    { 221, 82, "Brandy.Hagenes34@hotmail.com", "Brandy", "DB", 0, "Hagenes" },
                    { 222, 70, "Javier_Stanton77@yahoo.com", "Javier", "DB", 0, "Stanton" },
                    { 223, 42, "Darlene81@hotmail.com", "Darlene", "DB", 1, "Kshlerin" },
                    { 224, 17, "Lynda.Emard@gmail.com", "Lynda", "DB", 0, "Emard" },
                    { 225, 56, "Helen.Langworth@gmail.com", "Helen", "DB", 1, "Langworth" },
                    { 226, 89, "Kenny_Boyle@hotmail.com", "Kenny", "DB", 0, "Boyle" },
                    { 227, 74, "Winifred86@gmail.com", "Winifred", "DB", 0, "Legros" },
                    { 228, 83, "Earl.Kirlin@hotmail.com", "Earl", "DB", 0, "Kirlin" },
                    { 229, 50, "Chelsea.Will88@yahoo.com", "Chelsea", "DB", 0, "Will" },
                    { 230, 25, "Dominic21@hotmail.com", "Dominic", "DB", 0, "Gislason" },
                    { 231, 15, "Tim97@hotmail.com", "Tim", "DB", 0, "Braun" },
                    { 232, 80, "Max.OHara@yahoo.com", "Max", "DB", 0, "O'Hara" },
                    { 233, 16, "Nina.Hermiston@gmail.com", "Nina", "DB", 0, "Hermiston" },
                    { 234, 83, "Brandi39@yahoo.com", "Brandi", "DB", 1, "Gerlach" },
                    { 235, 19, "Nadine.Ondricka18@yahoo.com", "Nadine", "DB", 0, "Ondricka" },
                    { 236, 49, "Abraham85@hotmail.com", "Abraham", "DB", 1, "Muller" },
                    { 237, 43, "Jeremy_Ritchie@yahoo.com", "Jeremy", "DB", 0, "Ritchie" },
                    { 238, 68, "Lewis_Schamberger@gmail.com", "Lewis", "DB", 1, "Schamberger" },
                    { 239, 37, "Julius_Jacobi@yahoo.com", "Julius", "DB", 0, "Jacobi" },
                    { 240, 86, "Emmett_White@yahoo.com", "Emmett", "DB", 0, "White" },
                    { 241, 52, "Jeanne81@gmail.com", "Jeanne", "DB", 1, "Dicki" },
                    { 242, 36, "Erick64@hotmail.com", "Erick", "DB", 1, "Reichel" },
                    { 243, 34, "Clinton_Smith@gmail.com", "Clinton", "DB", 1, "Smith" },
                    { 244, 43, "Herman.Kozey@hotmail.com", "Herman", "DB", 0, "Kozey" },
                    { 245, 68, "Inez_Volkman72@gmail.com", "Inez", "DB", 0, "Volkman" },
                    { 246, 17, "Neal39@gmail.com", "Neal", "DB", 0, "Rutherford" },
                    { 247, 18, "Elias.Schuster@gmail.com", "Elias", "DB", 1, "Schuster" },
                    { 248, 70, "Kelley.Terry@hotmail.com", "Kelley", "DB", 1, "Terry" },
                    { 249, 55, "Isaac89@hotmail.com", "Isaac", "DB", 1, "Leannon" },
                    { 250, 86, "Ken.MacGyver@hotmail.com", "Ken", "DB", 1, "MacGyver" },
                    { 251, 81, "Ira67@yahoo.com", "Ira", "DB", 0, "Kertzmann" },
                    { 252, 36, "Sonya.OConner90@yahoo.com", "Sonya", "DB", 0, "O'Conner" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 253, 78, "Rosemary90@hotmail.com", "Rosemary", "DB", 1, "Rolfson" },
                    { 254, 47, "Mindy_Schuster@yahoo.com", "Mindy", "DB", 0, "Schuster" },
                    { 255, 54, "Yvonne_Schinner@yahoo.com", "Yvonne", "DB", 1, "Schinner" },
                    { 256, 69, "Rosemarie_Hartmann60@gmail.com", "Rosemarie", "DB", 1, "Hartmann" },
                    { 257, 8, "Chris66@hotmail.com", "Chris", "DB", 0, "Steuber" },
                    { 258, 29, "Nellie_Anderson49@hotmail.com", "Nellie", "DB", 1, "Anderson" },
                    { 259, 79, "Gina_Pfeffer@hotmail.com", "Gina", "DB", 0, "Pfeffer" },
                    { 260, 65, "Sherry.Walker24@hotmail.com", "Sherry", "DB", 1, "Walker" },
                    { 261, 33, "Alfonso.Hessel@gmail.com", "Alfonso", "DB", 0, "Hessel" },
                    { 262, 56, "Agnes_Leannon@gmail.com", "Agnes", "DB", 1, "Leannon" },
                    { 263, 11, "Joey_Green51@hotmail.com", "Joey", "DB", 0, "Green" },
                    { 264, 79, "Sheri33@gmail.com", "Sheri", "DB", 0, "Cartwright" },
                    { 265, 23, "Holly.Spencer@hotmail.com", "Holly", "DB", 1, "Spencer" },
                    { 266, 61, "Erma_Reichert@gmail.com", "Erma", "DB", 1, "Reichert" },
                    { 267, 33, "Dexter_Treutel@gmail.com", "Dexter", "DB", 1, "Treutel" },
                    { 268, 34, "Brandy.Yundt@yahoo.com", "Brandy", "DB", 0, "Yundt" },
                    { 269, 33, "Tom_Nolan@hotmail.com", "Tom", "DB", 1, "Nolan" },
                    { 270, 31, "Ronald78@yahoo.com", "Ronald", "DB", 0, "Beier" },
                    { 271, 49, "Jo89@hotmail.com", "Jo", "DB", 1, "Heller" },
                    { 272, 23, "Tanya_Stark10@hotmail.com", "Tanya", "DB", 1, "Stark" },
                    { 273, 86, "Tami.Funk@yahoo.com", "Tami", "DB", 0, "Funk" },
                    { 274, 29, "Nancy_Schaden68@hotmail.com", "Nancy", "DB", 0, "Schaden" },
                    { 275, 90, "Brandi.Cruickshank75@hotmail.com", "Brandi", "DB", 0, "Cruickshank" },
                    { 276, 68, "Desiree_Ziemann@yahoo.com", "Desiree", "DB", 1, "Ziemann" },
                    { 277, 35, "Susan.Metz@yahoo.com", "Susan", "DB", 1, "Metz" },
                    { 278, 81, "Charlie.Auer61@gmail.com", "Charlie", "DB", 1, "Auer" },
                    { 279, 67, "Jacob27@gmail.com", "Jacob", "DB", 1, "Osinski" },
                    { 280, 35, "Elizabeth47@yahoo.com", "Elizabeth", "DB", 1, "Christiansen" },
                    { 281, 42, "Elisa_Marks31@yahoo.com", "Elisa", "DB", 1, "Marks" },
                    { 282, 90, "Leona63@hotmail.com", "Leona", "DB", 0, "Ritchie" },
                    { 283, 47, "Cody_Rodriguez@yahoo.com", "Cody", "DB", 0, "Rodriguez" },
                    { 284, 44, "Sammy.Reynolds@hotmail.com", "Sammy", "DB", 0, "Reynolds" },
                    { 285, 59, "Damon.Auer90@gmail.com", "Damon", "DB", 0, "Auer" },
                    { 286, 88, "Harry22@hotmail.com", "Harry", "DB", 0, "Reichel" },
                    { 287, 10, "Mattie.Gutkowski70@hotmail.com", "Mattie", "DB", 0, "Gutkowski" },
                    { 288, 40, "Patti.Brekke81@gmail.com", "Patti", "DB", 0, "Brekke" },
                    { 289, 69, "Tasha.Beier@gmail.com", "Tasha", "DB", 1, "Beier" },
                    { 290, 47, "Bernice30@hotmail.com", "Bernice", "DB", 0, "Christiansen" },
                    { 291, 89, "Elena_Reinger0@yahoo.com", "Elena", "DB", 0, "Reinger" },
                    { 292, 37, "Helen.Block78@hotmail.com", "Helen", "DB", 0, "Block" },
                    { 293, 35, "Douglas_Littel@hotmail.com", "Douglas", "DB", 1, "Littel" },
                    { 294, 73, "Lana.Terry@gmail.com", "Lana", "DB", 0, "Terry" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 295, 81, "Stewart_Batz5@gmail.com", "Stewart", "DB", 1, "Batz" },
                    { 296, 25, "Kyle17@gmail.com", "Kyle", "DB", 0, "Runte" },
                    { 297, 15, "Cecelia.Grimes32@yahoo.com", "Cecelia", "DB", 1, "Grimes" },
                    { 298, 33, "Eloise93@yahoo.com", "Eloise", "DB", 0, "Hermiston" },
                    { 299, 40, "Marilyn_Emard@hotmail.com", "Marilyn", "DB", 1, "Emard" },
                    { 300, 82, "Bruce_Tromp62@gmail.com", "Bruce", "DB", 1, "Tromp" },
                    { 301, 69, "Melody3@hotmail.com", "Melody", "DB", 0, "Green" },
                    { 302, 53, "Bert_Hintz51@gmail.com", "Bert", "DB", 0, "Hintz" },
                    { 303, 82, "Francis7@gmail.com", "Francis", "DB", 0, "Cole" },
                    { 304, 58, "Lillian.Maggio40@yahoo.com", "Lillian", "DB", 1, "Maggio" },
                    { 305, 47, "Sherry.Walker47@gmail.com", "Sherry", "DB", 0, "Walker" },
                    { 306, 13, "Blake79@gmail.com", "Blake", "DB", 1, "Cummings" },
                    { 307, 60, "Calvin_Swaniawski88@gmail.com", "Calvin", "DB", 1, "Swaniawski" },
                    { 308, 88, "Roger_Stamm@hotmail.com", "Roger", "DB", 1, "Stamm" },
                    { 309, 25, "Darrel13@yahoo.com", "Darrel", "DB", 0, "Boyle" },
                    { 310, 63, "Brooke.Wyman72@hotmail.com", "Brooke", "DB", 1, "Wyman" },
                    { 311, 11, "Billie59@gmail.com", "Billie", "DB", 0, "Kling" },
                    { 312, 22, "Gwendolyn_Hills90@yahoo.com", "Gwendolyn", "DB", 0, "Hills" },
                    { 313, 88, "Terry37@yahoo.com", "Terry", "DB", 1, "Heller" },
                    { 314, 86, "Darryl45@yahoo.com", "Darryl", "DB", 0, "King" },
                    { 315, 76, "Mamie.Botsford@hotmail.com", "Mamie", "DB", 1, "Botsford" },
                    { 316, 42, "Shane82@yahoo.com", "Shane", "DB", 0, "Schmidt" },
                    { 317, 61, "Edwin61@yahoo.com", "Edwin", "DB", 1, "Nitzsche" },
                    { 318, 89, "Bert.Hackett2@hotmail.com", "Bert", "DB", 0, "Hackett" },
                    { 319, 77, "Nick_Ankunding@yahoo.com", "Nick", "DB", 1, "Ankunding" },
                    { 320, 57, "Erick.Nolan@gmail.com", "Erick", "DB", 1, "Nolan" },
                    { 321, 14, "Stephen29@yahoo.com", "Stephen", "DB", 1, "Mitchell" },
                    { 322, 55, "Marguerite8@hotmail.com", "Marguerite", "DB", 1, "Sawayn" },
                    { 323, 24, "Dianna49@gmail.com", "Dianna", "DB", 0, "Moen" },
                    { 324, 88, "Philip_Hermann3@gmail.com", "Philip", "DB", 0, "Hermann" },
                    { 325, 33, "Diana16@gmail.com", "Diana", "DB", 0, "Douglas" },
                    { 326, 79, "Emma12@hotmail.com", "Emma", "DB", 0, "Flatley" },
                    { 327, 85, "Martin_Schoen@gmail.com", "Martin", "DB", 1, "Schoen" },
                    { 328, 30, "Ella26@yahoo.com", "Ella", "DB", 0, "Cremin" },
                    { 329, 14, "Raymond_Welch59@yahoo.com", "Raymond", "DB", 0, "Welch" },
                    { 330, 32, "Cesar_Bogan@gmail.com", "Cesar", "DB", 0, "Bogan" },
                    { 331, 8, "Jaime87@gmail.com", "Jaime", "DB", 0, "Moen" },
                    { 332, 20, "Gertrude.Greenfelder69@hotmail.com", "Gertrude", "DB", 0, "Greenfelder" },
                    { 333, 70, "Opal_Kris@gmail.com", "Opal", "DB", 0, "Kris" },
                    { 334, 47, "Ricardo11@yahoo.com", "Ricardo", "DB", 0, "Koss" },
                    { 335, 21, "Austin_Wolf@yahoo.com", "Austin", "DB", 1, "Wolf" },
                    { 336, 65, "Guadalupe.Baumbach@gmail.com", "Guadalupe", "DB", 0, "Baumbach" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 337, 49, "Arlene_Welch@yahoo.com", "Arlene", "DB", 1, "Welch" },
                    { 338, 19, "Neal.Wyman27@yahoo.com", "Neal", "DB", 1, "Wyman" },
                    { 339, 58, "Mattie_Heller10@gmail.com", "Mattie", "DB", 1, "Heller" },
                    { 340, 75, "Rosalie.Blick71@hotmail.com", "Rosalie", "DB", 1, "Blick" },
                    { 341, 67, "Eva.Beatty15@gmail.com", "Eva", "DB", 1, "Beatty" },
                    { 342, 20, "Rachel16@yahoo.com", "Rachel", "DB", 0, "Ward" },
                    { 343, 10, "Jeannie_Mertz12@gmail.com", "Jeannie", "DB", 0, "Mertz" },
                    { 344, 90, "Lester54@hotmail.com", "Lester", "DB", 0, "Boehm" },
                    { 345, 48, "Kristine_Russel48@hotmail.com", "Kristine", "DB", 1, "Russel" },
                    { 346, 66, "Tonya.Yundt@hotmail.com", "Tonya", "DB", 0, "Yundt" },
                    { 347, 9, "Lionel94@hotmail.com", "Lionel", "DB", 0, "Dietrich" },
                    { 348, 61, "Nathan.Bode39@hotmail.com", "Nathan", "DB", 1, "Bode" },
                    { 349, 36, "Josephine23@hotmail.com", "Josephine", "DB", 0, "Glover" },
                    { 350, 51, "Dexter.Corwin90@hotmail.com", "Dexter", "DB", 1, "Corwin" },
                    { 351, 54, "Lynne64@yahoo.com", "Lynne", "DB", 0, "Fay" },
                    { 352, 26, "Ismael.Heathcote@hotmail.com", "Ismael", "DB", 0, "Heathcote" },
                    { 353, 74, "Rochelle_Gibson@hotmail.com", "Rochelle", "DB", 0, "Gibson" },
                    { 354, 33, "Winifred.Lowe0@gmail.com", "Winifred", "DB", 0, "Lowe" },
                    { 355, 16, "Bernadette_Halvorson97@yahoo.com", "Bernadette", "DB", 1, "Halvorson" },
                    { 356, 21, "Mario.Kovacek78@gmail.com", "Mario", "DB", 0, "Kovacek" },
                    { 357, 58, "Deborah15@hotmail.com", "Deborah", "DB", 0, "Walker" },
                    { 358, 58, "Arlene.Armstrong@yahoo.com", "Arlene", "DB", 1, "Armstrong" },
                    { 359, 46, "Dominic.Ondricka@yahoo.com", "Dominic", "DB", 1, "Ondricka" },
                    { 360, 55, "Alexandra_Wolff@hotmail.com", "Alexandra", "DB", 0, "Wolff" },
                    { 361, 25, "Eula_Bergstrom3@yahoo.com", "Eula", "DB", 1, "Bergstrom" },
                    { 362, 56, "Felicia_Vandervort@hotmail.com", "Felicia", "DB", 0, "Vandervort" },
                    { 363, 33, "Maureen_Ondricka65@hotmail.com", "Maureen", "DB", 1, "Ondricka" },
                    { 364, 35, "Mary41@hotmail.com", "Mary", "DB", 0, "Mann" },
                    { 365, 74, "Danny.Jast97@yahoo.com", "Danny", "DB", 0, "Jast" },
                    { 366, 25, "Sylvester_Corkery@gmail.com", "Sylvester", "DB", 1, "Corkery" },
                    { 367, 21, "Madeline_Carter62@gmail.com", "Madeline", "DB", 1, "Carter" },
                    { 368, 48, "Stephanie.Bayer@yahoo.com", "Stephanie", "DB", 1, "Bayer" },
                    { 369, 13, "Taylor_Kulas92@yahoo.com", "Taylor", "DB", 1, "Kulas" },
                    { 370, 87, "Fred.Leuschke@hotmail.com", "Fred", "DB", 1, "Leuschke" },
                    { 371, 34, "Shannon.Sporer@hotmail.com", "Shannon", "DB", 0, "Sporer" },
                    { 372, 64, "Philip12@yahoo.com", "Philip", "DB", 1, "Dickinson" },
                    { 373, 18, "Stella55@gmail.com", "Stella", "DB", 0, "Watsica" },
                    { 374, 28, "Kim_Kessler39@hotmail.com", "Kim", "DB", 0, "Kessler" },
                    { 375, 38, "Ruben_Senger@gmail.com", "Ruben", "DB", 0, "Senger" },
                    { 376, 66, "Marjorie.Reinger@hotmail.com", "Marjorie", "DB", 1, "Reinger" },
                    { 377, 8, "Alvin67@yahoo.com", "Alvin", "DB", 1, "Schultz" },
                    { 378, 89, "Stephanie.Lowe61@hotmail.com", "Stephanie", "DB", 1, "Lowe" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 379, 90, "Daniel_Von34@yahoo.com", "Daniel", "DB", 1, "Von" },
                    { 380, 37, "Gina_Langosh30@yahoo.com", "Gina", "DB", 0, "Langosh" },
                    { 381, 25, "Willard87@yahoo.com", "Willard", "DB", 0, "Carroll" },
                    { 382, 41, "Wm99@gmail.com", "Wm", "DB", 0, "Lehner" },
                    { 383, 89, "Mable_Hand35@yahoo.com", "Mable", "DB", 1, "Hand" },
                    { 384, 16, "Ramon.Mosciski@gmail.com", "Ramon", "DB", 1, "Mosciski" },
                    { 385, 89, "Casey.Dibbert9@hotmail.com", "Casey", "DB", 1, "Dibbert" },
                    { 386, 24, "Howard.McKenzie@gmail.com", "Howard", "DB", 1, "McKenzie" },
                    { 387, 74, "Ida_Toy52@hotmail.com", "Ida", "DB", 0, "Toy" },
                    { 388, 9, "Travis_Rodriguez@gmail.com", "Travis", "DB", 1, "Rodriguez" },
                    { 389, 75, "Joey26@yahoo.com", "Joey", "DB", 0, "Douglas" },
                    { 390, 89, "Willie.Heathcote@hotmail.com", "Willie", "DB", 0, "Heathcote" },
                    { 391, 50, "Donnie39@hotmail.com", "Donnie", "DB", 1, "Fay" },
                    { 392, 51, "Oliver_Kuvalis18@hotmail.com", "Oliver", "DB", 1, "Kuvalis" },
                    { 393, 51, "Woodrow39@yahoo.com", "Woodrow", "DB", 1, "Kohler" },
                    { 394, 86, "Vickie64@hotmail.com", "Vickie", "DB", 1, "Bernhard" },
                    { 395, 52, "Abel34@yahoo.com", "Abel", "DB", 0, "Purdy" },
                    { 396, 72, "Sammy_Yost@gmail.com", "Sammy", "DB", 1, "Yost" },
                    { 397, 27, "Brandy22@gmail.com", "Brandy", "DB", 1, "Walter" },
                    { 398, 16, "Shirley79@yahoo.com", "Shirley", "DB", 1, "Lindgren" },
                    { 399, 40, "Kathleen_Mraz67@yahoo.com", "Kathleen", "DB", 0, "Mraz" },
                    { 400, 66, "Joan.Senger@gmail.com", "Joan", "DB", 0, "Senger" },
                    { 401, 21, "Catherine.Lindgren32@yahoo.com", "Catherine", "DB", 1, "Lindgren" },
                    { 402, 40, "Chris27@gmail.com", "Chris", "DB", 1, "Brekke" },
                    { 403, 54, "Anne_Doyle72@hotmail.com", "Anne", "DB", 0, "Doyle" },
                    { 404, 74, "Randolph_Christiansen@yahoo.com", "Randolph", "DB", 1, "Christiansen" },
                    { 405, 32, "Sherman_Bogan@yahoo.com", "Sherman", "DB", 1, "Bogan" },
                    { 406, 20, "Delia32@hotmail.com", "Delia", "DB", 1, "Wuckert" },
                    { 407, 23, "Jon.Anderson@gmail.com", "Jon", "DB", 1, "Anderson" },
                    { 408, 45, "Carolyn.Christiansen14@hotmail.com", "Carolyn", "DB", 0, "Christiansen" },
                    { 409, 15, "Donna_Auer3@yahoo.com", "Donna", "DB", 0, "Auer" },
                    { 410, 61, "Madeline92@yahoo.com", "Madeline", "DB", 1, "Pollich" },
                    { 411, 79, "Michele_Veum48@yahoo.com", "Michele", "DB", 1, "Veum" },
                    { 412, 40, "Danielle_Dibbert@yahoo.com", "Danielle", "DB", 1, "Dibbert" },
                    { 413, 29, "Willis_Rice25@hotmail.com", "Willis", "DB", 0, "Rice" },
                    { 414, 88, "Everett68@gmail.com", "Everett", "DB", 1, "Aufderhar" },
                    { 415, 43, "Rosemary.Beahan@hotmail.com", "Rosemary", "DB", 0, "Beahan" },
                    { 416, 90, "Arnold42@yahoo.com", "Arnold", "DB", 1, "Lindgren" },
                    { 417, 43, "Forrest49@yahoo.com", "Forrest", "DB", 1, "Corkery" },
                    { 418, 18, "Garrett_Reichert@hotmail.com", "Garrett", "DB", 1, "Reichert" },
                    { 419, 11, "Alonzo20@hotmail.com", "Alonzo", "DB", 0, "Kuhlman" },
                    { 420, 44, "Edgar_Kessler@hotmail.com", "Edgar", "DB", 0, "Kessler" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 421, 54, "Pete.Hackett@gmail.com", "Pete", "DB", 1, "Hackett" },
                    { 422, 82, "Bobbie81@yahoo.com", "Bobbie", "DB", 0, "Kuhlman" },
                    { 423, 27, "Mandy_Schmidt@hotmail.com", "Mandy", "DB", 0, "Schmidt" },
                    { 424, 28, "Carlton.Braun@hotmail.com", "Carlton", "DB", 1, "Braun" },
                    { 425, 15, "Irvin.Hayes45@hotmail.com", "Irvin", "DB", 0, "Hayes" },
                    { 426, 40, "Earnest_Monahan55@yahoo.com", "Earnest", "DB", 1, "Monahan" },
                    { 427, 14, "Ruth.Schmeler@yahoo.com", "Ruth", "DB", 1, "Schmeler" },
                    { 428, 17, "Vicki92@yahoo.com", "Vicki", "DB", 1, "Price" },
                    { 429, 44, "Jeffery_Oberbrunner@yahoo.com", "Jeffery", "DB", 1, "Oberbrunner" },
                    { 430, 24, "Tammy94@yahoo.com", "Tammy", "DB", 0, "Ankunding" },
                    { 431, 81, "June.Dare@yahoo.com", "June", "DB", 1, "Dare" },
                    { 432, 29, "Spencer98@gmail.com", "Spencer", "DB", 1, "Effertz" },
                    { 433, 57, "Terry_Ondricka@hotmail.com", "Terry", "DB", 0, "Ondricka" },
                    { 434, 37, "Constance_Lowe@gmail.com", "Constance", "DB", 1, "Lowe" },
                    { 435, 27, "Jill.Hackett@gmail.com", "Jill", "DB", 0, "Hackett" },
                    { 436, 73, "Harry_Rath@yahoo.com", "Harry", "DB", 1, "Rath" },
                    { 437, 51, "Arturo10@yahoo.com", "Arturo", "DB", 1, "Pfeffer" },
                    { 438, 78, "Domingo26@yahoo.com", "Domingo", "DB", 0, "Kris" },
                    { 439, 54, "Caleb_Gerhold@gmail.com", "Caleb", "DB", 1, "Gerhold" },
                    { 440, 20, "Sue_Funk23@hotmail.com", "Sue", "DB", 1, "Funk" },
                    { 441, 54, "Brent_Hermann74@gmail.com", "Brent", "DB", 1, "Hermann" },
                    { 442, 72, "Jesus_Lakin68@hotmail.com", "Jesus", "DB", 1, "Lakin" },
                    { 443, 31, "Peggy.Kiehn@hotmail.com", "Peggy", "DB", 0, "Kiehn" },
                    { 444, 16, "Alfonso.McDermott@hotmail.com", "Alfonso", "DB", 0, "McDermott" },
                    { 445, 29, "Cecil11@hotmail.com", "Cecil", "DB", 1, "Veum" },
                    { 446, 72, "Larry13@hotmail.com", "Larry", "DB", 0, "Prosacco" },
                    { 447, 47, "Amos_Prosacco@gmail.com", "Amos", "DB", 1, "Prosacco" },
                    { 448, 79, "Tomas9@gmail.com", "Tomas", "DB", 1, "Satterfield" },
                    { 449, 21, "Justin_Beer@gmail.com", "Justin", "DB", 1, "Beer" },
                    { 450, 26, "Lila.Price34@hotmail.com", "Lila", "DB", 0, "Price" },
                    { 451, 87, "Melvin.Schimmel@gmail.com", "Melvin", "DB", 1, "Schimmel" },
                    { 452, 51, "Bertha15@hotmail.com", "Bertha", "DB", 1, "Kohler" },
                    { 453, 33, "Elena.Champlin2@hotmail.com", "Elena", "DB", 1, "Champlin" },
                    { 454, 21, "Leona63@gmail.com", "Leona", "DB", 0, "Spencer" },
                    { 455, 82, "Jan58@gmail.com", "Jan", "DB", 0, "Greenfelder" },
                    { 456, 83, "Bradley_Block@yahoo.com", "Bradley", "DB", 1, "Block" },
                    { 457, 14, "Jeremiah_Maggio@yahoo.com", "Jeremiah", "DB", 0, "Maggio" },
                    { 458, 82, "Catherine.Yost59@gmail.com", "Catherine", "DB", 0, "Yost" },
                    { 459, 86, "Aubrey_Gorczany44@yahoo.com", "Aubrey", "DB", 0, "Gorczany" },
                    { 460, 29, "Kathleen54@yahoo.com", "Kathleen", "DB", 0, "Altenwerth" },
                    { 461, 59, "Kelley79@gmail.com", "Kelley", "DB", 1, "Mayert" },
                    { 462, 53, "Jasmine_Dach82@hotmail.com", "Jasmine", "DB", 0, "Dach" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 463, 27, "Marguerite56@hotmail.com", "Marguerite", "DB", 1, "Olson" },
                    { 464, 49, "Lionel2@hotmail.com", "Lionel", "DB", 1, "Tillman" },
                    { 465, 37, "Laurence22@gmail.com", "Laurence", "DB", 1, "Ankunding" },
                    { 466, 12, "Florence_Goodwin40@hotmail.com", "Florence", "DB", 0, "Goodwin" },
                    { 467, 56, "Otis.Feil@gmail.com", "Otis", "DB", 1, "Feil" },
                    { 468, 12, "Doreen95@yahoo.com", "Doreen", "DB", 0, "Harber" },
                    { 469, 28, "Erica79@hotmail.com", "Erica", "DB", 0, "Bins" },
                    { 470, 49, "Ernest_Jacobi@yahoo.com", "Ernest", "DB", 1, "Jacobi" },
                    { 471, 28, "Meredith_Kris@hotmail.com", "Meredith", "DB", 0, "Kris" },
                    { 472, 40, "Ann_Price@gmail.com", "Ann", "DB", 0, "Price" },
                    { 473, 90, "Candace38@hotmail.com", "Candace", "DB", 1, "Walter" },
                    { 474, 28, "Edna_Kuhlman17@hotmail.com", "Edna", "DB", 1, "Kuhlman" },
                    { 475, 37, "Barbara_Kling@gmail.com", "Barbara", "DB", 1, "Kling" },
                    { 476, 81, "Roland.Cormier81@gmail.com", "Roland", "DB", 1, "Cormier" },
                    { 477, 45, "Karla_Abernathy@gmail.com", "Karla", "DB", 0, "Abernathy" },
                    { 478, 23, "Jesse_Dickinson10@gmail.com", "Jesse", "DB", 0, "Dickinson" },
                    { 479, 22, "Geneva65@hotmail.com", "Geneva", "DB", 0, "O'Kon" },
                    { 480, 44, "Garry3@gmail.com", "Garry", "DB", 1, "Pouros" },
                    { 481, 18, "Stacy_Kemmer7@yahoo.com", "Stacy", "DB", 0, "Kemmer" },
                    { 482, 43, "Amanda.Sawayn88@yahoo.com", "Amanda", "DB", 1, "Sawayn" },
                    { 483, 13, "Erin_Schulist@gmail.com", "Erin", "DB", 1, "Schulist" },
                    { 484, 49, "Spencer.Flatley@yahoo.com", "Spencer", "DB", 1, "Flatley" },
                    { 485, 65, "Kristen31@hotmail.com", "Kristen", "DB", 0, "Stroman" },
                    { 486, 33, "Tracy_Lockman@gmail.com", "Tracy", "DB", 0, "Lockman" },
                    { 487, 77, "Fredrick.Kunde@gmail.com", "Fredrick", "DB", 1, "Kunde" },
                    { 488, 74, "Ernesto94@gmail.com", "Ernesto", "DB", 1, "Friesen" },
                    { 489, 50, "Meghan.Blick@yahoo.com", "Meghan", "DB", 1, "Blick" },
                    { 490, 76, "Ruth_Price97@gmail.com", "Ruth", "DB", 0, "Price" },
                    { 491, 14, "Jordan.Pollich48@yahoo.com", "Jordan", "DB", 0, "Pollich" },
                    { 492, 47, "Rita.Aufderhar37@hotmail.com", "Rita", "DB", 1, "Aufderhar" },
                    { 493, 74, "Ernestine.OKon@hotmail.com", "Ernestine", "DB", 1, "O'Kon" },
                    { 494, 81, "Rebecca.Stracke@hotmail.com", "Rebecca", "DB", 1, "Stracke" },
                    { 495, 85, "Kristy_Corkery@yahoo.com", "Kristy", "DB", 1, "Corkery" },
                    { 496, 49, "Archie_Price@yahoo.com", "Archie", "DB", 0, "Price" },
                    { 497, 57, "Joshua.Kirlin@yahoo.com", "Joshua", "DB", 1, "Kirlin" },
                    { 498, 18, "Hilda.Grant86@gmail.com", "Hilda", "DB", 1, "Grant" },
                    { 499, 35, "Terrance_Padberg@yahoo.com", "Terrance", "DB", 1, "Padberg" },
                    { 500, 43, "Estelle_Sawayn@hotmail.com", "Estelle", "DB", 0, "Sawayn" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
