using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace minAPI.Migrations
{
    public partial class create : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    FirstName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LastName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Age = table.Column<int>(type: "int", nullable: false),
                    Email = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Gender = table.Column<int>(type: "int", nullable: false),
                    Framework = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 1, 57, "Clifton.Toy61@yahoo.com", "Clifton", "DB", 0, "Toy" },
                    { 2, 11, "Clara.Heaney@yahoo.com", "Clara", "DB", 0, "Heaney" },
                    { 3, 61, "Herbert_Quitzon69@yahoo.com", "Herbert", "DB", 0, "Quitzon" },
                    { 4, 24, "Laurie.Kessler@yahoo.com", "Laurie", "DB", 1, "Kessler" },
                    { 5, 53, "Sandy69@hotmail.com", "Sandy", "DB", 1, "Wolf" },
                    { 6, 45, "Timmy_Blanda21@hotmail.com", "Timmy", "DB", 1, "Blanda" },
                    { 7, 60, "Toby51@gmail.com", "Toby", "DB", 1, "Kuhn" },
                    { 8, 68, "Joseph54@hotmail.com", "Joseph", "DB", 1, "Lubowitz" },
                    { 9, 73, "Nelson68@gmail.com", "Nelson", "DB", 0, "Hilpert" },
                    { 10, 73, "Lula.Quitzon37@yahoo.com", "Lula", "DB", 0, "Quitzon" },
                    { 11, 9, "Wayne_VonRueden8@yahoo.com", "Wayne", "DB", 0, "VonRueden" },
                    { 12, 26, "Wade_Fadel@yahoo.com", "Wade", "DB", 0, "Fadel" },
                    { 13, 10, "Opal_Lueilwitz@yahoo.com", "Opal", "DB", 0, "Lueilwitz" },
                    { 14, 67, "Clark_Harber52@gmail.com", "Clark", "DB", 1, "Harber" },
                    { 15, 82, "Michelle.Roob@gmail.com", "Michelle", "DB", 0, "Roob" },
                    { 16, 73, "Elizabeth_Gibson@yahoo.com", "Elizabeth", "DB", 0, "Gibson" },
                    { 17, 36, "Rosemarie_Ferry@hotmail.com", "Rosemarie", "DB", 0, "Ferry" },
                    { 18, 36, "Casey_Lowe67@hotmail.com", "Casey", "DB", 1, "Lowe" },
                    { 19, 77, "Miguel42@hotmail.com", "Miguel", "DB", 1, "Mayert" },
                    { 20, 41, "Ron_Mayert@gmail.com", "Ron", "DB", 1, "Mayert" },
                    { 21, 15, "Connie98@yahoo.com", "Connie", "DB", 0, "Klocko" },
                    { 22, 59, "Moses.Smith@yahoo.com", "Moses", "DB", 0, "Smith" },
                    { 23, 82, "Patti_Heidenreich@yahoo.com", "Patti", "DB", 0, "Heidenreich" },
                    { 24, 22, "Reginald_Hilpert@yahoo.com", "Reginald", "DB", 1, "Hilpert" },
                    { 25, 78, "Gordon_Stoltenberg31@yahoo.com", "Gordon", "DB", 1, "Stoltenberg" },
                    { 26, 80, "Olive_Keeling24@gmail.com", "Olive", "DB", 0, "Keeling" },
                    { 27, 16, "Emilio.Hagenes75@hotmail.com", "Emilio", "DB", 0, "Hagenes" },
                    { 28, 23, "Dallas71@yahoo.com", "Dallas", "DB", 0, "Lubowitz" },
                    { 29, 38, "Tamara.Murphy94@hotmail.com", "Tamara", "DB", 1, "Murphy" },
                    { 30, 55, "Cathy37@yahoo.com", "Cathy", "DB", 0, "Kunze" },
                    { 31, 8, "Homer35@gmail.com", "Homer", "DB", 1, "O'Hara" },
                    { 32, 12, "Dora.Abernathy72@yahoo.com", "Dora", "DB", 1, "Abernathy" },
                    { 33, 89, "Kari.Schowalter78@hotmail.com", "Kari", "DB", 1, "Schowalter" },
                    { 34, 67, "Bernard_Dickens@hotmail.com", "Bernard", "DB", 0, "Dickens" },
                    { 35, 33, "Byron.Lindgren92@yahoo.com", "Byron", "DB", 0, "Lindgren" },
                    { 36, 13, "Gwen.Mitchell1@hotmail.com", "Gwen", "DB", 1, "Mitchell" },
                    { 37, 17, "Brad.Runolfsdottir64@gmail.com", "Brad", "DB", 0, "Runolfsdottir" },
                    { 38, 39, "Phyllis_Wuckert66@hotmail.com", "Phyllis", "DB", 1, "Wuckert" },
                    { 39, 40, "Frankie12@gmail.com", "Frankie", "DB", 1, "Olson" },
                    { 40, 89, "Nick.Williamson42@hotmail.com", "Nick", "DB", 1, "Williamson" },
                    { 41, 37, "Lionel_Jerde82@hotmail.com", "Lionel", "DB", 1, "Jerde" },
                    { 42, 26, "Jacqueline.Jerde@gmail.com", "Jacqueline", "DB", 0, "Jerde" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 43, 72, "Guillermo80@hotmail.com", "Guillermo", "DB", 1, "Armstrong" },
                    { 44, 71, "Lynette_Stroman@hotmail.com", "Lynette", "DB", 1, "Stroman" },
                    { 45, 62, "Rhonda48@yahoo.com", "Rhonda", "DB", 1, "Gibson" },
                    { 46, 59, "Taylor.Swaniawski12@gmail.com", "Taylor", "DB", 0, "Swaniawski" },
                    { 47, 30, "Jonathon_Ebert21@hotmail.com", "Jonathon", "DB", 0, "Ebert" },
                    { 48, 35, "Hope.Luettgen69@yahoo.com", "Hope", "DB", 0, "Luettgen" },
                    { 49, 90, "Renee_Effertz16@yahoo.com", "Renee", "DB", 1, "Effertz" },
                    { 50, 8, "Jody.Bode78@hotmail.com", "Jody", "DB", 1, "Bode" },
                    { 51, 88, "Rebecca_Dach24@yahoo.com", "Rebecca", "DB", 0, "Dach" },
                    { 52, 53, "May_Sipes26@hotmail.com", "May", "DB", 1, "Sipes" },
                    { 53, 72, "Sonia.Crist@hotmail.com", "Sonia", "DB", 0, "Crist" },
                    { 54, 56, "Eduardo.Marks@yahoo.com", "Eduardo", "DB", 1, "Marks" },
                    { 55, 82, "Katherine92@gmail.com", "Katherine", "DB", 1, "Bernhard" },
                    { 56, 41, "Bessie16@yahoo.com", "Bessie", "DB", 1, "Upton" },
                    { 57, 51, "Greg51@gmail.com", "Greg", "DB", 1, "Lockman" },
                    { 58, 86, "Eleanor.Grady42@hotmail.com", "Eleanor", "DB", 1, "Grady" },
                    { 59, 23, "Gwendolyn20@yahoo.com", "Gwendolyn", "DB", 0, "Harvey" },
                    { 60, 56, "Ramiro66@yahoo.com", "Ramiro", "DB", 0, "Waters" },
                    { 61, 70, "Karl16@hotmail.com", "Karl", "DB", 1, "Denesik" },
                    { 62, 21, "Jennie.Effertz@gmail.com", "Jennie", "DB", 0, "Effertz" },
                    { 63, 71, "Penny_Larson65@hotmail.com", "Penny", "DB", 0, "Larson" },
                    { 64, 42, "Minnie58@gmail.com", "Minnie", "DB", 0, "Bogan" },
                    { 65, 40, "Rex_Cummings@yahoo.com", "Rex", "DB", 0, "Cummings" },
                    { 66, 45, "Alexander_Pfeffer32@gmail.com", "Alexander", "DB", 1, "Pfeffer" },
                    { 67, 18, "Darnell_Kohler@hotmail.com", "Darnell", "DB", 0, "Kohler" },
                    { 68, 79, "Desiree.Stiedemann17@hotmail.com", "Desiree", "DB", 1, "Stiedemann" },
                    { 69, 19, "Patrick_Harvey@gmail.com", "Patrick", "DB", 0, "Harvey" },
                    { 70, 17, "Otis.Collier@gmail.com", "Otis", "DB", 0, "Collier" },
                    { 71, 70, "Mark_Gusikowski@hotmail.com", "Mark", "DB", 0, "Gusikowski" },
                    { 72, 83, "Leonard.Collier87@hotmail.com", "Leonard", "DB", 0, "Collier" },
                    { 73, 33, "Preston.Waters68@yahoo.com", "Preston", "DB", 1, "Waters" },
                    { 74, 62, "Pam_Jacobson11@hotmail.com", "Pam", "DB", 0, "Jacobson" },
                    { 75, 82, "Derrick_Anderson@hotmail.com", "Derrick", "DB", 0, "Anderson" },
                    { 76, 15, "Ian.Ferry@hotmail.com", "Ian", "DB", 0, "Ferry" },
                    { 77, 30, "Max.Stamm54@yahoo.com", "Max", "DB", 0, "Stamm" },
                    { 78, 38, "Faye_Becker@yahoo.com", "Faye", "DB", 0, "Becker" },
                    { 79, 41, "Cory_Heidenreich@gmail.com", "Cory", "DB", 0, "Heidenreich" },
                    { 80, 34, "Sheryl83@hotmail.com", "Sheryl", "DB", 0, "King" },
                    { 81, 17, "Jonathan_Daugherty@yahoo.com", "Jonathan", "DB", 0, "Daugherty" },
                    { 82, 44, "Ramona.Parisian@gmail.com", "Ramona", "DB", 0, "Parisian" },
                    { 83, 45, "Marjorie35@gmail.com", "Marjorie", "DB", 1, "Kirlin" },
                    { 84, 69, "Arthur48@hotmail.com", "Arthur", "DB", 0, "Littel" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 85, 37, "Whitney_Mueller60@yahoo.com", "Whitney", "DB", 1, "Mueller" },
                    { 86, 64, "Johnny_Graham12@gmail.com", "Johnny", "DB", 0, "Graham" },
                    { 87, 28, "Nadine75@gmail.com", "Nadine", "DB", 1, "Lind" },
                    { 88, 57, "Myrtle_Fahey@hotmail.com", "Myrtle", "DB", 1, "Fahey" },
                    { 89, 14, "Ethel.Balistreri95@yahoo.com", "Ethel", "DB", 1, "Balistreri" },
                    { 90, 54, "Sonja.Pouros@hotmail.com", "Sonja", "DB", 0, "Pouros" },
                    { 91, 10, "Eric.Klocko@hotmail.com", "Eric", "DB", 1, "Klocko" },
                    { 92, 60, "Pearl.Hilpert@yahoo.com", "Pearl", "DB", 1, "Hilpert" },
                    { 93, 18, "Irma_Towne@gmail.com", "Irma", "DB", 1, "Towne" },
                    { 94, 47, "Antonia_Franecki@gmail.com", "Antonia", "DB", 1, "Franecki" },
                    { 95, 16, "Rex_Strosin26@yahoo.com", "Rex", "DB", 1, "Strosin" },
                    { 96, 61, "Annette.Ortiz8@hotmail.com", "Annette", "DB", 0, "Ortiz" },
                    { 97, 53, "Guillermo.Jacobi90@yahoo.com", "Guillermo", "DB", 0, "Jacobi" },
                    { 98, 19, "Damon_Brown@gmail.com", "Damon", "DB", 0, "Brown" },
                    { 99, 9, "Janet42@hotmail.com", "Janet", "DB", 1, "Romaguera" },
                    { 100, 26, "Aaron_Gibson@yahoo.com", "Aaron", "DB", 1, "Gibson" },
                    { 101, 90, "Joey_Lakin@yahoo.com", "Joey", "DB", 0, "Lakin" },
                    { 102, 64, "May51@hotmail.com", "May", "DB", 1, "Glover" },
                    { 103, 57, "Julio.Beahan52@gmail.com", "Julio", "DB", 1, "Beahan" },
                    { 104, 63, "Shannon71@hotmail.com", "Shannon", "DB", 1, "Veum" },
                    { 105, 54, "Eloise.Bayer14@hotmail.com", "Eloise", "DB", 0, "Bayer" },
                    { 106, 30, "Jenna_Tillman83@gmail.com", "Jenna", "DB", 1, "Tillman" },
                    { 107, 52, "Judith_Kohler67@gmail.com", "Judith", "DB", 0, "Kohler" },
                    { 108, 20, "Marco_Streich@gmail.com", "Marco", "DB", 1, "Streich" },
                    { 109, 79, "Garrett.Renner28@hotmail.com", "Garrett", "DB", 0, "Renner" },
                    { 110, 88, "Moses.Johnson@gmail.com", "Moses", "DB", 0, "Johnson" },
                    { 111, 25, "Harold_Lemke@gmail.com", "Harold", "DB", 0, "Lemke" },
                    { 112, 49, "Amber.Hand76@hotmail.com", "Amber", "DB", 1, "Hand" },
                    { 113, 11, "Gerard_Quitzon42@hotmail.com", "Gerard", "DB", 1, "Quitzon" },
                    { 114, 64, "Jeremiah65@hotmail.com", "Jeremiah", "DB", 0, "Hirthe" },
                    { 115, 50, "Craig_Aufderhar@gmail.com", "Craig", "DB", 1, "Aufderhar" },
                    { 116, 43, "Eunice24@yahoo.com", "Eunice", "DB", 1, "Turcotte" },
                    { 117, 12, "Milton9@gmail.com", "Milton", "DB", 1, "Rice" },
                    { 118, 27, "Ruby_Fisher@hotmail.com", "Ruby", "DB", 1, "Fisher" },
                    { 119, 87, "Willie77@gmail.com", "Willie", "DB", 1, "Hilpert" },
                    { 120, 37, "Tina_Beer43@yahoo.com", "Tina", "DB", 0, "Beer" },
                    { 121, 76, "Larry.Heller25@hotmail.com", "Larry", "DB", 0, "Heller" },
                    { 122, 44, "Johnnie_Abshire68@yahoo.com", "Johnnie", "DB", 1, "Abshire" },
                    { 123, 52, "Catherine77@hotmail.com", "Catherine", "DB", 0, "Raynor" },
                    { 124, 39, "Christina.Quitzon54@yahoo.com", "Christina", "DB", 1, "Quitzon" },
                    { 125, 52, "Randy_Ryan80@yahoo.com", "Randy", "DB", 0, "Ryan" },
                    { 126, 49, "Edwin_Yost@yahoo.com", "Edwin", "DB", 0, "Yost" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 127, 43, "Dianna_Harber@yahoo.com", "Dianna", "DB", 0, "Harber" },
                    { 128, 89, "Lowell_Conroy@gmail.com", "Lowell", "DB", 0, "Conroy" },
                    { 129, 66, "Donnie.McCullough@hotmail.com", "Donnie", "DB", 0, "McCullough" },
                    { 130, 23, "Gustavo.Leffler@gmail.com", "Gustavo", "DB", 0, "Leffler" },
                    { 131, 41, "Lorenzo44@yahoo.com", "Lorenzo", "DB", 1, "Sanford" },
                    { 132, 61, "Traci61@hotmail.com", "Traci", "DB", 0, "Borer" },
                    { 133, 54, "Gloria23@hotmail.com", "Gloria", "DB", 1, "Pouros" },
                    { 134, 34, "Leona.Littel@yahoo.com", "Leona", "DB", 0, "Littel" },
                    { 135, 58, "Della_Bernier57@gmail.com", "Della", "DB", 1, "Bernier" },
                    { 136, 20, "Delores.Koelpin91@gmail.com", "Delores", "DB", 1, "Koelpin" },
                    { 137, 53, "Glenda.Schmeler77@gmail.com", "Glenda", "DB", 1, "Schmeler" },
                    { 138, 35, "Sabrina.Marks18@hotmail.com", "Sabrina", "DB", 0, "Marks" },
                    { 139, 56, "Bill73@yahoo.com", "Bill", "DB", 0, "Bernhard" },
                    { 140, 22, "Ian_Kirlin27@hotmail.com", "Ian", "DB", 0, "Kirlin" },
                    { 141, 33, "Brooke_Mraz47@hotmail.com", "Brooke", "DB", 0, "Mraz" },
                    { 142, 84, "Mitchell.Tremblay@yahoo.com", "Mitchell", "DB", 0, "Tremblay" },
                    { 143, 36, "Vickie_Heidenreich@yahoo.com", "Vickie", "DB", 0, "Heidenreich" },
                    { 144, 73, "Lynette_Lowe76@yahoo.com", "Lynette", "DB", 1, "Lowe" },
                    { 145, 60, "Holly2@yahoo.com", "Holly", "DB", 0, "Anderson" },
                    { 146, 17, "Lorene.Larson72@yahoo.com", "Lorene", "DB", 0, "Larson" },
                    { 147, 44, "Helen_Hintz94@hotmail.com", "Helen", "DB", 0, "Hintz" },
                    { 148, 90, "Jose.Smith31@gmail.com", "Jose", "DB", 0, "Smith" },
                    { 149, 37, "Barry3@gmail.com", "Barry", "DB", 1, "Oberbrunner" },
                    { 150, 72, "Alma.Friesen@yahoo.com", "Alma", "DB", 1, "Friesen" },
                    { 151, 81, "Ira_Flatley@gmail.com", "Ira", "DB", 1, "Flatley" },
                    { 152, 66, "John_Bogisich23@hotmail.com", "John", "DB", 0, "Bogisich" },
                    { 153, 18, "Sheri.Dietrich@hotmail.com", "Sheri", "DB", 0, "Dietrich" },
                    { 154, 80, "Kurt_Hills65@gmail.com", "Kurt", "DB", 0, "Hills" },
                    { 155, 13, "Morris.Anderson@gmail.com", "Morris", "DB", 0, "Anderson" },
                    { 156, 79, "Bridget_Douglas57@yahoo.com", "Bridget", "DB", 0, "Douglas" },
                    { 157, 10, "Alfonso_Emard34@yahoo.com", "Alfonso", "DB", 0, "Emard" },
                    { 158, 8, "Sabrina40@yahoo.com", "Sabrina", "DB", 1, "Anderson" },
                    { 159, 57, "Alton_Cassin86@gmail.com", "Alton", "DB", 0, "Cassin" },
                    { 160, 19, "Brandon56@hotmail.com", "Brandon", "DB", 1, "Brakus" },
                    { 161, 36, "Patty.Sawayn58@hotmail.com", "Patty", "DB", 0, "Sawayn" },
                    { 162, 37, "Bobby.Little@gmail.com", "Bobby", "DB", 0, "Little" },
                    { 163, 12, "Corey.Schneider@yahoo.com", "Corey", "DB", 1, "Schneider" },
                    { 164, 68, "Archie62@hotmail.com", "Archie", "DB", 1, "Dickens" },
                    { 165, 45, "Dallas.Lemke@hotmail.com", "Dallas", "DB", 0, "Lemke" },
                    { 166, 10, "Myrtle.Ziemann15@yahoo.com", "Myrtle", "DB", 1, "Ziemann" },
                    { 167, 76, "Alma73@hotmail.com", "Alma", "DB", 1, "Gleichner" },
                    { 168, 44, "Neal_Walsh@hotmail.com", "Neal", "DB", 0, "Walsh" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 169, 76, "Kristen_Lindgren@gmail.com", "Kristen", "DB", 1, "Lindgren" },
                    { 170, 55, "Timmy_Harris78@yahoo.com", "Timmy", "DB", 1, "Harris" },
                    { 171, 71, "Guillermo28@hotmail.com", "Guillermo", "DB", 0, "Jaskolski" },
                    { 172, 22, "Candice42@hotmail.com", "Candice", "DB", 0, "Okuneva" },
                    { 173, 65, "Bernadette55@gmail.com", "Bernadette", "DB", 1, "Reichert" },
                    { 174, 50, "Christopher_Rohan@yahoo.com", "Christopher", "DB", 1, "Rohan" },
                    { 175, 18, "Vickie_Hauck@hotmail.com", "Vickie", "DB", 0, "Hauck" },
                    { 176, 33, "Ernest57@hotmail.com", "Ernest", "DB", 1, "Crona" },
                    { 177, 78, "Joyce50@hotmail.com", "Joyce", "DB", 1, "Mayer" },
                    { 178, 54, "Dora8@yahoo.com", "Dora", "DB", 1, "Schroeder" },
                    { 179, 8, "Wilbert6@yahoo.com", "Wilbert", "DB", 1, "Howell" },
                    { 180, 23, "Rene81@yahoo.com", "Rene", "DB", 1, "Franecki" },
                    { 181, 52, "Alejandro.Fay42@gmail.com", "Alejandro", "DB", 1, "Fay" },
                    { 182, 77, "Mattie.Schaefer@hotmail.com", "Mattie", "DB", 0, "Schaefer" },
                    { 183, 52, "Beverly_Tromp9@hotmail.com", "Beverly", "DB", 1, "Tromp" },
                    { 184, 68, "Debra_Jones95@yahoo.com", "Debra", "DB", 1, "Jones" },
                    { 185, 43, "Janet5@yahoo.com", "Janet", "DB", 1, "Mayert" },
                    { 186, 73, "Beth84@yahoo.com", "Beth", "DB", 0, "Bauch" },
                    { 187, 27, "Benny_Stroman81@yahoo.com", "Benny", "DB", 1, "Stroman" },
                    { 188, 21, "Sabrina.Casper74@yahoo.com", "Sabrina", "DB", 1, "Casper" },
                    { 189, 42, "Essie58@gmail.com", "Essie", "DB", 1, "Kuhn" },
                    { 190, 62, "Molly_Vandervort92@yahoo.com", "Molly", "DB", 1, "Vandervort" },
                    { 191, 75, "Randal0@gmail.com", "Randal", "DB", 0, "Beer" },
                    { 192, 42, "Lindsay.Daugherty63@hotmail.com", "Lindsay", "DB", 1, "Daugherty" },
                    { 193, 54, "Freda.Luettgen73@yahoo.com", "Freda", "DB", 0, "Luettgen" },
                    { 194, 53, "Raul.Miller@gmail.com", "Raul", "DB", 0, "Miller" },
                    { 195, 80, "Emily_Armstrong2@gmail.com", "Emily", "DB", 0, "Armstrong" },
                    { 196, 81, "Winston_MacGyver@hotmail.com", "Winston", "DB", 1, "MacGyver" },
                    { 197, 71, "Olive_Roberts@gmail.com", "Olive", "DB", 0, "Roberts" },
                    { 198, 63, "Karen_Harber@gmail.com", "Karen", "DB", 0, "Harber" },
                    { 199, 77, "Charlie_Bednar83@hotmail.com", "Charlie", "DB", 1, "Bednar" },
                    { 200, 59, "Ronnie_Donnelly81@gmail.com", "Ronnie", "DB", 0, "Donnelly" },
                    { 201, 27, "Alicia30@hotmail.com", "Alicia", "DB", 1, "Emard" },
                    { 202, 40, "Marion.Terry66@hotmail.com", "Marion", "DB", 0, "Terry" },
                    { 203, 24, "Grant.Bailey@yahoo.com", "Grant", "DB", 0, "Bailey" },
                    { 204, 68, "Toby6@yahoo.com", "Toby", "DB", 0, "Mayert" },
                    { 205, 28, "Elaine.Purdy@yahoo.com", "Elaine", "DB", 0, "Purdy" },
                    { 206, 58, "Johnny_Bradtke87@gmail.com", "Johnny", "DB", 1, "Bradtke" },
                    { 207, 73, "Marshall18@yahoo.com", "Marshall", "DB", 0, "Hartmann" },
                    { 208, 49, "Velma56@hotmail.com", "Velma", "DB", 1, "Zulauf" },
                    { 209, 42, "Cindy_Kassulke22@gmail.com", "Cindy", "DB", 0, "Kassulke" },
                    { 210, 26, "Spencer35@gmail.com", "Spencer", "DB", 0, "Bosco" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 211, 22, "Traci_Davis82@hotmail.com", "Traci", "DB", 1, "Davis" },
                    { 212, 82, "Janis.Toy@hotmail.com", "Janis", "DB", 1, "Toy" },
                    { 213, 81, "Preston_Cole16@hotmail.com", "Preston", "DB", 1, "Cole" },
                    { 214, 15, "Kathy_Adams@hotmail.com", "Kathy", "DB", 0, "Adams" },
                    { 215, 44, "Lester.DAmore86@yahoo.com", "Lester", "DB", 1, "D'Amore" },
                    { 216, 84, "Cristina_Moen53@yahoo.com", "Cristina", "DB", 0, "Moen" },
                    { 217, 66, "Brent.Schaefer@gmail.com", "Brent", "DB", 1, "Schaefer" },
                    { 218, 90, "Jackie92@yahoo.com", "Jackie", "DB", 1, "Runolfsson" },
                    { 219, 8, "Alonzo.Feeney49@gmail.com", "Alonzo", "DB", 0, "Feeney" },
                    { 220, 56, "Jenny23@hotmail.com", "Jenny", "DB", 1, "Schmitt" },
                    { 221, 12, "Ignacio98@gmail.com", "Ignacio", "DB", 1, "Rau" },
                    { 222, 17, "Edmond_Zulauf32@gmail.com", "Edmond", "DB", 0, "Zulauf" },
                    { 223, 18, "Angel45@gmail.com", "Angel", "DB", 0, "Blick" },
                    { 224, 82, "Jacquelyn.Gibson7@hotmail.com", "Jacquelyn", "DB", 1, "Gibson" },
                    { 225, 51, "Fernando.Rutherford9@yahoo.com", "Fernando", "DB", 0, "Rutherford" },
                    { 226, 38, "Steve_Hessel@gmail.com", "Steve", "DB", 0, "Hessel" },
                    { 227, 16, "Jane.Carroll@yahoo.com", "Jane", "DB", 0, "Carroll" },
                    { 228, 46, "Alexis.Wintheiser@yahoo.com", "Alexis", "DB", 0, "Wintheiser" },
                    { 229, 31, "Lillie59@hotmail.com", "Lillie", "DB", 0, "O'Conner" },
                    { 230, 48, "Rodney4@gmail.com", "Rodney", "DB", 1, "Prohaska" },
                    { 231, 48, "Olga55@yahoo.com", "Olga", "DB", 0, "McCullough" },
                    { 232, 50, "Violet_Rath@gmail.com", "Violet", "DB", 0, "Rath" },
                    { 233, 81, "Ernestine_Jones10@gmail.com", "Ernestine", "DB", 1, "Jones" },
                    { 234, 68, "Caroline_West@gmail.com", "Caroline", "DB", 1, "West" },
                    { 235, 31, "Ian.Conroy@hotmail.com", "Ian", "DB", 0, "Conroy" },
                    { 236, 77, "Adam87@gmail.com", "Adam", "DB", 1, "Jacobson" },
                    { 237, 37, "Kelly_Howell@yahoo.com", "Kelly", "DB", 0, "Howell" },
                    { 238, 85, "Violet.Lang94@gmail.com", "Violet", "DB", 0, "Lang" },
                    { 239, 45, "Jermaine98@hotmail.com", "Jermaine", "DB", 1, "Gleason" },
                    { 240, 39, "Dewey.Heathcote74@yahoo.com", "Dewey", "DB", 1, "Heathcote" },
                    { 241, 80, "Sheryl_Crist@hotmail.com", "Sheryl", "DB", 1, "Crist" },
                    { 242, 71, "Alexis.Romaguera9@hotmail.com", "Alexis", "DB", 0, "Romaguera" },
                    { 243, 88, "Jackie.Shields@yahoo.com", "Jackie", "DB", 1, "Shields" },
                    { 244, 23, "Sean.Muller@hotmail.com", "Sean", "DB", 1, "Muller" },
                    { 245, 76, "Stanley_Thiel1@gmail.com", "Stanley", "DB", 1, "Thiel" },
                    { 246, 64, "Wallace_Bogisich@hotmail.com", "Wallace", "DB", 1, "Bogisich" },
                    { 247, 38, "Claire_Stoltenberg@yahoo.com", "Claire", "DB", 1, "Stoltenberg" },
                    { 248, 31, "Marcos_Moore97@gmail.com", "Marcos", "DB", 0, "Moore" },
                    { 249, 45, "Archie_Nicolas9@hotmail.com", "Archie", "DB", 0, "Nicolas" },
                    { 250, 48, "Lucas90@yahoo.com", "Lucas", "DB", 0, "Tromp" },
                    { 251, 74, "Lyle.Durgan@hotmail.com", "Lyle", "DB", 1, "Durgan" },
                    { 252, 24, "Lyle2@hotmail.com", "Lyle", "DB", 0, "Tromp" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 253, 48, "Jeannie_Cruickshank20@hotmail.com", "Jeannie", "DB", 0, "Cruickshank" },
                    { 254, 64, "Jennifer.McClure83@gmail.com", "Jennifer", "DB", 1, "McClure" },
                    { 255, 39, "Marlene.Keeling58@yahoo.com", "Marlene", "DB", 0, "Keeling" },
                    { 256, 64, "Jenny71@gmail.com", "Jenny", "DB", 1, "O'Connell" },
                    { 257, 40, "Amy_Gottlieb26@hotmail.com", "Amy", "DB", 1, "Gottlieb" },
                    { 258, 14, "Phil_Russel@hotmail.com", "Phil", "DB", 0, "Russel" },
                    { 259, 42, "Bernice5@gmail.com", "Bernice", "DB", 0, "Jones" },
                    { 260, 69, "Jonathon90@hotmail.com", "Jonathon", "DB", 1, "Kessler" },
                    { 261, 40, "Margaret.Hoeger84@hotmail.com", "Margaret", "DB", 1, "Hoeger" },
                    { 262, 84, "Carolyn_Champlin@gmail.com", "Carolyn", "DB", 1, "Champlin" },
                    { 263, 69, "Tyler29@yahoo.com", "Tyler", "DB", 0, "Breitenberg" },
                    { 264, 57, "Latoya.Howe@yahoo.com", "Latoya", "DB", 0, "Howe" },
                    { 265, 37, "Shane.Green66@gmail.com", "Shane", "DB", 0, "Green" },
                    { 266, 25, "Amos45@gmail.com", "Amos", "DB", 0, "Hermann" },
                    { 267, 11, "Edwin_Strosin@gmail.com", "Edwin", "DB", 1, "Strosin" },
                    { 268, 16, "Roberto.Murazik@hotmail.com", "Roberto", "DB", 1, "Murazik" },
                    { 269, 71, "Chad_Toy47@yahoo.com", "Chad", "DB", 0, "Toy" },
                    { 270, 14, "Julian.Haag14@yahoo.com", "Julian", "DB", 1, "Haag" },
                    { 271, 45, "Ora56@gmail.com", "Ora", "DB", 1, "Christiansen" },
                    { 272, 10, "Orlando1@hotmail.com", "Orlando", "DB", 1, "Senger" },
                    { 273, 18, "Stuart79@hotmail.com", "Stuart", "DB", 0, "Hintz" },
                    { 274, 51, "Adrienne39@gmail.com", "Adrienne", "DB", 0, "Muller" },
                    { 275, 45, "Marvin_Wolf@hotmail.com", "Marvin", "DB", 0, "Wolf" },
                    { 276, 25, "Justin_Gerlach60@hotmail.com", "Justin", "DB", 0, "Gerlach" },
                    { 277, 21, "Lisa_Shanahan50@gmail.com", "Lisa", "DB", 1, "Shanahan" },
                    { 278, 30, "Dominic.OConner@yahoo.com", "Dominic", "DB", 1, "O'Conner" },
                    { 279, 52, "Toby.Ernser80@gmail.com", "Toby", "DB", 0, "Ernser" },
                    { 280, 78, "Lucy90@hotmail.com", "Lucy", "DB", 1, "Frami" },
                    { 281, 40, "Miranda_Gibson@gmail.com", "Miranda", "DB", 1, "Gibson" },
                    { 282, 33, "Colin22@gmail.com", "Colin", "DB", 1, "Ryan" },
                    { 283, 46, "Maurice_Kunze85@hotmail.com", "Maurice", "DB", 1, "Kunze" },
                    { 284, 42, "Jimmie11@gmail.com", "Jimmie", "DB", 0, "Gusikowski" },
                    { 285, 76, "Sylvester87@hotmail.com", "Sylvester", "DB", 1, "Mueller" },
                    { 286, 66, "Gail_Hettinger52@hotmail.com", "Gail", "DB", 0, "Hettinger" },
                    { 287, 15, "Bryant98@gmail.com", "Bryant", "DB", 1, "Haley" },
                    { 288, 37, "Luz_Volkman@gmail.com", "Luz", "DB", 1, "Volkman" },
                    { 289, 83, "Elbert_Schuppe92@yahoo.com", "Elbert", "DB", 1, "Schuppe" },
                    { 290, 10, "Brandi.Murray@hotmail.com", "Brandi", "DB", 1, "Murray" },
                    { 291, 11, "Jeanette68@gmail.com", "Jeanette", "DB", 0, "Runolfsdottir" },
                    { 292, 40, "Patrick_Parker@yahoo.com", "Patrick", "DB", 1, "Parker" },
                    { 293, 17, "Natalie_Dickinson@hotmail.com", "Natalie", "DB", 1, "Dickinson" },
                    { 294, 60, "Myra.Bosco23@yahoo.com", "Myra", "DB", 1, "Bosco" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 295, 26, "Shannon.Koss70@gmail.com", "Shannon", "DB", 0, "Koss" },
                    { 296, 37, "Jim_Corwin16@hotmail.com", "Jim", "DB", 1, "Corwin" },
                    { 297, 38, "Angela48@gmail.com", "Angela", "DB", 1, "Hahn" },
                    { 298, 81, "Freda98@hotmail.com", "Freda", "DB", 0, "Wyman" },
                    { 299, 24, "Marie.Abernathy@yahoo.com", "Marie", "DB", 1, "Abernathy" },
                    { 300, 38, "Vanessa_Crona@gmail.com", "Vanessa", "DB", 1, "Crona" },
                    { 301, 58, "Rose_Stark@gmail.com", "Rose", "DB", 1, "Stark" },
                    { 302, 41, "Francis_Reynolds@yahoo.com", "Francis", "DB", 1, "Reynolds" },
                    { 303, 36, "Kathryn_Champlin87@gmail.com", "Kathryn", "DB", 0, "Champlin" },
                    { 304, 8, "Anna79@gmail.com", "Anna", "DB", 1, "Botsford" },
                    { 305, 66, "Lucia58@hotmail.com", "Lucia", "DB", 1, "Paucek" },
                    { 306, 34, "Darlene.Schumm29@hotmail.com", "Darlene", "DB", 0, "Schumm" },
                    { 307, 90, "Jeannette.Ruecker@yahoo.com", "Jeannette", "DB", 1, "Ruecker" },
                    { 308, 43, "Marlon.Champlin96@gmail.com", "Marlon", "DB", 0, "Champlin" },
                    { 309, 62, "Clara_Lowe75@yahoo.com", "Clara", "DB", 1, "Lowe" },
                    { 310, 59, "Tyrone_Schimmel@hotmail.com", "Tyrone", "DB", 0, "Schimmel" },
                    { 311, 50, "Patsy33@yahoo.com", "Patsy", "DB", 1, "Orn" },
                    { 312, 18, "Kelli.Collins50@gmail.com", "Kelli", "DB", 0, "Collins" },
                    { 313, 55, "Lucia_Murazik@gmail.com", "Lucia", "DB", 1, "Murazik" },
                    { 314, 30, "Owen74@gmail.com", "Owen", "DB", 0, "Klocko" },
                    { 315, 31, "Benny_Weissnat@yahoo.com", "Benny", "DB", 1, "Weissnat" },
                    { 316, 54, "Jacob_Jacobson84@hotmail.com", "Jacob", "DB", 1, "Jacobson" },
                    { 317, 67, "Bryan38@yahoo.com", "Bryan", "DB", 1, "Schneider" },
                    { 318, 15, "Daryl96@hotmail.com", "Daryl", "DB", 1, "Streich" },
                    { 319, 28, "Neil.Daugherty37@yahoo.com", "Neil", "DB", 1, "Daugherty" },
                    { 320, 33, "Lowell70@yahoo.com", "Lowell", "DB", 0, "Goyette" },
                    { 321, 13, "Daniel.Kassulke33@hotmail.com", "Daniel", "DB", 0, "Kassulke" },
                    { 322, 34, "Marlene.Feil@yahoo.com", "Marlene", "DB", 0, "Feil" },
                    { 323, 38, "Alice_Block2@hotmail.com", "Alice", "DB", 0, "Block" },
                    { 324, 13, "Alison63@gmail.com", "Alison", "DB", 1, "Herzog" },
                    { 325, 36, "Christie27@hotmail.com", "Christie", "DB", 0, "Walter" },
                    { 326, 49, "Van.Dicki87@yahoo.com", "Van", "DB", 0, "Dicki" },
                    { 327, 12, "Wm_Mertz66@yahoo.com", "Wm", "DB", 0, "Mertz" },
                    { 328, 8, "Annette49@yahoo.com", "Annette", "DB", 1, "Dibbert" },
                    { 329, 46, "Ada.Reynolds67@yahoo.com", "Ada", "DB", 0, "Reynolds" },
                    { 330, 55, "Kenneth_Orn@hotmail.com", "Kenneth", "DB", 1, "Orn" },
                    { 331, 63, "Betsy22@yahoo.com", "Betsy", "DB", 0, "Powlowski" },
                    { 332, 24, "Michael_Hackett65@gmail.com", "Michael", "DB", 0, "Hackett" },
                    { 333, 45, "Dianne_Reichert80@gmail.com", "Dianne", "DB", 0, "Reichert" },
                    { 334, 87, "Kristen.Lueilwitz@yahoo.com", "Kristen", "DB", 1, "Lueilwitz" },
                    { 335, 73, "Mike.Swaniawski25@yahoo.com", "Mike", "DB", 1, "Swaniawski" },
                    { 336, 41, "Greg.Monahan@yahoo.com", "Greg", "DB", 0, "Monahan" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 337, 59, "Tamara_Nienow@gmail.com", "Tamara", "DB", 0, "Nienow" },
                    { 338, 64, "Natalie87@hotmail.com", "Natalie", "DB", 0, "Bruen" },
                    { 339, 61, "Beulah_Runolfsson@gmail.com", "Beulah", "DB", 0, "Runolfsson" },
                    { 340, 29, "Jermaine.Padberg@hotmail.com", "Jermaine", "DB", 1, "Padberg" },
                    { 341, 62, "Mindy_Koelpin@hotmail.com", "Mindy", "DB", 1, "Koelpin" },
                    { 342, 32, "Maggie.McDermott@hotmail.com", "Maggie", "DB", 1, "McDermott" },
                    { 343, 71, "Adam31@hotmail.com", "Adam", "DB", 0, "Lueilwitz" },
                    { 344, 36, "Clyde_Walsh12@gmail.com", "Clyde", "DB", 0, "Walsh" },
                    { 345, 36, "Kristina27@hotmail.com", "Kristina", "DB", 0, "Botsford" },
                    { 346, 17, "Carroll55@hotmail.com", "Carroll", "DB", 1, "Runolfsdottir" },
                    { 347, 71, "Chad4@hotmail.com", "Chad", "DB", 0, "Abbott" },
                    { 348, 46, "Iris.Morar99@gmail.com", "Iris", "DB", 0, "Morar" },
                    { 349, 88, "Kim.Williamson@gmail.com", "Kim", "DB", 1, "Williamson" },
                    { 350, 65, "Melissa67@hotmail.com", "Melissa", "DB", 1, "Johnston" },
                    { 351, 16, "Gwen11@hotmail.com", "Gwen", "DB", 0, "Barton" },
                    { 352, 82, "Krista82@hotmail.com", "Krista", "DB", 0, "Swaniawski" },
                    { 353, 78, "Julio2@yahoo.com", "Julio", "DB", 0, "Heidenreich" },
                    { 354, 72, "Clinton25@yahoo.com", "Clinton", "DB", 0, "Okuneva" },
                    { 355, 12, "Alan_Zboncak@hotmail.com", "Alan", "DB", 0, "Zboncak" },
                    { 356, 24, "Margaret79@yahoo.com", "Margaret", "DB", 0, "Reinger" },
                    { 357, 33, "Ernest22@hotmail.com", "Ernest", "DB", 0, "Rempel" },
                    { 358, 14, "Kristen_Block@gmail.com", "Kristen", "DB", 1, "Block" },
                    { 359, 73, "Alfred.Schulist69@hotmail.com", "Alfred", "DB", 1, "Schulist" },
                    { 360, 11, "Tammy.Graham@yahoo.com", "Tammy", "DB", 1, "Graham" },
                    { 361, 9, "Laura.Kozey74@hotmail.com", "Laura", "DB", 1, "Kozey" },
                    { 362, 18, "Leon_Simonis@hotmail.com", "Leon", "DB", 1, "Simonis" },
                    { 363, 64, "Angelo.Jaskolski@gmail.com", "Angelo", "DB", 0, "Jaskolski" },
                    { 364, 31, "Hector_Spinka78@yahoo.com", "Hector", "DB", 0, "Spinka" },
                    { 365, 19, "Jimmy.Wisoky48@gmail.com", "Jimmy", "DB", 0, "Wisoky" },
                    { 366, 74, "Lynne25@hotmail.com", "Lynne", "DB", 0, "Hirthe" },
                    { 367, 16, "Audrey_McGlynn@gmail.com", "Audrey", "DB", 0, "McGlynn" },
                    { 368, 86, "Priscilla.Veum95@gmail.com", "Priscilla", "DB", 0, "Veum" },
                    { 369, 24, "Cedric_Schmeler@yahoo.com", "Cedric", "DB", 1, "Schmeler" },
                    { 370, 23, "Al_Osinski94@gmail.com", "Al", "DB", 1, "Osinski" },
                    { 371, 53, "Julia41@gmail.com", "Julia", "DB", 0, "Reichel" },
                    { 372, 58, "Kendra.Kessler@yahoo.com", "Kendra", "DB", 1, "Kessler" },
                    { 373, 72, "Alvin.Hegmann@gmail.com", "Alvin", "DB", 0, "Hegmann" },
                    { 374, 33, "Suzanne.Schiller@gmail.com", "Suzanne", "DB", 0, "Schiller" },
                    { 375, 80, "Ron_Bartoletti@hotmail.com", "Ron", "DB", 1, "Bartoletti" },
                    { 376, 20, "Jamie_Schimmel51@hotmail.com", "Jamie", "DB", 0, "Schimmel" },
                    { 377, 15, "Gabriel29@hotmail.com", "Gabriel", "DB", 0, "Cummerata" },
                    { 378, 70, "Oscar6@gmail.com", "Oscar", "DB", 0, "Pouros" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 379, 72, "Pete12@hotmail.com", "Pete", "DB", 1, "Breitenberg" },
                    { 380, 30, "Kelley.Jast@hotmail.com", "Kelley", "DB", 0, "Jast" },
                    { 381, 61, "Clara15@yahoo.com", "Clara", "DB", 0, "Purdy" },
                    { 382, 25, "Heidi_Yost10@gmail.com", "Heidi", "DB", 1, "Yost" },
                    { 383, 19, "Linda_Toy44@gmail.com", "Linda", "DB", 1, "Toy" },
                    { 384, 65, "Leon.Koch6@hotmail.com", "Leon", "DB", 1, "Koch" },
                    { 385, 25, "Lucas_Price@gmail.com", "Lucas", "DB", 0, "Price" },
                    { 386, 13, "Katherine11@gmail.com", "Katherine", "DB", 1, "Dietrich" },
                    { 387, 54, "Crystal.Romaguera18@gmail.com", "Crystal", "DB", 1, "Romaguera" },
                    { 388, 26, "Terry44@gmail.com", "Terry", "DB", 0, "Conroy" },
                    { 389, 59, "Gail8@hotmail.com", "Gail", "DB", 1, "Anderson" },
                    { 390, 62, "Melanie55@yahoo.com", "Melanie", "DB", 1, "Rath" },
                    { 391, 25, "Beatrice.Cronin@hotmail.com", "Beatrice", "DB", 0, "Cronin" },
                    { 392, 71, "Guillermo_Grant73@hotmail.com", "Guillermo", "DB", 1, "Grant" },
                    { 393, 13, "Lance72@gmail.com", "Lance", "DB", 0, "Bergnaum" },
                    { 394, 76, "Wilfred_Tillman19@yahoo.com", "Wilfred", "DB", 1, "Tillman" },
                    { 395, 68, "Geneva.Volkman@gmail.com", "Geneva", "DB", 0, "Volkman" },
                    { 396, 59, "Casey.Langworth23@yahoo.com", "Casey", "DB", 0, "Langworth" },
                    { 397, 37, "Rudy.Ryan@gmail.com", "Rudy", "DB", 0, "Ryan" },
                    { 398, 70, "Dallas_Goodwin72@gmail.com", "Dallas", "DB", 0, "Goodwin" },
                    { 399, 66, "Terry.Yundt@yahoo.com", "Terry", "DB", 0, "Yundt" },
                    { 400, 26, "Sara39@hotmail.com", "Sara", "DB", 0, "Runte" },
                    { 401, 53, "Lucy39@gmail.com", "Lucy", "DB", 1, "Heathcote" },
                    { 402, 26, "Terrance.Haag@yahoo.com", "Terrance", "DB", 1, "Haag" },
                    { 403, 50, "Cameron88@hotmail.com", "Cameron", "DB", 1, "Smith" },
                    { 404, 27, "Cecelia.McGlynn46@gmail.com", "Cecelia", "DB", 0, "McGlynn" },
                    { 405, 10, "Alexander_Wiza28@gmail.com", "Alexander", "DB", 1, "Wiza" },
                    { 406, 83, "Israel.Lueilwitz89@yahoo.com", "Israel", "DB", 1, "Lueilwitz" },
                    { 407, 87, "May91@hotmail.com", "May", "DB", 1, "Block" },
                    { 408, 74, "Nora_Kuvalis@gmail.com", "Nora", "DB", 0, "Kuvalis" },
                    { 409, 10, "Brenda.Carter@yahoo.com", "Brenda", "DB", 0, "Carter" },
                    { 410, 50, "Gretchen46@yahoo.com", "Gretchen", "DB", 1, "Lebsack" },
                    { 411, 61, "Rodney_Moen@hotmail.com", "Rodney", "DB", 1, "Moen" },
                    { 412, 21, "Wade.Reichel66@gmail.com", "Wade", "DB", 0, "Reichel" },
                    { 413, 14, "Saul_Balistreri@gmail.com", "Saul", "DB", 0, "Balistreri" },
                    { 414, 44, "Gregg_Beahan10@yahoo.com", "Gregg", "DB", 0, "Beahan" },
                    { 415, 84, "Robin_Crooks87@hotmail.com", "Robin", "DB", 0, "Crooks" },
                    { 416, 51, "Eloise.Schowalter74@gmail.com", "Eloise", "DB", 1, "Schowalter" },
                    { 417, 33, "Cecil53@hotmail.com", "Cecil", "DB", 1, "Beer" },
                    { 418, 41, "Perry69@hotmail.com", "Perry", "DB", 1, "Greenfelder" },
                    { 419, 74, "Mathew.Konopelski30@gmail.com", "Mathew", "DB", 1, "Konopelski" },
                    { 420, 15, "Johnnie_Gleason82@yahoo.com", "Johnnie", "DB", 1, "Gleason" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 421, 71, "Emma_Monahan28@gmail.com", "Emma", "DB", 0, "Monahan" },
                    { 422, 18, "Steve97@yahoo.com", "Steve", "DB", 1, "Volkman" },
                    { 423, 90, "Eric38@gmail.com", "Eric", "DB", 1, "Welch" },
                    { 424, 85, "Willard_Waters77@gmail.com", "Willard", "DB", 0, "Waters" },
                    { 425, 11, "Juan_Jacobs@hotmail.com", "Juan", "DB", 1, "Jacobs" },
                    { 426, 24, "Victoria26@yahoo.com", "Victoria", "DB", 0, "Gerlach" },
                    { 427, 83, "Raul_Mohr71@hotmail.com", "Raul", "DB", 0, "Mohr" },
                    { 428, 68, "Jennifer.Brekke30@gmail.com", "Jennifer", "DB", 0, "Brekke" },
                    { 429, 79, "Leslie.Harvey25@hotmail.com", "Leslie", "DB", 1, "Harvey" },
                    { 430, 19, "Gerald_West@hotmail.com", "Gerald", "DB", 0, "West" },
                    { 431, 31, "Jonathon59@gmail.com", "Jonathon", "DB", 1, "Effertz" },
                    { 432, 30, "Florence10@hotmail.com", "Florence", "DB", 1, "Purdy" },
                    { 433, 47, "Spencer12@hotmail.com", "Spencer", "DB", 1, "Swift" },
                    { 434, 36, "Daniel_Beer@yahoo.com", "Daniel", "DB", 1, "Beer" },
                    { 435, 35, "Ramona_Dickinson8@gmail.com", "Ramona", "DB", 0, "Dickinson" },
                    { 436, 82, "Ashley_Denesik91@hotmail.com", "Ashley", "DB", 1, "Denesik" },
                    { 437, 79, "Rafael21@yahoo.com", "Rafael", "DB", 1, "Zboncak" },
                    { 438, 68, "Dexter.Collier26@gmail.com", "Dexter", "DB", 0, "Collier" },
                    { 439, 47, "Rickey.West@hotmail.com", "Rickey", "DB", 0, "West" },
                    { 440, 14, "Gordon83@hotmail.com", "Gordon", "DB", 1, "Bernhard" },
                    { 441, 89, "Bernard.Jacobi@yahoo.com", "Bernard", "DB", 1, "Jacobi" },
                    { 442, 81, "Belinda_Nitzsche50@gmail.com", "Belinda", "DB", 1, "Nitzsche" },
                    { 443, 83, "Jimmie99@hotmail.com", "Jimmie", "DB", 0, "Ryan" },
                    { 444, 17, "Rene.Homenick@gmail.com", "Rene", "DB", 1, "Homenick" },
                    { 445, 90, "Vicky.Klocko16@gmail.com", "Vicky", "DB", 1, "Klocko" },
                    { 446, 73, "Luther_Schoen7@gmail.com", "Luther", "DB", 0, "Schoen" },
                    { 447, 62, "Brandi.Daniel90@gmail.com", "Brandi", "DB", 1, "Daniel" },
                    { 448, 44, "Hope.Christiansen66@yahoo.com", "Hope", "DB", 0, "Christiansen" },
                    { 449, 15, "Sue.Willms46@gmail.com", "Sue", "DB", 1, "Willms" },
                    { 450, 22, "Wanda.Ebert16@hotmail.com", "Wanda", "DB", 1, "Ebert" },
                    { 451, 43, "Ernestine13@gmail.com", "Ernestine", "DB", 0, "Leannon" },
                    { 452, 30, "Natalie_Cronin13@hotmail.com", "Natalie", "DB", 1, "Cronin" },
                    { 453, 38, "Rita_Jast@hotmail.com", "Rita", "DB", 0, "Jast" },
                    { 454, 78, "Martha17@yahoo.com", "Martha", "DB", 0, "Sporer" },
                    { 455, 9, "Charlie28@hotmail.com", "Charlie", "DB", 1, "Gottlieb" },
                    { 456, 76, "Ralph97@hotmail.com", "Ralph", "DB", 0, "Rogahn" },
                    { 457, 35, "Ruben99@hotmail.com", "Ruben", "DB", 1, "Cole" },
                    { 458, 45, "Bessie_Will@gmail.com", "Bessie", "DB", 0, "Will" },
                    { 459, 43, "Maureen_Murray@gmail.com", "Maureen", "DB", 1, "Murray" },
                    { 460, 20, "Minnie_Osinski70@gmail.com", "Minnie", "DB", 0, "Osinski" },
                    { 461, 55, "Leland70@yahoo.com", "Leland", "DB", 1, "O'Kon" },
                    { 462, 22, "Tara_Kunze24@yahoo.com", "Tara", "DB", 0, "Kunze" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 463, 31, "Alex5@gmail.com", "Alex", "DB", 1, "Fadel" },
                    { 464, 47, "Greg.Doyle27@yahoo.com", "Greg", "DB", 1, "Doyle" },
                    { 465, 89, "Elvira16@gmail.com", "Elvira", "DB", 1, "Block" },
                    { 466, 56, "Travis85@hotmail.com", "Travis", "DB", 0, "Feil" },
                    { 467, 85, "Susie49@hotmail.com", "Susie", "DB", 0, "Prohaska" },
                    { 468, 76, "Terence96@gmail.com", "Terence", "DB", 1, "Vandervort" },
                    { 469, 41, "Kerry.Berge98@gmail.com", "Kerry", "DB", 0, "Berge" },
                    { 470, 73, "Arthur85@hotmail.com", "Arthur", "DB", 0, "Torphy" },
                    { 471, 51, "Roxanne.DuBuque@yahoo.com", "Roxanne", "DB", 1, "DuBuque" },
                    { 472, 8, "Anna.Bayer33@yahoo.com", "Anna", "DB", 1, "Bayer" },
                    { 473, 61, "Erick.Weissnat31@gmail.com", "Erick", "DB", 1, "Weissnat" },
                    { 474, 83, "Jody0@yahoo.com", "Jody", "DB", 1, "Lakin" },
                    { 475, 60, "Marlon_Kub@yahoo.com", "Marlon", "DB", 1, "Kub" },
                    { 476, 40, "Tammy3@yahoo.com", "Tammy", "DB", 0, "Daugherty" },
                    { 477, 75, "Enrique.Lang@yahoo.com", "Enrique", "DB", 1, "Lang" },
                    { 478, 66, "Kayla24@hotmail.com", "Kayla", "DB", 1, "Jones" },
                    { 479, 27, "Tonya_Waters97@gmail.com", "Tonya", "DB", 1, "Waters" },
                    { 480, 78, "Toby.Cassin@yahoo.com", "Toby", "DB", 0, "Cassin" },
                    { 481, 46, "Toni65@yahoo.com", "Toni", "DB", 0, "Stark" },
                    { 482, 64, "Alonzo59@gmail.com", "Alonzo", "DB", 1, "Feest" },
                    { 483, 47, "Ana28@hotmail.com", "Ana", "DB", 0, "Koch" },
                    { 484, 11, "Brendan.Moen@hotmail.com", "Brendan", "DB", 1, "Moen" },
                    { 485, 36, "Phillip46@gmail.com", "Phillip", "DB", 1, "Wolf" },
                    { 486, 21, "Kirk43@gmail.com", "Kirk", "DB", 0, "Hessel" },
                    { 487, 61, "Delbert.Kohler60@gmail.com", "Delbert", "DB", 0, "Kohler" },
                    { 488, 72, "Eunice.Gleason5@hotmail.com", "Eunice", "DB", 0, "Gleason" },
                    { 489, 19, "Vickie_Koepp83@yahoo.com", "Vickie", "DB", 1, "Koepp" },
                    { 490, 61, "Phyllis5@yahoo.com", "Phyllis", "DB", 0, "Robel" },
                    { 491, 80, "Jimmie_McDermott43@gmail.com", "Jimmie", "DB", 0, "McDermott" },
                    { 492, 8, "Ora9@gmail.com", "Ora", "DB", 1, "Kautzer" },
                    { 493, 33, "Jessie.Keeling28@hotmail.com", "Jessie", "DB", 1, "Keeling" },
                    { 494, 42, "Gene_Oberbrunner@gmail.com", "Gene", "DB", 1, "Oberbrunner" },
                    { 495, 22, "Hannah_Mayer85@hotmail.com", "Hannah", "DB", 0, "Mayer" },
                    { 496, 9, "Sadie_Christiansen93@yahoo.com", "Sadie", "DB", 1, "Christiansen" },
                    { 497, 47, "Karen88@yahoo.com", "Karen", "DB", 0, "Bayer" },
                    { 498, 10, "Ernestine.Hahn@gmail.com", "Ernestine", "DB", 1, "Hahn" },
                    { 499, 86, "Mark_DuBuque@gmail.com", "Mark", "DB", 0, "DuBuque" },
                    { 500, 42, "Jeremy.Kessler@gmail.com", "Jeremy", "DB", 1, "Kessler" },
                    { 501, 36, "Ed48@gmail.com", "Ed", "DB", 1, "Windler" },
                    { 502, 43, "Rodolfo31@gmail.com", "Rodolfo", "DB", 1, "Kreiger" },
                    { 503, 30, "Geneva.Nienow99@yahoo.com", "Geneva", "DB", 1, "Nienow" },
                    { 504, 74, "Louis.DAmore@yahoo.com", "Louis", "DB", 0, "D'Amore" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 505, 13, "Christine73@gmail.com", "Christine", "DB", 0, "Hermann" },
                    { 506, 24, "Madeline_Wintheiser@gmail.com", "Madeline", "DB", 1, "Wintheiser" },
                    { 507, 8, "Karl.Lindgren@gmail.com", "Karl", "DB", 1, "Lindgren" },
                    { 508, 51, "Janet9@hotmail.com", "Janet", "DB", 0, "Larkin" },
                    { 509, 52, "Amy.OHara@hotmail.com", "Amy", "DB", 1, "O'Hara" },
                    { 510, 74, "Camille82@hotmail.com", "Camille", "DB", 0, "Wehner" },
                    { 511, 13, "Alison96@yahoo.com", "Alison", "DB", 1, "Gleason" },
                    { 512, 50, "Pamela_Emmerich@yahoo.com", "Pamela", "DB", 1, "Emmerich" },
                    { 513, 48, "Cindy.Balistreri61@yahoo.com", "Cindy", "DB", 1, "Balistreri" },
                    { 514, 28, "Louise.Nienow62@gmail.com", "Louise", "DB", 1, "Nienow" },
                    { 515, 69, "Melody96@yahoo.com", "Melody", "DB", 0, "Windler" },
                    { 516, 30, "Clyde_Miller19@yahoo.com", "Clyde", "DB", 0, "Miller" },
                    { 517, 86, "Erika.Stokes@hotmail.com", "Erika", "DB", 0, "Stokes" },
                    { 518, 32, "Israel41@yahoo.com", "Israel", "DB", 1, "Rohan" },
                    { 519, 68, "Fred22@gmail.com", "Fred", "DB", 0, "Abernathy" },
                    { 520, 66, "Joanna71@yahoo.com", "Joanna", "DB", 1, "Schaden" },
                    { 521, 64, "Shannon_Bahringer20@yahoo.com", "Shannon", "DB", 0, "Bahringer" },
                    { 522, 11, "Craig51@yahoo.com", "Craig", "DB", 1, "MacGyver" },
                    { 523, 48, "Elisa35@hotmail.com", "Elisa", "DB", 0, "Harvey" },
                    { 524, 89, "Ken.Bashirian@hotmail.com", "Ken", "DB", 1, "Bashirian" },
                    { 525, 78, "Candice_Kreiger38@hotmail.com", "Candice", "DB", 0, "Kreiger" },
                    { 526, 36, "Kara80@hotmail.com", "Kara", "DB", 0, "Mayer" },
                    { 527, 77, "Pete.Thompson@yahoo.com", "Pete", "DB", 0, "Thompson" },
                    { 528, 21, "Erica55@hotmail.com", "Erica", "DB", 0, "Armstrong" },
                    { 529, 51, "Edward.Jacobson@gmail.com", "Edward", "DB", 0, "Jacobson" },
                    { 530, 26, "Gary_Maggio@yahoo.com", "Gary", "DB", 1, "Maggio" },
                    { 531, 16, "Meghan97@gmail.com", "Meghan", "DB", 0, "Heidenreich" },
                    { 532, 49, "Leroy77@hotmail.com", "Leroy", "DB", 0, "Huel" },
                    { 533, 73, "Margarita_Legros55@hotmail.com", "Margarita", "DB", 0, "Legros" },
                    { 534, 17, "Erik_Schinner44@hotmail.com", "Erik", "DB", 1, "Schinner" },
                    { 535, 31, "Erik14@yahoo.com", "Erik", "DB", 1, "Brown" },
                    { 536, 49, "Raymond_Stehr84@hotmail.com", "Raymond", "DB", 0, "Stehr" },
                    { 537, 22, "Richard41@hotmail.com", "Richard", "DB", 1, "Spinka" },
                    { 538, 29, "Cecelia.Koelpin38@gmail.com", "Cecelia", "DB", 1, "Koelpin" },
                    { 539, 80, "Johanna42@yahoo.com", "Johanna", "DB", 0, "Botsford" },
                    { 540, 84, "Rebecca55@gmail.com", "Rebecca", "DB", 1, "Schinner" },
                    { 541, 73, "Dora_Borer@yahoo.com", "Dora", "DB", 0, "Borer" },
                    { 542, 43, "Ebony49@gmail.com", "Ebony", "DB", 0, "Kuphal" },
                    { 543, 78, "Carla57@gmail.com", "Carla", "DB", 0, "Macejkovic" },
                    { 544, 49, "Jonathon_DAmore@hotmail.com", "Jonathon", "DB", 1, "D'Amore" },
                    { 545, 82, "Brandy.Harvey@hotmail.com", "Brandy", "DB", 1, "Harvey" },
                    { 546, 17, "Mark38@yahoo.com", "Mark", "DB", 0, "Price" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 547, 25, "Yolanda.Paucek84@hotmail.com", "Yolanda", "DB", 0, "Paucek" },
                    { 548, 43, "Erin_Casper@yahoo.com", "Erin", "DB", 0, "Casper" },
                    { 549, 82, "Antonio51@gmail.com", "Antonio", "DB", 0, "Nolan" },
                    { 550, 45, "Kerry.Pfannerstill@yahoo.com", "Kerry", "DB", 0, "Pfannerstill" },
                    { 551, 75, "Gail.Effertz@gmail.com", "Gail", "DB", 0, "Effertz" },
                    { 552, 19, "Betty_Farrell@gmail.com", "Betty", "DB", 1, "Farrell" },
                    { 553, 23, "Daryl_Stehr@yahoo.com", "Daryl", "DB", 1, "Stehr" },
                    { 554, 43, "Kendra_Powlowski60@gmail.com", "Kendra", "DB", 1, "Powlowski" },
                    { 555, 41, "Kerry_Wehner@yahoo.com", "Kerry", "DB", 0, "Wehner" },
                    { 556, 30, "Doreen3@yahoo.com", "Doreen", "DB", 1, "Smitham" },
                    { 557, 49, "Lewis14@gmail.com", "Lewis", "DB", 1, "Rodriguez" },
                    { 558, 79, "Maria.Pacocha@hotmail.com", "Maria", "DB", 1, "Pacocha" },
                    { 559, 10, "Shelia_Conroy@gmail.com", "Shelia", "DB", 0, "Conroy" },
                    { 560, 42, "Ronald.Hackett@gmail.com", "Ronald", "DB", 0, "Hackett" },
                    { 561, 46, "Tyrone_Leannon@yahoo.com", "Tyrone", "DB", 1, "Leannon" },
                    { 562, 22, "Tara_Marquardt@gmail.com", "Tara", "DB", 0, "Marquardt" },
                    { 563, 43, "Bryant_Collier@yahoo.com", "Bryant", "DB", 1, "Collier" },
                    { 564, 44, "Lois.Kris92@hotmail.com", "Lois", "DB", 1, "Kris" },
                    { 565, 39, "Dwayne35@gmail.com", "Dwayne", "DB", 0, "Ziemann" },
                    { 566, 52, "Pablo_Kunze@hotmail.com", "Pablo", "DB", 0, "Kunze" },
                    { 567, 32, "Bernice53@yahoo.com", "Bernice", "DB", 1, "Braun" },
                    { 568, 83, "Alma_Haag24@yahoo.com", "Alma", "DB", 1, "Haag" },
                    { 569, 40, "Marvin_Will19@gmail.com", "Marvin", "DB", 0, "Will" },
                    { 570, 81, "Ernesto.Turcotte@yahoo.com", "Ernesto", "DB", 1, "Turcotte" },
                    { 571, 82, "Deborah.Bogisich6@gmail.com", "Deborah", "DB", 1, "Bogisich" },
                    { 572, 84, "Amber_Ortiz@gmail.com", "Amber", "DB", 0, "Ortiz" },
                    { 573, 48, "Ida32@yahoo.com", "Ida", "DB", 1, "O'Reilly" },
                    { 574, 30, "Carolyn40@hotmail.com", "Carolyn", "DB", 0, "Berge" },
                    { 575, 15, "Daniel.Dietrich83@gmail.com", "Daniel", "DB", 0, "Dietrich" },
                    { 576, 18, "Devin.Lemke@yahoo.com", "Devin", "DB", 1, "Lemke" },
                    { 577, 76, "Marc.Hessel9@yahoo.com", "Marc", "DB", 1, "Hessel" },
                    { 578, 16, "Allison46@hotmail.com", "Allison", "DB", 0, "Kutch" },
                    { 579, 59, "Susan_Volkman43@gmail.com", "Susan", "DB", 1, "Volkman" },
                    { 580, 35, "Darryl_Kiehn@yahoo.com", "Darryl", "DB", 1, "Kiehn" },
                    { 581, 48, "Sammy82@yahoo.com", "Sammy", "DB", 1, "Stark" },
                    { 582, 72, "Herman_Murazik14@hotmail.com", "Herman", "DB", 0, "Murazik" },
                    { 583, 87, "Tina_Cummings99@gmail.com", "Tina", "DB", 1, "Cummings" },
                    { 584, 50, "Tiffany_Windler27@gmail.com", "Tiffany", "DB", 1, "Windler" },
                    { 585, 23, "Carlton_Crona93@yahoo.com", "Carlton", "DB", 1, "Crona" },
                    { 586, 76, "Frank.Swaniawski@gmail.com", "Frank", "DB", 1, "Swaniawski" },
                    { 587, 10, "Marion.Bruen59@hotmail.com", "Marion", "DB", 1, "Bruen" },
                    { 588, 27, "Ramon.Lowe9@hotmail.com", "Ramon", "DB", 0, "Lowe" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 589, 42, "Mark66@gmail.com", "Mark", "DB", 0, "Marvin" },
                    { 590, 77, "Ian59@hotmail.com", "Ian", "DB", 0, "Williamson" },
                    { 591, 70, "Monique_Gerhold@gmail.com", "Monique", "DB", 1, "Gerhold" },
                    { 592, 50, "Traci_Carroll54@gmail.com", "Traci", "DB", 0, "Carroll" },
                    { 593, 86, "Freddie.Spinka@yahoo.com", "Freddie", "DB", 0, "Spinka" },
                    { 594, 32, "Sean.Jast99@yahoo.com", "Sean", "DB", 1, "Jast" },
                    { 595, 41, "Constance_Nikolaus@yahoo.com", "Constance", "DB", 1, "Nikolaus" },
                    { 596, 57, "Nicole.Goldner19@gmail.com", "Nicole", "DB", 1, "Goldner" },
                    { 597, 27, "Dennis73@gmail.com", "Dennis", "DB", 0, "Kilback" },
                    { 598, 70, "Katie32@gmail.com", "Katie", "DB", 0, "Mitchell" },
                    { 599, 32, "Nathaniel.Wisozk@yahoo.com", "Nathaniel", "DB", 1, "Wisozk" },
                    { 600, 74, "Ana_Koelpin57@hotmail.com", "Ana", "DB", 0, "Koelpin" },
                    { 601, 37, "Patricia.Hoeger71@gmail.com", "Patricia", "DB", 1, "Hoeger" },
                    { 602, 28, "Luis19@yahoo.com", "Luis", "DB", 0, "Schuster" },
                    { 603, 74, "Denise.Bergstrom19@gmail.com", "Denise", "DB", 1, "Bergstrom" },
                    { 604, 80, "Valerie78@gmail.com", "Valerie", "DB", 0, "Carroll" },
                    { 605, 16, "Joseph_Dickinson@yahoo.com", "Joseph", "DB", 0, "Dickinson" },
                    { 606, 71, "Brent_Conroy@hotmail.com", "Brent", "DB", 1, "Conroy" },
                    { 607, 53, "Janis.Mohr@hotmail.com", "Janis", "DB", 1, "Mohr" },
                    { 608, 25, "Lucas_Marvin@gmail.com", "Lucas", "DB", 1, "Marvin" },
                    { 609, 62, "Mike5@yahoo.com", "Mike", "DB", 1, "Kling" },
                    { 610, 24, "Tabitha_Stark@hotmail.com", "Tabitha", "DB", 0, "Stark" },
                    { 611, 31, "Dennis_Nader@gmail.com", "Dennis", "DB", 0, "Nader" },
                    { 612, 35, "Armando_Gutkowski88@yahoo.com", "Armando", "DB", 0, "Gutkowski" },
                    { 613, 51, "Henry25@yahoo.com", "Henry", "DB", 0, "Predovic" },
                    { 614, 21, "Becky_Stark@yahoo.com", "Becky", "DB", 1, "Stark" },
                    { 615, 89, "Verna92@hotmail.com", "Verna", "DB", 0, "Beatty" },
                    { 616, 38, "Marcos_Rippin75@yahoo.com", "Marcos", "DB", 0, "Rippin" },
                    { 617, 18, "Alice_Feest@hotmail.com", "Alice", "DB", 1, "Feest" },
                    { 618, 63, "Samuel_Kirlin@gmail.com", "Samuel", "DB", 1, "Kirlin" },
                    { 619, 63, "Jonathon73@yahoo.com", "Jonathon", "DB", 1, "Durgan" },
                    { 620, 46, "Daniel.Robel@yahoo.com", "Daniel", "DB", 0, "Robel" },
                    { 621, 42, "Angel.Yost72@yahoo.com", "Angel", "DB", 0, "Yost" },
                    { 622, 30, "Eugene_Gusikowski@yahoo.com", "Eugene", "DB", 0, "Gusikowski" },
                    { 623, 53, "Jimmie98@yahoo.com", "Jimmie", "DB", 1, "Keeling" },
                    { 624, 39, "Elbert_Schaefer@hotmail.com", "Elbert", "DB", 0, "Schaefer" },
                    { 625, 49, "Edward_Brown21@hotmail.com", "Edward", "DB", 0, "Brown" },
                    { 626, 38, "Alicia.Jaskolski@gmail.com", "Alicia", "DB", 1, "Jaskolski" },
                    { 627, 62, "Elias.Becker80@gmail.com", "Elias", "DB", 1, "Becker" },
                    { 628, 14, "Laurence.Ankunding@hotmail.com", "Laurence", "DB", 1, "Ankunding" },
                    { 629, 54, "Tina58@yahoo.com", "Tina", "DB", 1, "Gaylord" },
                    { 630, 72, "Grant.Stokes9@gmail.com", "Grant", "DB", 1, "Stokes" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 631, 46, "Marguerite.Schoen38@hotmail.com", "Marguerite", "DB", 1, "Schoen" },
                    { 632, 57, "Yvonne_Hettinger@yahoo.com", "Yvonne", "DB", 0, "Hettinger" },
                    { 633, 44, "Austin66@yahoo.com", "Austin", "DB", 0, "Wisoky" },
                    { 634, 82, "Francis42@yahoo.com", "Francis", "DB", 1, "Ondricka" },
                    { 635, 60, "Casey.Lemke@yahoo.com", "Casey", "DB", 1, "Lemke" },
                    { 636, 44, "Ana.Keebler@yahoo.com", "Ana", "DB", 0, "Keebler" },
                    { 637, 39, "Tasha.Ritchie@gmail.com", "Tasha", "DB", 0, "Ritchie" },
                    { 638, 60, "Abel_Monahan@gmail.com", "Abel", "DB", 1, "Monahan" },
                    { 639, 36, "Erin_Wyman55@gmail.com", "Erin", "DB", 0, "Wyman" },
                    { 640, 13, "Candice.Haag64@yahoo.com", "Candice", "DB", 0, "Haag" },
                    { 641, 85, "Ernesto_Abbott@yahoo.com", "Ernesto", "DB", 1, "Abbott" },
                    { 642, 50, "Claire.Romaguera@gmail.com", "Claire", "DB", 0, "Romaguera" },
                    { 643, 90, "Percy_Franecki@gmail.com", "Percy", "DB", 1, "Franecki" },
                    { 644, 90, "Tommie.Kuvalis@hotmail.com", "Tommie", "DB", 1, "Kuvalis" },
                    { 645, 75, "Joanne.Sanford@hotmail.com", "Joanne", "DB", 1, "Sanford" },
                    { 646, 60, "Rufus.Von26@gmail.com", "Rufus", "DB", 1, "Von" },
                    { 647, 83, "Emma43@hotmail.com", "Emma", "DB", 1, "Gorczany" },
                    { 648, 34, "Bessie_Gleichner@gmail.com", "Bessie", "DB", 1, "Gleichner" },
                    { 649, 15, "Leslie85@yahoo.com", "Leslie", "DB", 0, "Connelly" },
                    { 650, 30, "Angie.Daugherty90@yahoo.com", "Angie", "DB", 1, "Daugherty" },
                    { 651, 84, "Rolando.Kuphal5@yahoo.com", "Rolando", "DB", 1, "Kuphal" },
                    { 652, 38, "Mark97@hotmail.com", "Mark", "DB", 0, "Morissette" },
                    { 653, 87, "Brad33@gmail.com", "Brad", "DB", 1, "Wuckert" },
                    { 654, 17, "Lorena8@hotmail.com", "Lorena", "DB", 1, "Ebert" },
                    { 655, 10, "Paul48@gmail.com", "Paul", "DB", 1, "Mohr" },
                    { 656, 27, "Omar62@yahoo.com", "Omar", "DB", 0, "Halvorson" },
                    { 657, 18, "Franklin_Mayer99@gmail.com", "Franklin", "DB", 1, "Mayer" },
                    { 658, 41, "Carl.Erdman@yahoo.com", "Carl", "DB", 1, "Erdman" },
                    { 659, 78, "Craig.Marvin@gmail.com", "Craig", "DB", 1, "Marvin" },
                    { 660, 17, "Darnell.Jacobi62@gmail.com", "Darnell", "DB", 1, "Jacobi" },
                    { 661, 83, "Joy2@hotmail.com", "Joy", "DB", 0, "Hermiston" },
                    { 662, 13, "Sonja_Robel81@gmail.com", "Sonja", "DB", 1, "Robel" },
                    { 663, 29, "Leo59@hotmail.com", "Leo", "DB", 0, "Bode" },
                    { 664, 78, "Inez15@yahoo.com", "Inez", "DB", 0, "Bauch" },
                    { 665, 61, "Colin5@yahoo.com", "Colin", "DB", 0, "Labadie" },
                    { 666, 11, "Billy_Torphy@gmail.com", "Billy", "DB", 0, "Torphy" },
                    { 667, 19, "Carmen_Von57@yahoo.com", "Carmen", "DB", 1, "Von" },
                    { 668, 86, "Josefina_Mills31@yahoo.com", "Josefina", "DB", 1, "Mills" },
                    { 669, 87, "Eunice28@yahoo.com", "Eunice", "DB", 1, "Greenholt" },
                    { 670, 90, "Alison28@gmail.com", "Alison", "DB", 1, "Medhurst" },
                    { 671, 62, "Tonya44@gmail.com", "Tonya", "DB", 0, "Orn" },
                    { 672, 25, "Morris61@hotmail.com", "Morris", "DB", 0, "Parisian" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 673, 39, "Billie.Weber@hotmail.com", "Billie", "DB", 0, "Weber" },
                    { 674, 76, "Lorraine_Lemke@gmail.com", "Lorraine", "DB", 1, "Lemke" },
                    { 675, 34, "Mitchell43@yahoo.com", "Mitchell", "DB", 0, "Nikolaus" },
                    { 676, 78, "Renee11@hotmail.com", "Renee", "DB", 0, "Hodkiewicz" },
                    { 677, 73, "Paul_Kulas@yahoo.com", "Paul", "DB", 1, "Kulas" },
                    { 678, 20, "Charles11@hotmail.com", "Charles", "DB", 0, "Hettinger" },
                    { 679, 43, "Jeff_Schowalter82@gmail.com", "Jeff", "DB", 0, "Schowalter" },
                    { 680, 19, "Dennis.Keeling@yahoo.com", "Dennis", "DB", 0, "Keeling" },
                    { 681, 13, "Ervin_Orn@yahoo.com", "Ervin", "DB", 0, "Orn" },
                    { 682, 52, "Casey.Fisher82@yahoo.com", "Casey", "DB", 1, "Fisher" },
                    { 683, 56, "Priscilla_Wisoky@hotmail.com", "Priscilla", "DB", 0, "Wisoky" },
                    { 684, 34, "Jeanne60@hotmail.com", "Jeanne", "DB", 1, "Crooks" },
                    { 685, 85, "Veronica_Harber@hotmail.com", "Veronica", "DB", 0, "Harber" },
                    { 686, 26, "Gustavo84@yahoo.com", "Gustavo", "DB", 1, "King" },
                    { 687, 37, "Randolph_Kuvalis50@yahoo.com", "Randolph", "DB", 0, "Kuvalis" },
                    { 688, 82, "Tonya.Raynor@hotmail.com", "Tonya", "DB", 0, "Raynor" },
                    { 689, 9, "Eula.OConnell75@hotmail.com", "Eula", "DB", 1, "O'Connell" },
                    { 690, 65, "Amelia_Stark11@hotmail.com", "Amelia", "DB", 0, "Stark" },
                    { 691, 61, "Amos_Lebsack@hotmail.com", "Amos", "DB", 0, "Lebsack" },
                    { 692, 54, "Lee.Hessel40@gmail.com", "Lee", "DB", 1, "Hessel" },
                    { 693, 44, "Wallace_Treutel@hotmail.com", "Wallace", "DB", 1, "Treutel" },
                    { 694, 85, "Levi27@hotmail.com", "Levi", "DB", 0, "Donnelly" },
                    { 695, 72, "Cecelia.Schuppe48@hotmail.com", "Cecelia", "DB", 1, "Schuppe" },
                    { 696, 28, "Brian.Jacobi18@yahoo.com", "Brian", "DB", 1, "Jacobi" },
                    { 697, 61, "Jan_Schoen@gmail.com", "Jan", "DB", 1, "Schoen" },
                    { 698, 89, "Lynn94@hotmail.com", "Lynn", "DB", 0, "Heller" },
                    { 699, 67, "Alvin_Abbott65@gmail.com", "Alvin", "DB", 0, "Abbott" },
                    { 700, 71, "Rhonda_Hilpert@yahoo.com", "Rhonda", "DB", 0, "Hilpert" },
                    { 701, 89, "Bryant_Pouros99@hotmail.com", "Bryant", "DB", 1, "Pouros" },
                    { 702, 29, "Timothy.Schneider78@gmail.com", "Timothy", "DB", 1, "Schneider" },
                    { 703, 34, "Kate.Howell27@yahoo.com", "Kate", "DB", 1, "Howell" },
                    { 704, 55, "Laurie.Beatty17@yahoo.com", "Laurie", "DB", 1, "Beatty" },
                    { 705, 41, "Marvin_Schiller@yahoo.com", "Marvin", "DB", 0, "Schiller" },
                    { 706, 68, "Amber72@hotmail.com", "Amber", "DB", 1, "Langworth" },
                    { 707, 82, "Francis.Koss17@gmail.com", "Francis", "DB", 0, "Koss" },
                    { 708, 39, "Dominick.Cummerata@hotmail.com", "Dominick", "DB", 1, "Cummerata" },
                    { 709, 50, "Kelly98@yahoo.com", "Kelly", "DB", 0, "Casper" },
                    { 710, 90, "Gerald_Davis54@gmail.com", "Gerald", "DB", 0, "Davis" },
                    { 711, 55, "Terri_Brown@hotmail.com", "Terri", "DB", 1, "Brown" },
                    { 712, 51, "Rogelio80@yahoo.com", "Rogelio", "DB", 0, "Hagenes" },
                    { 713, 73, "Al41@gmail.com", "Al", "DB", 0, "Macejkovic" },
                    { 714, 56, "Lydia.Bayer@yahoo.com", "Lydia", "DB", 0, "Bayer" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 715, 45, "Lester.Fay@hotmail.com", "Lester", "DB", 1, "Fay" },
                    { 716, 48, "Elizabeth17@yahoo.com", "Elizabeth", "DB", 0, "Green" },
                    { 717, 63, "Latoya63@yahoo.com", "Latoya", "DB", 0, "Friesen" },
                    { 718, 40, "Alyssa_Padberg14@yahoo.com", "Alyssa", "DB", 1, "Padberg" },
                    { 719, 9, "Vicky.Schiller30@hotmail.com", "Vicky", "DB", 0, "Schiller" },
                    { 720, 78, "Patrick99@gmail.com", "Patrick", "DB", 1, "Rosenbaum" },
                    { 721, 90, "Cindy_Koss61@hotmail.com", "Cindy", "DB", 1, "Koss" },
                    { 722, 88, "Jeanette.Fadel98@gmail.com", "Jeanette", "DB", 1, "Fadel" },
                    { 723, 8, "Mattie_Feeney48@hotmail.com", "Mattie", "DB", 1, "Feeney" },
                    { 724, 60, "Mona.Yost54@yahoo.com", "Mona", "DB", 1, "Yost" },
                    { 725, 33, "Ollie_Gibson4@yahoo.com", "Ollie", "DB", 0, "Gibson" },
                    { 726, 25, "Derek47@hotmail.com", "Derek", "DB", 0, "Hegmann" },
                    { 727, 80, "Preston_Hammes74@gmail.com", "Preston", "DB", 1, "Hammes" },
                    { 728, 42, "Constance.OReilly@yahoo.com", "Constance", "DB", 0, "O'Reilly" },
                    { 729, 89, "Francis4@yahoo.com", "Francis", "DB", 1, "Tromp" },
                    { 730, 72, "Lee.Jerde@gmail.com", "Lee", "DB", 0, "Jerde" },
                    { 731, 19, "Dewey25@hotmail.com", "Dewey", "DB", 0, "Terry" },
                    { 732, 30, "Bennie_Kris16@yahoo.com", "Bennie", "DB", 1, "Kris" },
                    { 733, 88, "Wendell.Schmeler@gmail.com", "Wendell", "DB", 1, "Schmeler" },
                    { 734, 54, "Henry.Altenwerth83@gmail.com", "Henry", "DB", 0, "Altenwerth" },
                    { 735, 62, "Anita63@gmail.com", "Anita", "DB", 0, "Klocko" },
                    { 736, 31, "Tracey_Lind38@yahoo.com", "Tracey", "DB", 0, "Lind" },
                    { 737, 64, "Desiree12@yahoo.com", "Desiree", "DB", 0, "Witting" },
                    { 738, 71, "Ramon_Stoltenberg14@gmail.com", "Ramon", "DB", 0, "Stoltenberg" },
                    { 739, 70, "Ellis_Leannon@yahoo.com", "Ellis", "DB", 1, "Leannon" },
                    { 740, 75, "Gina40@gmail.com", "Gina", "DB", 1, "Goldner" },
                    { 741, 89, "Cory_Mayer53@gmail.com", "Cory", "DB", 1, "Mayer" },
                    { 742, 29, "Chelsea.Gutmann@gmail.com", "Chelsea", "DB", 1, "Gutmann" },
                    { 743, 63, "Patsy_Corkery58@gmail.com", "Patsy", "DB", 1, "Corkery" },
                    { 744, 57, "Hugo94@gmail.com", "Hugo", "DB", 1, "Russel" },
                    { 745, 9, "Irvin.Jerde43@hotmail.com", "Irvin", "DB", 1, "Jerde" },
                    { 746, 64, "Kari_Zemlak6@hotmail.com", "Kari", "DB", 0, "Zemlak" },
                    { 747, 90, "Clinton_Cartwright12@hotmail.com", "Clinton", "DB", 1, "Cartwright" },
                    { 748, 78, "Tyrone_OKeefe@hotmail.com", "Tyrone", "DB", 1, "O'Keefe" },
                    { 749, 34, "Emma.Runolfsdottir@gmail.com", "Emma", "DB", 1, "Runolfsdottir" },
                    { 750, 40, "Kirk51@hotmail.com", "Kirk", "DB", 1, "Volkman" },
                    { 751, 60, "Mandy1@gmail.com", "Mandy", "DB", 1, "Kemmer" },
                    { 752, 59, "Christie16@hotmail.com", "Christie", "DB", 1, "Muller" },
                    { 753, 79, "Terrance_Willms@gmail.com", "Terrance", "DB", 1, "Willms" },
                    { 754, 42, "Allen.Keebler82@hotmail.com", "Allen", "DB", 0, "Keebler" },
                    { 755, 88, "Hugh.Koepp16@gmail.com", "Hugh", "DB", 0, "Koepp" },
                    { 756, 38, "Arturo66@gmail.com", "Arturo", "DB", 0, "Barrows" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 757, 36, "Hattie.Thompson@yahoo.com", "Hattie", "DB", 1, "Thompson" },
                    { 758, 59, "James31@hotmail.com", "James", "DB", 1, "Schultz" },
                    { 759, 60, "Mercedes36@yahoo.com", "Mercedes", "DB", 0, "McDermott" },
                    { 760, 40, "Courtney.White@gmail.com", "Courtney", "DB", 0, "White" },
                    { 761, 74, "Duane.Larkin@gmail.com", "Duane", "DB", 0, "Larkin" },
                    { 762, 22, "Everett88@hotmail.com", "Everett", "DB", 1, "Streich" },
                    { 763, 42, "Jeannette.Skiles@gmail.com", "Jeannette", "DB", 0, "Skiles" },
                    { 764, 49, "Doreen.Lesch30@hotmail.com", "Doreen", "DB", 1, "Lesch" },
                    { 765, 13, "Alberta.Sawayn18@hotmail.com", "Alberta", "DB", 1, "Sawayn" },
                    { 766, 80, "Virgil.Hettinger65@yahoo.com", "Virgil", "DB", 1, "Hettinger" },
                    { 767, 8, "Jared96@hotmail.com", "Jared", "DB", 1, "Larkin" },
                    { 768, 33, "Melissa_Windler@yahoo.com", "Melissa", "DB", 0, "Windler" },
                    { 769, 88, "Jesus.Cassin@gmail.com", "Jesus", "DB", 0, "Cassin" },
                    { 770, 25, "Lori_Dicki@hotmail.com", "Lori", "DB", 1, "Dicki" },
                    { 771, 38, "Luke32@gmail.com", "Luke", "DB", 0, "Hoeger" },
                    { 772, 25, "Vicki.Wisoky10@yahoo.com", "Vicki", "DB", 1, "Wisoky" },
                    { 773, 10, "Tom_Hammes87@yahoo.com", "Tom", "DB", 1, "Hammes" },
                    { 774, 10, "Caroline.Gutkowski31@yahoo.com", "Caroline", "DB", 1, "Gutkowski" },
                    { 775, 15, "Marcos.Stanton72@hotmail.com", "Marcos", "DB", 1, "Stanton" },
                    { 776, 71, "Bessie.Stanton@yahoo.com", "Bessie", "DB", 1, "Stanton" },
                    { 777, 40, "Alicia_Hammes68@hotmail.com", "Alicia", "DB", 1, "Hammes" },
                    { 778, 32, "Cedric.Crist52@yahoo.com", "Cedric", "DB", 1, "Crist" },
                    { 779, 76, "Neal69@gmail.com", "Neal", "DB", 1, "Pfannerstill" },
                    { 780, 15, "Sammy.Wilkinson48@yahoo.com", "Sammy", "DB", 0, "Wilkinson" },
                    { 781, 61, "Carlos.Daniel14@yahoo.com", "Carlos", "DB", 1, "Daniel" },
                    { 782, 36, "Billy_Abshire74@gmail.com", "Billy", "DB", 1, "Abshire" },
                    { 783, 47, "Frank0@yahoo.com", "Frank", "DB", 0, "Barrows" },
                    { 784, 78, "Dexter40@yahoo.com", "Dexter", "DB", 0, "Bins" },
                    { 785, 81, "Theodore_Bayer@yahoo.com", "Theodore", "DB", 1, "Bayer" },
                    { 786, 66, "Johnny51@hotmail.com", "Johnny", "DB", 1, "Blanda" },
                    { 787, 19, "Erica64@gmail.com", "Erica", "DB", 0, "Hirthe" },
                    { 788, 64, "Carole44@hotmail.com", "Carole", "DB", 1, "Willms" },
                    { 789, 20, "Marjorie_Douglas25@yahoo.com", "Marjorie", "DB", 1, "Douglas" },
                    { 790, 63, "Eduardo.Davis43@yahoo.com", "Eduardo", "DB", 0, "Davis" },
                    { 791, 54, "Claire.Fay@yahoo.com", "Claire", "DB", 0, "Fay" },
                    { 792, 15, "Joanne_Hermiston@yahoo.com", "Joanne", "DB", 1, "Hermiston" },
                    { 793, 76, "Terrence89@hotmail.com", "Terrence", "DB", 1, "Durgan" },
                    { 794, 67, "Jane68@yahoo.com", "Jane", "DB", 1, "Hessel" },
                    { 795, 18, "Iris56@gmail.com", "Iris", "DB", 1, "Homenick" },
                    { 796, 40, "Charlotte_Walter99@hotmail.com", "Charlotte", "DB", 0, "Walter" },
                    { 797, 30, "Francis47@hotmail.com", "Francis", "DB", 0, "Stiedemann" },
                    { 798, 60, "Winston_Gleason41@hotmail.com", "Winston", "DB", 0, "Gleason" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 799, 34, "Pearl37@gmail.com", "Pearl", "DB", 1, "Ratke" },
                    { 800, 73, "Priscilla_Hudson90@yahoo.com", "Priscilla", "DB", 1, "Hudson" },
                    { 801, 24, "Bradford.Erdman8@gmail.com", "Bradford", "DB", 1, "Erdman" },
                    { 802, 70, "Roderick_Tillman69@yahoo.com", "Roderick", "DB", 0, "Tillman" },
                    { 803, 19, "Stephen.King96@gmail.com", "Stephen", "DB", 1, "King" },
                    { 804, 59, "Joy.Altenwerth9@hotmail.com", "Joy", "DB", 1, "Altenwerth" },
                    { 805, 54, "Kristen.Marks61@yahoo.com", "Kristen", "DB", 1, "Marks" },
                    { 806, 29, "Bobbie95@gmail.com", "Bobbie", "DB", 1, "Pacocha" },
                    { 807, 66, "Whitney.Kilback@hotmail.com", "Whitney", "DB", 0, "Kilback" },
                    { 808, 28, "Kelly_Wilkinson62@yahoo.com", "Kelly", "DB", 1, "Wilkinson" },
                    { 809, 39, "Cameron_Schmitt13@yahoo.com", "Cameron", "DB", 1, "Schmitt" },
                    { 810, 23, "Lloyd46@yahoo.com", "Lloyd", "DB", 0, "Ullrich" },
                    { 811, 53, "Travis_Fahey@yahoo.com", "Travis", "DB", 1, "Fahey" },
                    { 812, 8, "Eileen41@hotmail.com", "Eileen", "DB", 0, "Rau" },
                    { 813, 25, "Josephine_Windler@hotmail.com", "Josephine", "DB", 0, "Windler" },
                    { 814, 64, "Javier.Prosacco68@gmail.com", "Javier", "DB", 0, "Prosacco" },
                    { 815, 86, "Herbert96@hotmail.com", "Herbert", "DB", 1, "Bartell" },
                    { 816, 82, "Eileen.Metz@yahoo.com", "Eileen", "DB", 0, "Metz" },
                    { 817, 76, "Janet.Schneider@yahoo.com", "Janet", "DB", 1, "Schneider" },
                    { 818, 90, "Pam.Kihn65@yahoo.com", "Pam", "DB", 1, "Kihn" },
                    { 819, 23, "Zachary_Fisher23@gmail.com", "Zachary", "DB", 1, "Fisher" },
                    { 820, 74, "Evelyn_Bergnaum95@gmail.com", "Evelyn", "DB", 0, "Bergnaum" },
                    { 821, 26, "Eric_McLaughlin53@hotmail.com", "Eric", "DB", 1, "McLaughlin" },
                    { 822, 56, "Chelsea_Baumbach30@hotmail.com", "Chelsea", "DB", 1, "Baumbach" },
                    { 823, 57, "Melissa.Mills47@hotmail.com", "Melissa", "DB", 0, "Mills" },
                    { 824, 78, "Aubrey66@gmail.com", "Aubrey", "DB", 0, "Green" },
                    { 825, 76, "Shirley54@yahoo.com", "Shirley", "DB", 0, "Tromp" },
                    { 826, 80, "Darnell42@gmail.com", "Darnell", "DB", 1, "Wuckert" },
                    { 827, 46, "Kellie_Jaskolski@gmail.com", "Kellie", "DB", 0, "Jaskolski" },
                    { 828, 68, "Penny_Hagenes@yahoo.com", "Penny", "DB", 0, "Hagenes" },
                    { 829, 33, "Frederick84@gmail.com", "Frederick", "DB", 1, "Abernathy" },
                    { 830, 18, "Raymond.Walker@hotmail.com", "Raymond", "DB", 0, "Walker" },
                    { 831, 78, "Gwendolyn.Lehner@gmail.com", "Gwendolyn", "DB", 1, "Lehner" },
                    { 832, 27, "Heidi_Reichel27@hotmail.com", "Heidi", "DB", 1, "Reichel" },
                    { 833, 45, "Madeline.Cruickshank@hotmail.com", "Madeline", "DB", 0, "Cruickshank" },
                    { 834, 29, "Yolanda68@hotmail.com", "Yolanda", "DB", 0, "Torphy" },
                    { 835, 29, "Maureen23@hotmail.com", "Maureen", "DB", 1, "McGlynn" },
                    { 836, 32, "Jenna.Schiller71@gmail.com", "Jenna", "DB", 0, "Schiller" },
                    { 837, 37, "Debra.Ankunding@gmail.com", "Debra", "DB", 0, "Ankunding" },
                    { 838, 75, "Dustin.Leffler11@gmail.com", "Dustin", "DB", 1, "Leffler" },
                    { 839, 65, "Israel_Rempel24@hotmail.com", "Israel", "DB", 0, "Rempel" },
                    { 840, 35, "Josefina_Becker@gmail.com", "Josefina", "DB", 0, "Becker" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 841, 64, "Daniel32@gmail.com", "Daniel", "DB", 0, "Zemlak" },
                    { 842, 31, "Glen44@yahoo.com", "Glen", "DB", 1, "Morar" },
                    { 843, 72, "Camille80@yahoo.com", "Camille", "DB", 0, "Larson" },
                    { 844, 54, "Sonya_Rempel40@hotmail.com", "Sonya", "DB", 0, "Rempel" },
                    { 845, 54, "Albert_Berge48@yahoo.com", "Albert", "DB", 0, "Berge" },
                    { 846, 31, "Harvey_Hessel46@gmail.com", "Harvey", "DB", 1, "Hessel" },
                    { 847, 85, "Steve.Schuppe@yahoo.com", "Steve", "DB", 1, "Schuppe" },
                    { 848, 23, "Juan.Gaylord@hotmail.com", "Juan", "DB", 0, "Gaylord" },
                    { 849, 71, "Edna10@hotmail.com", "Edna", "DB", 0, "Greenholt" },
                    { 850, 69, "Troy.Kutch3@gmail.com", "Troy", "DB", 1, "Kutch" },
                    { 851, 13, "Sabrina.Adams@yahoo.com", "Sabrina", "DB", 0, "Adams" },
                    { 852, 61, "Gina36@hotmail.com", "Gina", "DB", 1, "Doyle" },
                    { 853, 82, "Francis_Ward82@hotmail.com", "Francis", "DB", 1, "Ward" },
                    { 854, 47, "Penny_Turcotte60@hotmail.com", "Penny", "DB", 0, "Turcotte" },
                    { 855, 59, "Stuart0@yahoo.com", "Stuart", "DB", 1, "Abshire" },
                    { 856, 35, "Regina.Abernathy39@hotmail.com", "Regina", "DB", 1, "Abernathy" },
                    { 857, 43, "Alan_Harber98@yahoo.com", "Alan", "DB", 1, "Harber" },
                    { 858, 76, "April_Gusikowski@hotmail.com", "April", "DB", 0, "Gusikowski" },
                    { 859, 45, "Ira_Yundt75@hotmail.com", "Ira", "DB", 0, "Yundt" },
                    { 860, 18, "Darlene99@yahoo.com", "Darlene", "DB", 1, "Johnson" },
                    { 861, 82, "Marco.Keebler@yahoo.com", "Marco", "DB", 0, "Keebler" },
                    { 862, 64, "Jonathan_Purdy85@yahoo.com", "Jonathan", "DB", 0, "Purdy" },
                    { 863, 11, "Lewis_Weber71@gmail.com", "Lewis", "DB", 0, "Weber" },
                    { 864, 77, "Annie_Rice1@gmail.com", "Annie", "DB", 1, "Rice" },
                    { 865, 45, "Ernest.Larson@hotmail.com", "Ernest", "DB", 1, "Larson" },
                    { 866, 60, "Debra44@gmail.com", "Debra", "DB", 1, "Reilly" },
                    { 867, 84, "Tara3@yahoo.com", "Tara", "DB", 0, "Rodriguez" },
                    { 868, 87, "Brandi_Brakus93@hotmail.com", "Brandi", "DB", 0, "Brakus" },
                    { 869, 36, "Noah.Wehner35@yahoo.com", "Noah", "DB", 0, "Wehner" },
                    { 870, 13, "Frank.Mills@yahoo.com", "Frank", "DB", 1, "Mills" },
                    { 871, 47, "Roberta_Farrell27@hotmail.com", "Roberta", "DB", 1, "Farrell" },
                    { 872, 21, "Stacey37@yahoo.com", "Stacey", "DB", 0, "Heller" },
                    { 873, 13, "Jane88@gmail.com", "Jane", "DB", 0, "Conn" },
                    { 874, 87, "Pamela58@hotmail.com", "Pamela", "DB", 0, "Armstrong" },
                    { 875, 69, "Tasha.Bechtelar@yahoo.com", "Tasha", "DB", 1, "Bechtelar" },
                    { 876, 90, "Kelli70@gmail.com", "Kelli", "DB", 1, "Murazik" },
                    { 877, 32, "Robin_Gulgowski@gmail.com", "Robin", "DB", 0, "Gulgowski" },
                    { 878, 55, "Cesar_Ebert7@yahoo.com", "Cesar", "DB", 1, "Ebert" },
                    { 879, 42, "Walter52@gmail.com", "Walter", "DB", 0, "Willms" },
                    { 880, 54, "Beatrice.Breitenberg54@gmail.com", "Beatrice", "DB", 1, "Breitenberg" },
                    { 881, 19, "Tasha.Toy35@yahoo.com", "Tasha", "DB", 0, "Toy" },
                    { 882, 83, "Simon97@hotmail.com", "Simon", "DB", 0, "Goodwin" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 883, 10, "Duane0@hotmail.com", "Duane", "DB", 1, "Pfeffer" },
                    { 884, 70, "Natasha.Hand@gmail.com", "Natasha", "DB", 0, "Hand" },
                    { 885, 17, "Dianne.Lynch43@hotmail.com", "Dianne", "DB", 1, "Lynch" },
                    { 886, 82, "Molly55@yahoo.com", "Molly", "DB", 0, "Jaskolski" },
                    { 887, 51, "Becky.Herman61@yahoo.com", "Becky", "DB", 0, "Herman" },
                    { 888, 18, "Wilbert_Morar@gmail.com", "Wilbert", "DB", 0, "Morar" },
                    { 889, 8, "Marianne81@gmail.com", "Marianne", "DB", 1, "Waelchi" },
                    { 890, 46, "Henrietta_Herman@gmail.com", "Henrietta", "DB", 0, "Herman" },
                    { 891, 50, "Lillie71@hotmail.com", "Lillie", "DB", 1, "Legros" },
                    { 892, 28, "Mae19@gmail.com", "Mae", "DB", 0, "Hahn" },
                    { 893, 24, "Albert.McLaughlin14@hotmail.com", "Albert", "DB", 1, "McLaughlin" },
                    { 894, 83, "Krista_Sauer@gmail.com", "Krista", "DB", 0, "Sauer" },
                    { 895, 82, "Scott64@hotmail.com", "Scott", "DB", 0, "Weimann" },
                    { 896, 17, "Jeffery_Gutmann32@hotmail.com", "Jeffery", "DB", 0, "Gutmann" },
                    { 897, 12, "Carmen61@gmail.com", "Carmen", "DB", 1, "Harris" },
                    { 898, 32, "Kim9@gmail.com", "Kim", "DB", 1, "Smitham" },
                    { 899, 18, "Margaret86@hotmail.com", "Margaret", "DB", 1, "Daugherty" },
                    { 900, 46, "Anne18@hotmail.com", "Anne", "DB", 1, "Feil" },
                    { 901, 57, "Wilbert50@gmail.com", "Wilbert", "DB", 1, "Moore" },
                    { 902, 84, "Marjorie_Windler@gmail.com", "Marjorie", "DB", 0, "Windler" },
                    { 903, 28, "Merle.Moore83@yahoo.com", "Merle", "DB", 0, "Moore" },
                    { 904, 69, "Glenn68@gmail.com", "Glenn", "DB", 0, "Aufderhar" },
                    { 905, 67, "Delia_Paucek@hotmail.com", "Delia", "DB", 0, "Paucek" },
                    { 906, 61, "Candice.Nicolas44@gmail.com", "Candice", "DB", 0, "Nicolas" },
                    { 907, 33, "Rolando_Gleichner@yahoo.com", "Rolando", "DB", 1, "Gleichner" },
                    { 908, 45, "Margaret.Will@yahoo.com", "Margaret", "DB", 0, "Will" },
                    { 909, 43, "Maureen82@yahoo.com", "Maureen", "DB", 1, "Leuschke" },
                    { 910, 22, "Dewey.Waelchi@yahoo.com", "Dewey", "DB", 0, "Waelchi" },
                    { 911, 74, "Natalie_Bednar@gmail.com", "Natalie", "DB", 1, "Bednar" },
                    { 912, 46, "Erick73@yahoo.com", "Erick", "DB", 1, "Little" },
                    { 913, 13, "Rosalie18@gmail.com", "Rosalie", "DB", 1, "Ullrich" },
                    { 914, 62, "Amanda52@gmail.com", "Amanda", "DB", 0, "Schoen" },
                    { 915, 42, "Warren_VonRueden83@hotmail.com", "Warren", "DB", 1, "VonRueden" },
                    { 916, 15, "Johnnie38@gmail.com", "Johnnie", "DB", 0, "Murphy" },
                    { 917, 55, "Leroy.Rice@gmail.com", "Leroy", "DB", 0, "Rice" },
                    { 918, 44, "Jerome.Hermiston11@yahoo.com", "Jerome", "DB", 1, "Hermiston" },
                    { 919, 40, "Bethany27@yahoo.com", "Bethany", "DB", 1, "McDermott" },
                    { 920, 8, "Kathleen71@hotmail.com", "Kathleen", "DB", 1, "Schamberger" },
                    { 921, 21, "Pedro33@hotmail.com", "Pedro", "DB", 0, "Kreiger" },
                    { 922, 28, "Jaime.Boyer@gmail.com", "Jaime", "DB", 1, "Boyer" },
                    { 923, 89, "Emma_Heathcote45@yahoo.com", "Emma", "DB", 0, "Heathcote" },
                    { 924, 61, "Eddie.Reichel27@yahoo.com", "Eddie", "DB", 1, "Reichel" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 925, 90, "Angel_Kris@yahoo.com", "Angel", "DB", 0, "Kris" },
                    { 926, 79, "Shelia_Abernathy86@gmail.com", "Shelia", "DB", 1, "Abernathy" },
                    { 927, 23, "Miriam.Gleason22@gmail.com", "Miriam", "DB", 1, "Gleason" },
                    { 928, 84, "Troy_Cummerata53@gmail.com", "Troy", "DB", 0, "Cummerata" },
                    { 929, 21, "Jose_Howell@yahoo.com", "Jose", "DB", 1, "Howell" },
                    { 930, 17, "Norma3@yahoo.com", "Norma", "DB", 0, "Weissnat" },
                    { 931, 27, "Robert17@yahoo.com", "Robert", "DB", 1, "Bayer" },
                    { 932, 42, "Gregg_Kub80@gmail.com", "Gregg", "DB", 1, "Kub" },
                    { 933, 35, "Nathan_Konopelski53@gmail.com", "Nathan", "DB", 0, "Konopelski" },
                    { 934, 11, "Paulette25@yahoo.com", "Paulette", "DB", 0, "Morissette" },
                    { 935, 48, "Van_Walsh@hotmail.com", "Van", "DB", 1, "Walsh" },
                    { 936, 11, "Charlotte30@hotmail.com", "Charlotte", "DB", 0, "Armstrong" },
                    { 937, 60, "Darryl.Ankunding5@gmail.com", "Darryl", "DB", 0, "Ankunding" },
                    { 938, 53, "Lela.Baumbach@gmail.com", "Lela", "DB", 0, "Baumbach" },
                    { 939, 9, "Mario_Raynor45@yahoo.com", "Mario", "DB", 1, "Raynor" },
                    { 940, 27, "Chester.Kreiger@hotmail.com", "Chester", "DB", 1, "Kreiger" },
                    { 941, 35, "Kayla94@gmail.com", "Kayla", "DB", 0, "Hartmann" },
                    { 942, 40, "Steven_Jerde@gmail.com", "Steven", "DB", 1, "Jerde" },
                    { 943, 33, "Roger.Mertz@yahoo.com", "Roger", "DB", 1, "Mertz" },
                    { 944, 9, "Christopher.Runte77@yahoo.com", "Christopher", "DB", 0, "Runte" },
                    { 945, 38, "Suzanne.Dooley@gmail.com", "Suzanne", "DB", 0, "Dooley" },
                    { 946, 60, "Jenna52@yahoo.com", "Jenna", "DB", 0, "Swaniawski" },
                    { 947, 54, "Justin_Kreiger@yahoo.com", "Justin", "DB", 1, "Kreiger" },
                    { 948, 48, "Violet.Durgan@yahoo.com", "Violet", "DB", 0, "Durgan" },
                    { 949, 78, "Tami75@hotmail.com", "Tami", "DB", 1, "Hamill" },
                    { 950, 85, "Jay60@gmail.com", "Jay", "DB", 1, "Connelly" },
                    { 951, 21, "Shannon37@hotmail.com", "Shannon", "DB", 0, "Kiehn" },
                    { 952, 52, "Anna38@gmail.com", "Anna", "DB", 0, "Walker" },
                    { 953, 45, "Jacob55@hotmail.com", "Jacob", "DB", 0, "Hane" },
                    { 954, 70, "Joshua49@gmail.com", "Joshua", "DB", 0, "Fisher" },
                    { 955, 25, "Nick54@yahoo.com", "Nick", "DB", 1, "Schneider" },
                    { 956, 68, "Greg.Zulauf84@yahoo.com", "Greg", "DB", 1, "Zulauf" },
                    { 957, 15, "Cary_Cruickshank67@yahoo.com", "Cary", "DB", 0, "Cruickshank" },
                    { 958, 46, "Heidi_Kris@yahoo.com", "Heidi", "DB", 1, "Kris" },
                    { 959, 29, "Julia85@yahoo.com", "Julia", "DB", 0, "Hintz" },
                    { 960, 17, "Johnnie83@hotmail.com", "Johnnie", "DB", 0, "Beier" },
                    { 961, 63, "Harold.Johns@hotmail.com", "Harold", "DB", 0, "Johns" },
                    { 962, 90, "Mildred8@yahoo.com", "Mildred", "DB", 1, "Howell" },
                    { 963, 21, "Jose_Bashirian@gmail.com", "Jose", "DB", 0, "Bashirian" },
                    { 964, 77, "Tricia39@yahoo.com", "Tricia", "DB", 0, "Nikolaus" },
                    { 965, 44, "Dean.Hoeger@yahoo.com", "Dean", "DB", 0, "Hoeger" },
                    { 966, 67, "Ginger.Kling@gmail.com", "Ginger", "DB", 1, "Kling" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Age", "Email", "FirstName", "Framework", "Gender", "LastName" },
                values: new object[,]
                {
                    { 967, 34, "Robin1@gmail.com", "Robin", "DB", 0, "Bernier" },
                    { 968, 87, "Esther.Mosciski@yahoo.com", "Esther", "DB", 0, "Mosciski" },
                    { 969, 61, "Albert.Crona@yahoo.com", "Albert", "DB", 1, "Crona" },
                    { 970, 19, "Tonya_Gerhold@yahoo.com", "Tonya", "DB", 0, "Gerhold" },
                    { 971, 49, "Jorge12@yahoo.com", "Jorge", "DB", 0, "Goodwin" },
                    { 972, 33, "Theodore94@hotmail.com", "Theodore", "DB", 0, "Koelpin" },
                    { 973, 32, "Tricia.Tillman@gmail.com", "Tricia", "DB", 0, "Tillman" },
                    { 974, 24, "Robin.Maggio@hotmail.com", "Robin", "DB", 1, "Maggio" },
                    { 975, 37, "Patti.Mante94@yahoo.com", "Patti", "DB", 0, "Mante" },
                    { 976, 35, "Winifred76@yahoo.com", "Winifred", "DB", 1, "Mohr" },
                    { 977, 53, "Sidney.Marquardt54@hotmail.com", "Sidney", "DB", 1, "Marquardt" },
                    { 978, 67, "May78@hotmail.com", "May", "DB", 1, "O'Kon" },
                    { 979, 74, "Lillian.Morissette29@gmail.com", "Lillian", "DB", 1, "Morissette" },
                    { 980, 54, "Neil.Reinger@hotmail.com", "Neil", "DB", 1, "Reinger" },
                    { 981, 64, "Spencer89@gmail.com", "Spencer", "DB", 1, "Keebler" },
                    { 982, 86, "Clyde_Friesen49@yahoo.com", "Clyde", "DB", 0, "Friesen" },
                    { 983, 67, "Ralph.Barrows96@hotmail.com", "Ralph", "DB", 0, "Barrows" },
                    { 984, 64, "Ellen2@hotmail.com", "Ellen", "DB", 0, "Littel" },
                    { 985, 34, "Andrea.Terry46@hotmail.com", "Andrea", "DB", 1, "Terry" },
                    { 986, 8, "Christina_Mosciski@hotmail.com", "Christina", "DB", 1, "Mosciski" },
                    { 987, 52, "Gloria45@hotmail.com", "Gloria", "DB", 0, "Herzog" },
                    { 988, 35, "Sylvia74@hotmail.com", "Sylvia", "DB", 1, "Predovic" },
                    { 989, 65, "Andy_Sauer@yahoo.com", "Andy", "DB", 1, "Sauer" },
                    { 990, 47, "Norma78@hotmail.com", "Norma", "DB", 0, "Runte" },
                    { 991, 23, "Marc28@hotmail.com", "Marc", "DB", 1, "Schuppe" },
                    { 992, 88, "May83@yahoo.com", "May", "DB", 0, "Block" },
                    { 993, 34, "Christy_Jerde@hotmail.com", "Christy", "DB", 1, "Jerde" },
                    { 994, 43, "Edmond.Maggio@gmail.com", "Edmond", "DB", 1, "Maggio" },
                    { 995, 52, "Leslie.Collier@gmail.com", "Leslie", "DB", 0, "Collier" },
                    { 996, 14, "Milton_Bergstrom@yahoo.com", "Milton", "DB", 0, "Bergstrom" },
                    { 997, 18, "Kimberly.Wisozk@gmail.com", "Kimberly", "DB", 1, "Wisozk" },
                    { 998, 60, "Jake.Bode@hotmail.com", "Jake", "DB", 1, "Bode" },
                    { 999, 89, "Ronald_Emmerich@gmail.com", "Ronald", "DB", 0, "Emmerich" },
                    { 1000, 11, "Tyler21@hotmail.com", "Tyler", "DB", 1, "Kihn" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
